api/main.go
Closed :#16
I changed JWT secret to get environment variables.
https://golang.org/pkg/os/#Getenv
=> api: Remove hard code of JWT secret

ui/src/api/devices.js, ui/src/components/DeviceFeature.vue, ui/src/components/DeviceList.vue, ui/src/modules/devices.js, ui/src/router.js, ui/src/views/FeatureDevice.vue
Added icon details in list device to redirect page features devices.
=> Added to the device features page

gateway/shellhub.conf, ssh/main.go, ssh/server.go, ui/src/api/sessions.js, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/modules/sessions.js
Co-authored-by: leonardojoao <ldrsjoao@inf.ufpel.edu.br>
=> ui: ssh: agent: add close session route

.github/workflows/ci.yml, agent/main.go, api/pkg/services/deviceadm/service.go, pkg/models/device.go
=> github: Add linting workflow

.github/workflows/commit.yml
=> github: Add commit message sanity check

api/pkg/services/deviceadm/service.go, api/pkg/store/mongo/store.go
fix when no filter is selected
=> api: fix listDevices when no filter is present

.gitignore, agent/Dockerfile, api/Dockerfile, scripts/lint-code, ssh/Dockerfile, ui/package.json
=> script: Add a lint-code helper so we audit Golang and Vue easily

ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceIcon.vue, ui/src/components/device/DeviceList.vue, ui/src/plugins/vuetify.js
A new component for device icons was created, 
additional tooltips for icons in deviceList were
defined as well.
=> ui: Removing icons duplication

agent/Dockerfile.amd64, agent/Dockerfile.arm32v6, agent/Dockerfile.arm64v8
The setpriv binary is required for changing user's shell privileges
=> agent: install setpriv on container

ui/src/router/index.js
Router.js moves to router directory and renames it to index.js.
Because, when create the vue project the behavior default.
=> ui: move the routers

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceList.vue, ui/src/components/session/SessionList.vue, ui/src/components/terminal/TerminalDialog.vue
A device delete component was added to
the device folder which consists in a 
vuetify dialog. Remaining tooltips for other 
icons were also set.
=> ui: Integrating a device delete component 

ui/src/components/device/DeviceList.vue
The link to specific device was configured
to device list hostname field as in sessions
Closes #128
=> ui: Accessing device by hostname in device list

ui/.eslintrc.js, ui/jest.config.js, ui/package-lock.json, ui/package.json, ui/tests/unit/example.spec.js, ui/tests/unit/index.js
It's the first commit using jest unit test.
=> ui: implementing unit test on Login

api/pkg/store/mongo/migrations.go, api/pkg/store/mongo/utils.go
=> api: Refactor migration code to avoid using duplicated code

ui/src/api/devices.js, ui/src/components/device/DeviceList.vue, ui/src/modules/devices.js
It's now possible for the user to search devices on the view device list.
=> ui: search devices by name

agent/keypair.go
=> agent: create parent directory if it does not exist

.github/workflows/docker-build-validation.yml, api/Dockerfile
We need to build the docker, but don't publish it.
=> cicd: starting docker build validation

ui/package-lock.json, ui/package.json, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceRename.vue
A component for renaming device was included,
it consists of a Vuetify dialog that provides
frontend validation for hostname according
to RFC1123.
=> Creating a rename dialog component

ui/src/views/Login.vue, ui/tests/unit/Login.spec.js, ui/tests/unit/VuexAuth.spec.js, ui/tests/unit/VuexDevices.spec.js, ui/tests/unit/VuexModals.spec.js, ui/tests/unit/VuexSessions.spec.js, ui/tests/unit/VuexStats.spec.js
The test is considering default variables
=> ui: creating test for the getters and removing unused code

ui/src/views/Dashboard.vue, ui/tests/unit/Dashboard.spec.js
This code testing the vuex, and buttons.
=> ui: testing the components of the dashboard

api/go.mod, api/go.sum, api/pkg/store/mongo/store.go, pkg/models/device.go, sonar-project.properties, ssh/go.mod, ssh/go.sum
the operations "and" and "or" are supported in the filter
=> api: support to multiple filters

ui/src/components/welcome/Welcome.vue, ui/src/components/welcome/WelcomeFirstScreen.vue, ui/src/components/welcome/WelcomeSecondScreen.vue, ui/src/components/welcome/WelcomeThirdScreen.vue, ui/src/modules/auth.js, ui/src/modules/modals.js, ui/src/views/Dashboard.vue
A welcome component composed of different screens
about Shellhub features was created using the
polling sync functionality. It forces the user to add a
device in order to proceed.
=> Creation of a Welcome Component

README.md
Removing duplication of word 'the'
=> readme: Removing duplication of word 'the'

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceRename.vue, ui/src/components/session/SessionDetails.vue, ui/src/components/terminal/TerminalDialog.vue, ui/src/views/Dashboard.vue
The dialogs were formatted according to the convention
used. Slight improvements in components display messages
and notFound alert were set as well.
=> ui: Formatting dialogs and display

ui/src/components/terminal/TerminalDialog.vue
Fix regression introducted by xterm 4.7.0
=> ui: auto fit terminal width

ui/src/App.vue
This refactory is important for adding other items to the menu.
You can now add additional items in the list menu with the path
and configure the routers to redirect to the page.
=> ui: refatory the user menu

api/main.go, api/pkg/services/deviceadm/service.go, api/pkg/services/firewall/service.go, api/pkg/services/sessionmngr/service.go, api/pkg/store/mongo/store.go, api/pkg/store/store.go, pkg/api/paginator/query.go
Moved pagination logic into paginator component to reduce code duplication
=> api: add paginator pkg

ui/package-lock.json, ui/package.json, ui/src/components/firewall_rules/FirewallRulesFormDialog.vue, ui/src/main.js, ui/src/vee-validate.js
The rules are configured in a single file, centralized to validations.
The library is used to verify the form when creating and editing firewall rules.
=> ui: add library vee validade, and validate firewall rules form

.github/workflows/qa.yml
=> cicd:  remove sonarcloud scan

gateway/Dockerfile, gateway/install.sh, gateway/shellhub.conf
=> gateway: use sudo in install script if necessary

ui/package-lock.json, ui/package.json, ui/src/api/sessions.js, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/components/session/SessionPlay.vue, ui/src/modules/sessions.js
A new component for playing session was defined, which displays collected log data
in a xtermjs instance, providing features like pausing, time formatting, frame logic and
control of speed for the session.
=> ui: Create new SessionPlay Component

api/authsvc/service.go, api/firewall/service.go, api/routes/auth.go, api/routes/firewall.go, ssh/session.go
This has no semantic changes. All trivial lints fixes.
=> api, ssh: Fix 'revive' warnings

api/store/mongo/migrations.go
correct version name and status update, fix returns
=> api: fix migrations bug

.github/workflows/qa.yml
Documentation: https://github.com/actions/cache
=> cicd: cache actions should be before go mod

ssh/go.sum, ssh/server.go, ssh/session.go
=> ssh: use case insensitive sshid in hostname lookup

.github/workflows/build-agent.yml
We need to fix the arch name on build phase
=> cicd: fix the arch name

.github/workflows/build-tag-push-go.yml, gateway/Dockerfile, ui/Dockerfile
rename the workflow file name to build go
add another workflow to buil ui and gateway image
dockerfiles need to follow the path standard
=> cicd: adding ui and gateway build

ui/src/main.js, ui/src/store/helpers/http.js, ui/src/store/modules/auth.js, ui/src/views/Dashboard.vue, ui/src/views/Login.vue
Add promises to the authentication modules and this corrects the
problem with a console request error when the request fails.
=> Fix login issues

ui/src/components/session/SessionPlay.vue
The cursor of slider is now paused when dragged.
Additional fixes for syncronism of the session were made.
=> ui: Fix timeSlider in playsession

ssh/session.go
=> ssh: fix newline terminal

ui/src/views/Dashboard.vue
Use the v-for on list cards, it is possible to reuse the same code.
And to add new items, you must have items in the list data.
=> ui: Refactor dashboard to use for to list cards

api/deviceadm/service.go, api/store/mongo/migrations.go
=> api: only allow lowercase hostname

.github/workflows/commit.yml
=> cicd: commit: Accept dependabot commit logs as valid

agent/main.go, api/authsvc/service.go, api/authsvc/service_test.go, api/store/mocks/store.go, api/store/mongo/store.go, api/store/mongo/store_test.go, api/store/store.go, gateway/install.sh, gateway/shellhub.conf, pkg/models/device.go
=> api, agent: set DeviceIdentity hostname via env docker var

agent/selfupdater/updater_docker.go
Append /dev to mount if old container version is less than v0.4.0 since /dev from host is required inside container to mount a pseudo-tty
=> agent: append /dev to mount list when updating container

ui/src/views/Login.vue, ui/tests/unit/views/Login.spec.js
New tests verify the variables used in login. And change data-cy to data-test.
=> ui: Update unit test for Login

agent/main.go, api/go.mod, docker-compose.dev.yml, gateway/install.sh, gateway/shellhub.conf
Also process unprefixed env vars for backward compatibility
=> agent: use prefix for env vars

.github/workflows/build-agent.yml
the build agent shouldn't push image on PR
=> cicd: workflow refactor

ui/src/components/session/SessionDetails.vue, ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js
New verification of the received fields in the
store were added to sessionDetails.
=> ui: Update test for sessiondetails

ssh/ssh2ws.go
=> ssh: fix WebSocket frame utf8 encoding

.github/workflows/commit.yml
exclude PR description from commit check
specify the ubuntu version
=> cicd: add commit check from PR

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceRename.vue, ui/src/components/firewall_rules/FirewallRulesDelete.vue, ui/src/components/firewall_rules/FirewallRulesFormDialog.vue, ui/src/components/session/SessionClose.vue, ui/src/components/setting/SettingProfile.vue, ui/src/components/snackbar/Snackbar.vue, ui/src/components/snackbar/SnackbarSuccess.vue, ui/src/main.js, ui/src/store/modules/modals.js, ui/src/success.js
The update allows the use of qualifying messages for the user to see
in case of succeess on the following pages: device, session and
firewall rule.
=> ui: Update snackbarSuccess component to add new success messages

.github/workflows/qa.yml
Expected behavior:
Changes to the golang folders trigger go jobs.
Changes to the ui folder trigger js jobs.
=> cicd: add filter for monorepo trigger

ui/src/components/welcome/Welcome.vue, ui/src/views/Dashboard.vue
This solves the problem when the user has pending and reject device
and device not accepted.
=> ui: Fix not show welcome screen when user has device

ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js, ui/tests/unit/components/session/SessionPlay.spec.js
This remove variable declare inside store to scope, add blank line,
and organizes just like #414.
=> ui: standard tests in the session directory

ui/src/components/device/Device.vue, ui/src/components/device/DeviceList.vue, ui/src/components/device/DevicePendingList.vue, ui/src/components/device/DeviceRejectedList.vue, ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/DevicePendingList.spec.js, ui/tests/unit/components/device/DeviceRejectedList.spec.js
A verification of data-table items in devicelist was added.
This closes #417.
=> ui: Update unit tests in device list

ui/tests/unit/components/firewall_rule/FirewallRulesDelete.spec.js, ui/tests/unit/components/firewall_rule/FirewallRulesFormDialog.spec.js, ui/tests/unit/components/firewall_rule/FirewallRulesList.spec.js
=> ui: Update test on the firewall rules components

ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionPlay.spec.js
=> ui: Update test on the session components

ui/tests/unit/components/device/DeviceActionButton.spec.js, ui/tests/unit/components/device/DeviceAdd.spec.js
Verification was added for methods and computed properties.
This closes #431 and #432.
=> ui: Update tests DeviceAdd and DeviceActiveButton

ui/tests/unit/views/Dashboard.spec.js, ui/tests/unit/views/Login.spec.js, ui/tests/unit/views/Sessions.spec.js
=> ui: Standard tests in the views directory

ui/tests/unit/components/snackbar/Snackbar.spec.js, ui/tests/unit/components/snackbar/SnackbarCopy.spec.js, ui/tests/unit/components/snackbar/SnackbarError.spec.js, ui/tests/unit/components/snackbar/SnackbarSuccess.spec.js
=> ui: Add test to snackbar components

ui/src/components/terminal/TerminalDialog.vue, ui/tests/unit/components/terminal/TerminalDialog.spec.js
=> ui: update terminal component tests

bin/docker-compose
This commit replaces PR #409. Closes #407
=> bin: fix docker-compose script for Darwin

ui/src/components/welcome/Welcome.vue, ui/src/components/welcome/WelcomeSecondScreen.vue, ui/src/components/welcome/WelcomeThirdScreen.vue, ui/tests/unit/components/welcome/Welcome.spec.js, ui/tests/unit/components/welcome/WelcomeFirstScreen.spec.js, ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js, ui/tests/unit/components/welcome/WelcomeThirdScreen.spec.js
The test verify the computed, method and props. And simule navigation
between steps.
=> ui: Update test on welcome, use the event click to move between steps

ui/src/App.vue, ui/tests/index.js, ui/tests/unit/App.spec.js
This test the menu and settings rendering with the defined fields.
=> ui: Create test for the app file

.github/workflows/commit.yml
Signed-off-by: Jonathas-Conceicao <jonathas.conceicao@ossystems.com.br>
=> cicd: Ignore checking commit messages for dependabot

README.md
Signed-off-by: Jonathas-Conceicao <jonathas.conceicao@ossystems.com.br>
=> README: fix link on QA status badge

api/store/mocks/store.go, api/store/mongo/store.go, api/store/mongo/store_test.go, api/store/store.go
=> api: insert a flag to sinalize if you want count devices and sessions

ui/package-lock.json, ui/package.json, ui/src/components/setting/SettingProfile.vue, ui/tests/unit/components/setting/SettingProfile.spec.js
A new plugin for flush promises was added as well.
=> ui: Add vee-validate tests in settigProfile component

ui/src/App.vue, ui/src/components/device/Device.vue, ui/src/components/firewall_rules/FirewallRulesFormDialog.vue, ui/src/views/Dashboard.vue
Higher contrast makes components easier to see, alignment of components to create visual pattern and component size hierarchy to show how important something is
=> ui: Add higher contrast, alignment and use size hierarchy in the v-card

agent/main.go
=> agent: add check to ensure process is run as root

ui/src/components/device/DeviceList.vue
=> ui: fix SSHID copy clipboard

agent/main.go
This PR is all about code rework for cleanness so it is not intended to add new features or do massive reworks, just small ones.
=> agent: Small code rework

agent/main.go
small change for 
https://github.com/shellhub-io/shellhub/issues/183
=> agent: show envconfig usage help users to run agent

api/store/mocks/store.go, api/store/mongo/store.go, api/store/mongo/store_test.go, api/store/store.go, pkg/models/user.go
list and export users with filtering by number of namespaces of each user
=> api: export users by number of namespaces

ui/src/components/device/DeviceAdd.vue, ui/src/components/welcome/Welcome.vue, ui/tests/unit/components/device/DeviceAdd.spec.js, ui/tests/unit/components/welcome/Welcome.spec.js, ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js
Added changes mentioned in #638
=> ui: Fixed command displayed when added devices

ui/src/components/app_bar/notification/Notification.vue, ui/src/components/setting/SettingSecurity.vue
=> ui: verify association in first-pending request

ui/src/components/setting/SettingNamespace.vue, ui/tests/unit/components/setting/SettingNamespace.spec.js
Unit tests for settingNamespace were also updated.
=> ui: show member list in open version

docker-compose.autossl.yml, docker-compose.dev.yml, docker-compose.enterprise.yml, docker-compose.yml
Always restart the container unless it is manually stopped even after Docker daemon restarts (system reboot).
=> docker: added restarty policy to docker-compose files

.gitignore, api/authsvc/service.go, api/main.go
Also added to be ignored binary files generated by the API.
=> api: small fix on formatting

api/store/mongo/migrations.go, api/store/mongo/store.go
when a user is deleted,  your namespaces need to be deleted too.  And when a namespaces is deleted, your devices need to be deleted too
=> api: fix partial delete

api/store/mongo/store_test.go
=> api: store: test: Enable all tests

api/authsvc/service.go, api/store/mongo/store.go, api/store/store.go
This commit, fix the login problem when the user has not registered a namespace.
=> api: Fix login

.github/workflows/build-agent.yml, agent/Dockerfile.i386
=> agent: Add i386 support to the Docker images

docker-compose.yml, pkg/api/client/client.go, pkg/api/client/logger.go, pkg/api/webhook/types.go, pkg/api/webhook/webhook.go, ssh/server.go, ssh/session.go
=> On-demand connections

pkg/api/client/client_internal.go
avoid unauthorized login when geyPubclicKey returns 404
=> pkg: client: fix err return in GetPublicKey

api/sshkeys/service.go, api/sshkeys/service_test.go, api/store/mongo/migrations.go
=> api: fix error on pubkeys with different tenant

ui/src/components/app_bar/AppBar.vue, ui/src/components/app_bar/namespace/NamespaceInstructions.vue, ui/src/components/app_bar/namespace/NamespaceMenu.vue, ui/src/components/app_bar/notification/Notification.vue, ui/src/store/modules/namespaces.js, ui/src/views/Dashboard.vue
This commit resolves some errors when the user logs in and has no
namespace.
When the user's login account has a namespace and after logging in
another account has no namespace, the instructions do not appear,
this commit corrects that.
=> ui: Resolve erros in console and fix show instructions namespace

.github/workflows/qa.yml
=> cicd: Upgrade Go to 1.16

ui/src/components/snackbar/SnackbarError.vue, ui/src/errors.js, ui/src/store/helpers/http.js, ui/src/store/modules/auth.js, ui/src/store/modules/snackbar.js, ui/src/views/Login.vue, ui/tests/unit/store/Snackbar.spec.js
This changes also fix some console errors.
=> ui: add snackbar incorrect in login

ui/src/views/SignUp.vue
=> ui: fix username signup validation

ui/src/components/public_key/KeyFormDialog.vue
=> ui: add support message for valid key types

.github/workflows/build-agent.yml
Replace the deprcated crazy-max/ghaction-docker-buildx with the
docker/setup-qemu-action and the docker/setup-buildx-action
=> cicd: update workflow for buildx

bin/add-namespace, cli/main.go, cli/service.go
=> cli: small fixes on cli

ui/src/components/app_bar/namespace/NamespaceAdd.vue
=> ui: Show message when namespace name already in use

api/store/mongo/migrations.go
=> api: fix migrations to remove orphan sessions and records

ui/src/App.vue, ui/src/components/app_bar/AppBar.vue, ui/tests/unit/components/app_bar/AppBar.spec.js
=> ui: fix showing the navigation drawer on mobile

cli/main.go
=> cli: fix the error when the provided input is not enough

api/authsvc/service.go, api/nsadm/service.go, api/nsadm/service_test.go, api/routes/nsadm.go, api/store/mongo/migrations.go, api/store/mongo/store_test.go, cli/service.go, cli/service_test.go, pkg/models/namespace.go
=> api: Remove dependency on bson package from API services

cli/error.go, cli/service.go
=> cli: display more meaningful errors to the user

ui/src/App.vue, ui/src/components/app_bar/AppBar.vue, ui/src/components/app_bar/namespace/NamespaceMenu.vue, ui/src/plugins/vuetify.js, ui/src/store/index.js, ui/src/store/modules/mobile.js, ui/tests/unit/App.spec.js, ui/tests/unit/components/app_bar/AppBar.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js
This code is refactored, as it is the best way to check in any
component if the user is accessing from a mobile.
=> ui: refactor the code in relation to usability in mobile

cli/README.md, cli/service_test.go
=> cli: add documentation for the service

ui/src/components/public_key/KeyDelete.vue, ui/src/store/modules/private_keys.js, ui/tests/unit/store/PrivateKeys.spec.js
This commit deletes the correct private key.
=> ui: fix delete private key

agent/sshd/cmd_docker.go
These changes add verification for the existance of system namespace related files
in order to dinamically change nsenter command arguments.
=> agent: add verification for nsenter arguments

agent/Dockerfile, agent/Dockerfile.amd64, agent/Dockerfile.arm32v6, agent/Dockerfile.arm32v7, agent/Dockerfile.arm64v8, agent/Dockerfile.i386, api/Dockerfile, cli/Dockerfile, ssh/Dockerfile
=> docker: Upgrade golang to 1.16.4

ui/src/components/app_bar/namespace/NamespaceNewMember.vue, ui/src/components/public_key/KeyFormDialog.vue, ui/src/components/setting/SettingNamespace.vue, ui/src/components/setting/SettingProfile.vue, ui/src/views/SignUp.vue
when has a form, use the obs tag. But, when there are two forms in
the component, in the second form use the pass tag.
=> ui: apply tag pattern in validation

ui/src/components/app_bar/AppBar.vue, ui/src/errors.js
=> ui: fix order of operations when calling the logout method

api/main.go, api/store/mongo/migrations/migration_1.go, api/store/mongo/migrations/migration_10.go, api/store/mongo/migrations/migration_11.go, api/store/mongo/migrations/migration_12.go, api/store/mongo/migrations/migration_13.go, api/store/mongo/migrations/migration_14.go, api/store/mongo/migrations/migration_15.go, api/store/mongo/migrations/migration_16.go, api/store/mongo/migrations/migration_17.go, api/store/mongo/migrations/migration_18.go, api/store/mongo/migrations/migration_19.go, api/store/mongo/migrations/migration_2.go, api/store/mongo/migrations/migration_20.go, api/store/mongo/migrations/migration_21.go, api/store/mongo/migrations/migration_22.go, api/store/mongo/migrations/migration_3.go, api/store/mongo/migrations/migration_4.go, api/store/mongo/migrations/migration_5.go, api/store/mongo/migrations/migration_6.go, api/store/mongo/migrations/migration_7.go, api/store/mongo/migrations/migration_8.go, api/store/mongo/migrations/migration_9.go
=> api: add messages at each step of the API initialization

api/nsadm/service.go, api/nsadm/service_test.go
This commit apply early-return pattern in namespace
=> api: refactor to use early-return pattern

api/store/mongo/user_store.go, api/store/store.go, cli/error.go, cli/service.go
create errors for duplicated user in store.go
removecheck error from mongo to services on duplicate cases
=> api, cli: fix error returns

cli/service.go
=> cli: fix error display on userCreate

.env, api/Dockerfile, api/entrypoint-dev.sh, api/go.mod, api/go.sum, api/main.go, api/refresh.yml, api/server.go, api/worker.go, docker-compose.yml
The worker runs periodically and will perform some tasks. For now, just a print statement to verify if its running.
=> api: add worker

cli/service.go
=> cli: refactor CreateNamespace

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_23.go, pkg/models/device.go, pkg/models/namespace.go
=> Do not allow dot in namespace and hostname

pkg/dockerutils/utils.go
=> pkg: complement regexp for btrfs mounts

api/store/mongo/migrations/migration_23_test.go
Errorf was printing wrong variable in this error case
this commit fix this issue
=> api: fix print error in migration 23 test

api/go.mod, api/go.sum, api/store/mongo/migrations.go, cli/go.sum
=> api: prevent concurrent migrations running from several instances

agent/sshd/server.go
Authenticate using simple password only when password is provided
=> agent: fix simple password authentication process

cli/main.go
=> cli: fix wrong print on redis error

pkg/api/client/client_internal.go, pkg/models/session.go, ssh/main.go, ssh/options.go, ssh/server.go, ssh/session.go, ssh/ssh2ws.go
=> ssh: refactor the code

pkg/api/client/client_internal.go, ssh/session.go
=> ssh: fix record session

ui/src/components/terminal/TerminalDialog.vue
Updates cols and rows to computed for adapting terminal to container box.
=> ui: fix web terminal dimensions

pkg/models/session.go
=> pkg: remove unused model

.github/workflows/commit.yml, .github/workflows/qa.yml
remove ignore-tags and insert if to skip PRs with Draft label
=> github: fix tag draft to skip ci

.golangci.yaml, api/nsadm/service_test.go, api/sessionmngr/service_test.go
Updates coverage of tests in service to handle error cases
=> api: update service tests to table driven

ui/src/components/app_bar/namespace/NamespaceAdd.vue, ui/src/components/app_bar/namespace/NamespaceDelete.vue, ui/src/components/app_bar/namespace/NamespaceInstructions.vue, ui/src/components/app_bar/namespace/NamespaceNewMember.vue, ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceDelete.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceInstructions.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceNewMember.spec.js
This commit adds more tests to cover cases not previously added.
=> ui: add tests

ui/tests/unit/components/app_bar/AppBar.spec.js
This commit adds more tests to cover cases not previously added.
=> ui: add tests for app bar component

ui/src/components/device/Device.vue, ui/src/components/device/DeviceActionButton.vue, ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceList.vue, ui/src/components/device/DevicePendingList.vue, ui/src/components/device/DeviceRejectedList.vue, ui/src/components/device/DeviceRename.vue, ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/DeviceActionButton.spec.js, ui/tests/unit/components/device/DeviceAdd.spec.js, ui/tests/unit/components/device/DeviceDelete.spec.js, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceIcon.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/DevicePendingList.spec.js, ui/tests/unit/components/device/DeviceRejectedList.spec.js, ui/tests/unit/components/device/DeviceRename.spec.js
This commit adds more tests to cover cases not previously added.
=> ui: add tests for device components

api/deviceadm/service.go, api/nsadm/service.go, api/user/service.go, pkg/validator/validate.go
and rename methods to validateStruct and validateVar
=> pkg, api: add method to validate vars in validator package

ui/.eslintrc.js, ui/src/components/terminal/TerminalDialog.vue, ui/tests/unit/components/terminal/TerminalDialog.spec.js, ui/tests/unit/components/terminal/__snapshots__/TerminalDialog.spec.js.snap
=> ui: refactor UI terminal tests

ui/src/components/snackbar/Snackbar.vue, ui/src/components/snackbar/SnackbarCopy.vue, ui/src/components/snackbar/SnackbarError.vue, ui/tests/unit/components/snackbar/Snackbar.spec.js, ui/tests/unit/components/snackbar/SnackbarCopy.spec.js, ui/tests/unit/components/snackbar/SnackbarError.spec.js, ui/tests/unit/components/snackbar/SnackbarSuccess.spec.js, ui/tests/unit/components/snackbar/__snapshots__/Snackbar.spec.js.snap, ui/tests/unit/components/snackbar/__snapshots__/SnackbarCopy.spec.js.snap, ui/tests/unit/components/snackbar/__snapshots__/SnackbarError.spec.js.snap, ui/tests/unit/components/snackbar/__snapshots__/SnackbarSuccess.spec.js.snap
=> ui: refactor UI snackbar tests

ui/src/components/firewall_rule/FirewallRule.vue, ui/src/components/firewall_rule/FirewallRuleDelete.vue, ui/src/components/firewall_rule/FirewallRuleFormDialog.vue, ui/src/components/firewall_rule/FirewallRuleList.vue, ui/tests/unit/components/firewall_rule/FirewallRule.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
=> ui: refactor UI firewall rules tests

ui/src/components/public_key/KeyDelete.vue, ui/src/components/public_key/KeyFormDialog.vue, ui/src/components/public_key/PublicKey.vue, ui/src/components/public_key/PublicKeyList.vue, ui/tests/unit/components/public_key/KeyDelete.spec.js, ui/tests/unit/components/public_key/KeyFormDialog.spec.js, ui/tests/unit/components/public_key/PublicKey.spec.js, ui/tests/unit/components/public_key/PublicKeyList.spec.js, ui/tests/unit/components/public_key/__snapshots__/KeyDelete.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/PublicKeyList.spec.js.snap
=> ui: refactor UI keys tests

ui/src/components/setting/SettingNamespace.vue, ui/src/components/setting/SettingPrivateKeys.vue, ui/tests/unit/components/setting/SettingNamespace.spec.js, ui/tests/unit/components/setting/SettingPrivateKeys.spec.js, ui/tests/unit/components/setting/SettingProfile.spec.js, ui/tests/unit/components/setting/SettingSecurity.spec.js, ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap, ui/tests/unit/components/setting/__snapshots__/SettingPrivateKeys.spec.js.snap, ui/tests/unit/components/setting/__snapshots__/SettingSecurity.spec.js.snap
=> ui: refactor UI settings tests

ui/tests/unit/components/welcome/Welcome.spec.js, ui/tests/unit/components/welcome/WelcomeFirstScreen.spec.js, ui/tests/unit/components/welcome/WelcomeFourthScreen.spec.js, ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js, ui/tests/unit/components/welcome/WelcomeThirdScreen.spec.js, ui/tests/unit/components/welcome/__snapshots__/WelcomeThirdScreen.spec.js.snap
=> ui: refactor UI welcome tests

ui/src/components/session/Session.vue, ui/src/components/session/SessionClose.vue, ui/src/components/session/SessionDeleteRecord.vue, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionPlay.vue, ui/tests/unit/components/session/Session.spec.js, ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDeleteRecord.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js, ui/tests/unit/components/session/SessionPlay.spec.js, ui/tests/unit/components/session/__snapshots__/Session.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionClose.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDeleteRecord.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
=> ui: refactor UI session tests

ui/src/components/app_bar/namespace/NamespaceAdd.vue, ui/src/components/setting/SettingNamespace.vue, ui/src/errors.js, ui/src/vee-validate.js, ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js, ui/tests/unit/components/setting/SettingNamespace.spec.js, ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
This commit fix the creating a namespace and editing the name. The UI
was not considering the length of the name, which should be between 3
and 30 characters long.
=> ui: fix on when inserting name in namespace

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_27.go, api/store/mongo/migrations/migration_27_test.go, api/store/mongo/session_store.go, pkg/models/session.go, ssh/server.go, ssh/session.go
when a session is created it's inserted on active session and it connection fails, finish it
=> ssh: fix finish session

ui/src/components/app_bar/max_device/MaxDevice.vue, ui/tests/unit/components/app_bar/max_device/MaxDevice.spec.js, ui/tests/unit/components/app_bar/max_device/__snapshots__/MaxDevice.spec.js.snap
=> ui: refactor UI max devices component tests

ui/src/components/app_bar/namespace/NamespaceAdd.vue, ui/src/components/app_bar/namespace/NamespaceDelete.vue, ui/src/components/app_bar/namespace/NamespaceInstructions.vue, ui/src/components/app_bar/namespace/NamespaceMenu.vue, ui/src/components/app_bar/namespace/NamespaceNewMember.vue, ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceDelete.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceInstructions.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js, ui/tests/unit/components/app_bar/namespaces/NamespaceNewMember.spec.js, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceAdd.spec.js.snap, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceDelete.spec.js.snap, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceInstructions.spec.js.snap, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceMenu.spec.js.snap, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceNewMember.spec.js.snap
Within this, some specific points are made:
- NamespaceAdd: the store and dialog validation are added;
- NamespaceDelete: verify the rendering of the delete button and rendering
of the dialog;
- NamespaceInstructions: adds rendering of the open version;
- NamespaceMenu: adds rerun check for some buttons and the open version;
- NamespaceNewMember: adds rendering button.
=> ui: refactor UI namespaces tests

ui/src/components/app_bar/AppBar.vue, ui/tests/unit/components/app_bar/AppBar.spec.js, ui/tests/unit/components/app_bar/__snapshots__/AppBar.spec.js.snap
Test for component rendering verification is added.
=> ui: refactor UI appBar tests

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_28.go, api/store/mongo/migrations/migration_28_test.go, pkg/models/device.go, pkg/models/user.go
=> api: add timestamps for models device and user

ui/src/components/device/DeviceAdd.vue, ui/src/components/device/DeviceDelete.vue, ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/DeviceActionButton.spec.js, ui/tests/unit/components/device/DeviceAdd.spec.js, ui/tests/unit/components/device/DeviceDelete.spec.js, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceIcon.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/DevicePendingList.spec.js, ui/tests/unit/components/device/DeviceRejectedList.spec.js, ui/tests/unit/components/device/DeviceRename.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceAdd.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceDelete.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DevicePendingList.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceRename.spec.js.snap
=> ui: refactor UI devices tests

cli/service.go
=> cli: add a field to store when the user was created

api/services/auth.go, api/services/auth_test.go, api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_29.go, api/store/mongo/migrations/migration_29_test.go, pkg/models/user.go
=> api: add last_login field to users

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_31.go, api/store/mongo/migrations/migration_31_test.go, cli/service.go, cli/service_test.go, pkg/models/namespace.go
=> api: add timestamp for namespace

api/store/mongo/migrations/migration_28_test.go, api/store/mongo/migrations/migration_29_test.go, api/store/mongo/migrations/migration_30_test.go, api/store/mongo/migrations/migration_31_test.go
=> api: migrations tested after migration

cli/service_test.go
=> cli: update tests for table driven model

api/services/auth_test.go, api/services/user_test.go
=> api: update the tests for table drive model

api/store/mongo/device_store.go, pkg/models/device.go
=> api: fix to set create_at on devices only one time

api/store/mongo/user_store.go
=> api: fix to store the last_login on users collection

api/services/sshkeys_test.go
=> api: update the tests on sshkeys for table drive model

agent/Dockerfile, agent/Dockerfile.amd64, agent/Dockerfile.arm32v6, agent/Dockerfile.arm32v7, agent/Dockerfile.arm64v8, agent/Dockerfile.i386, api/Dockerfile, cli/Dockerfile, docker-compose.enterprise.yml, ssh/Dockerfile
This intends to prepare the new baseline for the release. We're moving to the new registry and upgrading the Docker base images.
=> Prepare new baseline

api/routes/device.go, api/services/device.go, api/services/device_test.go, api/services/errors.go
Signed-off-by: Vagner Nornberg <vagner.nornberg@ossystems.com.br>
=> api: fix case error when device is not found

api/store/device_store.go, api/store/mocks/store.go, api/store/mongo/device_store.go, api/store/mongo/store_test.go
Signed-off-by: Vagner Nornberg <vagner.nornberg@ossystems.com.br>
=> api: add store methods to devices

pkg/connman/connman.go, pkg/httptunnel/httptunnel.go, pkg/revdial/revdial.go, ssh/main.go
This also fixes segmentation violation introduced in `57b4887f`.
=> ssh: use existing channel to detect connection failures

.github/dependabot.yml
=> cicd: enable Dependabot Docker backend

ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceList.spec.js
=> ui: fix wrong variable names on tests

ui/package-lock.json, ui/package.json, ui/webpack.config.js
=> ui: remove fabers package

ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceList.vue, ui/src/errors.js, ui/src/store/api/devices.js, ui/src/store/modules/devices.js, ui/src/success.js, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
Signed-off-by: asakiz <juan.rios@ossystems.com.br>
=> ui: add tag system for devices

api/store/mongo/store_test.go, api/store/namespace_store.go
Also add test for the function.
=> api: fix wrong argument name on the function NamespaceGetByName

ui/src/components/setting/SettingTags.vue
=> ui: add tab for rename tag

docker-compose.dev.yml, docker-compose.yml, pkg/api/client/client_internal.go, ssh/server.go, ssh/session.go
An internal route was also added to ensure device server connection
according to billing usage.
Signed-off-by: Vagner Nornberg <vagner.nornberg@ossystems.com.br>
=> ssh, pkg: handle connection block to device

pkg/geoip/geolite2.go
Currently, the Shellhub uses the GeoLite2-City's database from MaxMind to
collection the geolocation from device, but it also needs collect data from
the country whom connect. Unfortunately, GeoLite2-City does not contain
information about country, so download the appropriated database,
GeoLite2-Country, is needed.
This is necessary because the cloud's firewall check if a license is allowed
in that country.
=> pkg: fix GeoIP country getting information

.github/workflows/qa.yml
This commit removes the blank line and indentation the code.
=> cicd: qa: standardize the file

api/services/auth.go
=> api: services: auth: Avoid converting uid to hex multiple times

api/store/mongo/billing_store.go
Signed-off-by: Vagner Nornberg <vagner.nornberg@ossystems.com.br>
=> api: add cache delete to instance update

ui/src/App.vue, ui/src/components/app_bar/AppBar.vue, ui/src/layouts/AppLayout.vue, ui/src/layouts/SimpleLayout.vue, ui/src/store/index.js, ui/src/store/modules/layout.js, ui/src/views/Login.vue, ui/tests/unit/App.spec.js, ui/tests/unit/__snapshots__/App.spec.js.snap, ui/tests/unit/components/app_bar/AppBar.spec.js, ui/tests/unit/layouts/AppLayout.spec.js, ui/tests/unit/layouts/SimpleLayout.spec.js, ui/tests/unit/layouts/__snapshots__/AppLayout.spec.js.snap, ui/tests/unit/layouts/__snapshots__/SimpleLayout.spec.js.snap, ui/tests/unit/store/Layouts.spec.js, ui/tests/unit/views/LoginIsCloud.spec.js, ui/tests/unit/views/LoginIsnotCloud.spec.js
=> ui: uses two layouts

ui/src/layouts/AppLayout.vue, ui/tests/unit/layouts/__snapshots__/AppLayout.spec.js.snap
=> ui: remove code that is not needed

ui/src/views/ValidationAccount.vue
=> ui: redirect to login route after activating account

ui/src/views/Login.vue, ui/tests/unit/views/LoginIsnotCloud.spec.js, ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap, ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
The account is not active for an unknown reason, so a message is displayed when
trying to login.
=> ui: add message when account is not active in enterprise version

ui/src/views/ValidationAccount.vue, ui/tests/unit/views/ValidationAccount.spec.js, ui/tests/unit/views/__snapshots__/ValidationAccount.spec.js.snap
This commit adds two messagens:
- When the request is making;
- When resquest fails.
=> ui: add messages to the user in the account validation screen

ui/src/components/billing/BillingWarning.vue, ui/src/components/device/DeviceChooser.vue, ui/tests/unit/components/billing/BillingWarning.spec.js, ui/tests/unit/components/billing/__snapshots__/BillingWarning.spec.js.snap, ui/tests/unit/components/device/DeviceChooser.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceChooser.spec.js.snap
=> ui: check ownership in userwarning

ui/src/components/billing/BillingWarning.vue, ui/src/store/modules/users.js, ui/src/views/Dashboard.vue, ui/tests/unit/components/billing/BillingWarning.spec.js
=> ui: fix show the update account dialog

ui/src/components/billing/BillingCancel.vue, ui/src/components/setting/SettingBilling.vue, ui/tests/unit/components/billing/BillingCancel.spec.js, ui/tests/unit/components/billing/__snapshots__/BillingCancel.spec.js.snap
=> ui: fix cancel button message

ui/src/authorizer.js, ui/src/components/device/DeviceChooser.vue, ui/tests/unit/components/device/DeviceChooser.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceChooser.spec.js.snap
=> ui: add system permission on device chooser component

gateway/kickstart.sh, gateway/shellhub.conf
=> gateway: add preferred indentity to kickstart

ui/src/components/app_bar/namespace/NamespaceMemberFormDialog.vue, ui/src/components/app_bar/namespace/NamespaceMemberList.vue, ui/src/components/setting/SettingNamespace.vue, ui/src/components/setting/SettingSecurity.vue, ui/tests/unit/components/app_bar/namespaces/NamespaceMemberList.spec.js, ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceMemberList.spec.js.snap, ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
Also updates its call in namespace settings and fix success snackbar to show editing record.
=> ui: create namespace member list component

agent/pkg/osauth/auth.go
fix https://github.com/shellhub-io/shellhub/issues/1511
=> agent: fix panic when hashing algorithm is not supported

ui/src/components/app_bar/namespace/NamespaceMemberList.vue
=> ui: remove own owner actions in namespace list members

ui/src/components/session/SessionClose.vue, ui/src/components/session/SessionDeleteRecord.vue, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/components/session/SessionPlay.vue, ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDeleteRecord.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js, ui/tests/unit/components/session/SessionPlay.spec.js, ui/tests/unit/components/session/__snapshots__/SessionClose.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDeleteRecord.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
=> Change view of actions to use menu template in session list

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceList.vue, ui/src/components/device/DeviceRename.vue, ui/src/components/terminal/TerminalDialog.vue, ui/tests/unit/components/device/DeviceDelete.spec.js, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/DeviceRename.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDelete.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceListChoose.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceRename.spec.js.snap, ui/tests/unit/components/terminal/TerminalDialog.spec.js, ui/tests/unit/components/terminal/__snapshots__/TerminalDialog.spec.js.snap
=> ui: change view of actions to use menu template in device list

ui/src/components/billing/BillingDialogPaymentMethod.vue, ui/tests/unit/components/billing/BillingDialogPaymentMethod.spec.js
Add template render for estimated price function based on current registered
devices in the namespace.
=> ui: add pricing estimation to subscription dialog

ui/src/components/app_bar/namespace/NamespaceDelete.vue, ui/src/components/user/UserWarning.vue
For some use cases the appbar could not be rendered properly
after logging in.
These change add a correction to it.
=> ui: fix appbar layout rendering

ui/src/components/box/BoxMessage.vue, ui/src/components/firewall_rule/FirewallRule.vue, ui/src/components/firewall_rule/FirewallRuleDelete.vue, ui/src/components/firewall_rule/FirewallRuleFormDialog.vue, ui/src/components/firewall_rule/FirewallRuleList.vue, ui/tests/unit/components/box/BoxMessage.spec.js, ui/tests/unit/components/firewall_rule/FirewallRule.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
=> ui: change view of actions to use menu template in firewall list

ui/src/components/box/BoxMessage.vue, ui/src/components/public_key/KeyDelete.vue, ui/src/components/public_key/KeyFormDialog.vue, ui/src/components/public_key/PublicKey.vue, ui/src/components/public_key/PublicKeyList.vue, ui/src/components/setting/SettingPrivateKeys.vue, ui/tests/unit/components/public_key/KeyDelete.spec.js, ui/tests/unit/components/public_key/KeyFormDialog.spec.js, ui/tests/unit/components/public_key/PublicKey.spec.js, ui/tests/unit/components/public_key/__snapshots__/KeyDelete.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap, ui/tests/unit/components/setting/__snapshots__/SettingPrivateKeys.spec.js.snap
=> ui: change view of actions to use menu template in key list

ui/tests/unit/views/Dashboard.spec.js
This commit adds the action mock.
=> ui: fix warnings about ui tests

ui/src/components/session/SessionDeleteRecord.vue, ui/src/components/session/SessionDetails.vue
This confirmation fixes the close and delete session dialogs. Well, the correct
argument was not being passed.
Also removes two IF's that are used in the components, but they are not
necessary and a dead code.
=> ui: fix actions in session details and remove dead code

ui/src/components/device/DeviceActionButton.vue, ui/tests/unit/components/device/__snapshots__/DeviceActionButton.spec.js.snap
=> ui: capitalize the first letter in pending and rejected actions

ui/src/authorizer.js, ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceList.vue, ui/src/components/setting/tag/TagDelete.vue, ui/src/components/setting/tag/TagFormDialog.vue, ui/src/components/setting/tag/TagList.vue, ui/src/views/Settings.vue, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/DeviceListChoose.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceListChoose.spec.js.snap, ui/tests/unit/components/setting/tag/TagDelete.spec.js, ui/tests/unit/components/setting/tag/TagFormDialog.spec.js, ui/tests/unit/components/setting/tag/TagList.spec.js, ui/tests/unit/components/setting/tag/__snapshots__/TagDelete.spec.js.snap, ui/tests/unit/components/setting/tag/__snapshots__/TagFormDialog.spec.js.snap, ui/tests/unit/components/setting/tag/__snapshots__/TagList.spec.js.snap, ui/tests/unit/views/__snapshots__/Settings.spec.js.snap
This commit enables the functionality of tags in the device list and details.
And add the tags menu in the settings.
=> ui: restore tags functionality

ui/src/views/ForgotPassword.vue, ui/src/views/SignUp.vue, ui/src/views/UpdatePassword.vue, ui/src/views/ValidationAccount.vue, ui/tests/unit/views/__snapshots__/ForgotPassword.spec.js.snap, ui/tests/unit/views/__snapshots__/SignUp.spec.js.snap, ui/tests/unit/views/__snapshots__/UpdatePassword.spec.js.snap, ui/tests/unit/views/__snapshots__/ValidationAccount.spec.js.snap
This commit applies in sign up, update password, validation account and forgot
password pages.
=> ui: apply dark mode to pages set to light mode only

ui/src/components/app_bar/AppBar.vue, ui/tests/unit/components/app_bar/__snapshots__/AppBar.spec.js.snap
This commit restores gitter that were removed this commit #1588.
=> ui: restore gitter in appBar

ui/src/views/Login.vue, ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap, ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
This commit applies the larger size to the desktop size.
=> ui: change grid system in login screen

ui/package-lock.json
=> ui: run npm audit fix command

ui/src/components/device/DeviceList.vue, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
This commit returns the title 'tags', applies the outline style and lists
three tags.
=> ui: improvements in the view of tags in the device list

ui/src/components/device/DeviceList.vue, ui/src/components/terminal/TerminalDialog.vue, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap, ui/tests/unit/components/terminal/TerminalDialog.spec.js, ui/tests/unit/components/terminal/__snapshots__/TerminalDialog.spec.js.snap
This commit removes the online icon and replaces it with a connect button. And
remove the connect device item from the action list.
=> ui: add connect device button in device list

ui/src/components/setting/tag/TagSelector.vue, ui/tests/unit/components/setting/tag/TagSelector.spec.js, ui/tests/unit/components/setting/tag/__snapshots__/TagSelector.spec.js.snap
This commit adds the online and right property. And now it's possible to click
on the list item to select. Previously it was only possible to select the item
by clicking on the check box.
=> ui: refactor tag listing button

api/store/billing_store.go, api/store/mocks/store.go, api/store/mongo/billing_store.go, api/store/mongo/billing_store_test.go, pkg/models/billing.go
It returns namespaces with active subscriptions.
=> api: add store method to list active instances

ui/src/components/setting/tag/TagFormUpdate.vue, ui/tests/unit/components/setting/tag/TagFormUpdate.spec.js, ui/tests/unit/components/setting/tag/__snapshots__/TagFormUpdate.spec.js.snap
=> ui: put the tag name in the plural

ui/src/components/session/SessionPlay.vue, ui/src/components/terminal/TerminalDialog.vue
=> ui: remove dark styles that are not needed

ui/src/components/device/DeviceDetails.vue, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
This commit removes the online icon and adds the device connect button.
=> ui: add connect button in device details

ui/src/components/billing/BillingInvoiceList.vue
=> ui: remove filter not using in billing list

ui/src/components/terminal/TerminalDialog.vue
This commit applies the same format as is followed in card title in dialogs.
=> ui: move close icon to end of bar

ui/src/components/namespace/NamespaceMemberDelete.vue, ui/src/components/namespace/NamespaceMemberFormDialog.vue
=> ui: block actions when the role is same

ui/src/components/session/SessionDetails.vue, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
=> ui: show menu in session details when there is recorded session

ui/src/components/filter/date.js, ui/src/components/session/SessionList.vue, ui/tests/unit/components/filter/Date.spec.js, ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap
=> ui: modify time format display in session list

ui/src/components/namespace/Namespace.vue, ui/src/components/namespace/NamespaceList.vue, ui/tests/unit/components/namespaces/NamespaceList.spec.js, ui/tests/unit/components/namespaces/__snapshots__/Namespace.spec.js.snap, ui/tests/unit/components/namespaces/__snapshots__/NamespaceList.spec.js.snap
This commit creates a component to separate the code into another component.
=> ui: create component to list namespaces

ui/src/components/device/DeviceActionButton.vue, ui/src/components/namespace/NamespaceDelete.vue, ui/tests/unit/components/namespaces/NamespaceDelete.spec.js
=> ui: fix console warnings

ui/src/components/namespace/NamespaceMemberDelete.vue, ui/src/components/namespace/NamespaceMemberList.vue, ui/tests/unit/components/namespaces/NamespaceMemberDelete.spec.js, ui/tests/unit/components/namespaces/NamespaceMemberList.spec.js, ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberDelete.spec.js.snap, ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberList.spec.js.snap
the user does not have permission.
=> ui: refator member delete component

ui/src/components/firewall_rule/FirewallRuleFormDialog.vue, ui/src/components/public_key/KeyFormDialog.vue, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
=> ui: change color of buttons on firewall and public when disabled

ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/components/session/SessionPlay.vue, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js, ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
This commit removes the v-if because it's not good programming practice to put
it in the template.
And change tests to uses table drive model.
=> ui: remove v-if in fragment

ui/src/components/box/BoxMessage.vue, ui/src/components/public_key/PublicKey.vue, ui/src/components/public_key/PublicKeyFormDialogAdd.vue, ui/tests/unit/components/public_key/PublicKey.spec.js, ui/tests/unit/components/public_key/PublicKeyFormDialogAdd.spec.js, ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/PublicKeyFormDialogAdd.spec.js.snap
This commit is part of the future refactoring of the public edit. Because in
this other, only the editing part will remain.
=> ui: create component to add public key

ui/src/components/public_key/PublicKeyFormDialogAdd.vue, ui/src/components/public_key/PublicKeyFormDialogEdit.vue, ui/src/components/public_key/PublicKeyList.vue, ui/tests/unit/components/public_key/PublicKeyFormDialogEdit.spec.js, ui/tests/unit/components/public_key/PublicKeyList.spec.js, ui/tests/unit/components/public_key/__snapshots__/PublicKeyFormDialogEdit.spec.js.snap, ui/tests/unit/components/public_key/__snapshots__/PublicKeyList.spec.js.snap
=> ui: create component to edit public key

ui/src/components/firewall_rule/FirewallRuleFormDialogAdd.vue
=> ui: fix variable name used to add the firewall

ui/src/components/public_key/PublicKeyDelete.vue, ui/src/components/public_key/PublicKeyList.vue, ui/tests/unit/components/public_key/PublicKeyDelete.spec.js, ui/tests/unit/components/public_key/PublicKeyList.spec.js, ui/tests/unit/components/public_key/__snapshots__/PublicKeyDelete.spec.js.snap
=> ui: create unique component only for public key deletion

ui/src/components/firewall_rule/FirewallRuleDelete.vue, ui/src/components/firewall_rule/FirewallRuleList.vue, ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
=> ui: refactor the component firewall rule delete

ui/src/components/tag/TagDelete.vue, ui/src/components/tag/TagList.vue, ui/tests/unit/components/tag/TagDelete.spec.js, ui/tests/unit/components/tag/TagList.spec.js, ui/tests/unit/components/tag/__snapshots__/TagDelete.spec.js.snap, ui/tests/unit/components/tag/__snapshots__/TagList.spec.js.snap
=> ui:  refactor the component tag delete

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceList.vue, ui/tests/unit/components/device/DeviceDelete.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDelete.spec.js.snap
=> ui: refactor the component device delete

ui/src/components/device/DeviceDetails.vue, ui/src/components/device/DeviceRename.vue, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceRename.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceRename.spec.js.snap
=> ui: refactor the component device rename

ui/src/components/session/SessionClose.vue, ui/src/components/session/SessionDeleteRecord.vue, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/components/session/SessionPlay.vue, ui/tests/unit/components/session/SessionClose.spec.js, ui/tests/unit/components/session/SessionDeleteRecord.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js, ui/tests/unit/components/session/SessionPlay.spec.js, ui/tests/unit/components/session/__snapshots__/SessionClose.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDeleteRecord.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap, ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
=> ui: refactor the component play session

.github/dependabot.yml
=> github: ignore major update dependency cli-service

ui/src/components/device/DeviceDetails.vue, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
=> ui: fix device delete permission in device details

ui/src/components/device/DeviceDetails.vue, ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
=> ui: fix device rename permission in device details

ui/src/components/public_key/PublicKeyFormDialogAdd.vue
=> ui: standardize dialog size when add public key

api/server.go, api/worker.go, cli/main.go
This would be useful for integration tests environment.
=> Pass database name using Mongo connection string URI

ui/src/components/public_key/PublicKeyFormDialogEdit.vue, ui/src/components/tag/TagSelector.vue, ui/tests/unit/components/public_key/PublicKeyFormDialogEdit.spec.js
- Avoid device state sobreposition in tagselector between lists
- Fill default hostname value of pub key with empty string
=> ui: add small fixes

ui/src/components/namespace/Namespace.vue, ui/tests/unit/components/namespaces/Namespace.spec.js
=> ui: fix namespace auto switch

ui/src/components/firewall_rule/FirewallRule.vue, ui/src/components/firewall_rule/FirewallRuleFormDialogAdd.vue, ui/src/components/firewall_rule/FirewallRuleFormDialogEdit.vue, ui/src/components/firewall_rule/FirewallRuleList.vue, ui/src/store/api/firewall_rules.js, ui/tests/unit/components/firewall_rule/FirewallRule.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogAdd.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogEdit.spec.js, ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap, ui/tests/unit/components/public_key/PublicKey.spec.js
It also improves the description for the rule fields.
=> ui: Adds tag feature to the firewall rules dialog

ui/src/components/namespace/NamespaceRename.vue, ui/tests/unit/components/namespaces/NamespaceRename.spec.js, ui/tests/unit/components/namespaces/__snapshots__/NamespaceRename.spec.js.snap
=> ui: fix empty name in page refresh

api/routes/sshkeys.go, api/store/mongo/publickey_store.go, api/store/mongo/publickey_store_test.go
Co-authored-by: Henry Barreto <henrybarreto@ossystems.com.br>
=> api: fix duplicated fingerprint access

ui/package-lock.json, ui/package.json, ui/src/components/terminal/TerminalDialog.vue, ui/src/helpers/keyauth/ed25519.js
Adds [node-lib](https://github.com/paulmillr/noble-ed25519) to support
key algorithm.
Co-authored-by: Gustavo S. Barreto <gustavosbarreto@ossystems.com.br>
=> ui: add web support to ed25519 public key authentication

.github/workflows/qa.yml
=> cicd: upgrade golangci/golangci-lint-action to v3

Makefile, bin/docker-compose, docker-compose.yml
=> Makefile: rework help to avoid complexity

api/store/mongo/queries/queries.go
Indeed, there are no errors, the existent code works, but the check
could be done in a better way, what I did here.
=> api: fix on query property check

api/server.go
=> api: fix typo in server.go

api/go.mod, api/pkg/gateway/context.go, api/routes/device_test.go, api/routes/errors.go, api/routes/handlers/binder.go, api/routes/handlers/converter/converter.go, api/routes/handlers/error.go, api/routes/handlers/validator.go, api/routes/user.go, api/server.go, api/services/auth.go, api/services/auth_test.go, api/services/mocks/services.go, api/services/user.go, api/services/user_test.go, api/store/mocks/store.go, api/store/mongo/user_store.go, api/store/mongo/user_store_test.go, api/store/user_store.go, pkg/api/request/user.go, pkg/errors/errors.go, pkg/validator/validator.go
This is the first step to apply new models to routes and remove the database models from it. With the new models, we'll preserve information about what has been saved on the database and empower local validation for that new models.
=> api,pkg: add custom validator to echo and change password validation

agent/sshd/cmd_docker.go
=> agent: set working directory in namespace

ssh/main.go, ssh/pkg/flow/flow.go, ssh/pkg/kind/kind.go, ssh/server/handler/password.go, ssh/server/handler/publickey.go, ssh/server/server.go, ssh/session/session.go, ssh/session/websession.go
I've added some comments to improve the readability and remove
error variables, what have not used in more than one place on code.
=> ssh: add comments, nolint rules and rename variable on handlers

ui/src/components/billing/BillingInvoiceList.vue, ui/src/components/filter/currency.js, ui/src/components/setting/SettingBilling.vue, ui/src/helpers/billInfoExtract.js
- changed data received by API in billing routes.
- Changed show currency function
=> ui: show correct currency

ssh/session/session_test.go, ssh/session/websession.go
=> ssh: set $TERM to xterm

api/services/billing.go, api/services/device.go, api/services/mocks/services.go, api/services/namespace.go, api/services/service.go, pkg/requests/helpers.go
We intend to completely remove billing business logic out of API code because it is specific to our cloud SaaS.
=> api: move billing business logic out of services layer

ui/src/vee-validate.js, ui/src/views/SignUp.vue
Added visual validation on `username` field when the user tries to create a new account.
=> ui: added validation in username field on Sign Up.

new-ui/src/api/client/api.ts, new-ui/src/store/api/users.ts, new-ui/src/views/SignUp.vue, new-ui/tests/views/SignUp.spec.ts, new-ui/tests/views/__snapshots__/SignUp.spec.ts.snap
=> new-ui: add marketing field in SignUp page

new-ui/src/components/Announcements/AnnouncementsModal.vue, new-ui/src/components/User/UserWarning.vue
- Added rule to view the announcement once time
- Fix announcement visualization in modal
=> new-ui: rule to show announcement just once time

new-ui/index.html, new-ui/src/layouts/AppLayout.vue, new-ui/src/router/index.ts, new-ui/src/store/modules/devices.ts
- Fix dashboard menu icon
- Redirect to `/` when the router doesn't exists.
- Fix devices list navigation
- Duplicated import in `index.html`
=> new-ui: issues found on 0.11 rc

.github/workflows/build-agent.yml, .github/workflows/dependabot_pr.yml, .github/workflows/dependabot_pr_gomodtidify.yml, .github/workflows/docker-build.yml, .github/workflows/docker-publish.yml, .github/workflows/qa.yml
Following actions has been upgraded:
- actions/checkout: v2 -> v3
- actions/setup-go: v2 -> v3
- actions/cache: v1 -> v3
=> ci: upgrade workflow actions

new-ui/src/components/Devices/DeviceList.vue, new-ui/src/components/PublicKeys/PublicKeysList.vue, new-ui/src/components/firewall/FirewallRuleList.vue
- Align connect device button
- Unnecessary request in `Public Key` and Firewall Rules.
=> new-ui: bugs found in 0.11rc-6

.env, ui/src/components/User/UserWarning.vue
- ui: only show announcements dialog when enabled
- env: disable announcements feature
=> Disable announcements feature

ui/src/components/Setting/SettingBilling.vue, ui/src/components/Setting/SettingOwnerInfo.vue, ui/tests/components/Setting/SettingOwnerInfo.spec.ts
- Remove unuseful request when the user is not the namespace owner
- Fix `SettingOwnerInfo` to show the namespace owner username
- Update `SettingOwnerInfo` test
=> new-ui: setting billing page fixes

agent/main.go
Previously, when running a command on an agent through the server,
the result of the command did not always reach the SSH client.
After investigation, it was suspected that a race condition
due to intermittent results. But we are fixed all the race
conditions found and the issue persisted.
During the debugging sessions, we noticed that some bytes of the
connection between the server and the agent were not arriving
as they should. This led us to believe that someone might be
interfering with the communication by reading the bytes before
us and prematurely closing the socket, as if something
was "hijacking" the socket.
To address this, a hijack was added to the HTTP connection in
reverse listener handler. With this addition, the agent's now
properly handles the connection and prevents any …
=> agent: fix issue with results not always reaching SSH client

ui/src/components/Tags/TagSelector.vue
=> ui: fix `TagSelector` color to primary color #2556

ui/src/components/Devices/DeviceList.vue, ui/src/components/Devices/DeviceListChooser.vue, ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/src/store/modules/devices.ts, ui/tests/store/modules/devices.spec.ts
=> ui: fix device sort by in device listing

ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/tests/components/Device/DevicePendingList.spec.ts, ui/tests/components/Device/DeviceRejectedList.spec.ts, ui/tests/components/Device/__snapshots__/DevicePendingList.spec.ts.snap, ui/tests/components/Device/__snapshots__/DeviceRejectedList.spec.ts.snap
- Add details device link in `DevicePendingList` and `DeviceRejectedList`
- Update unit tests
Device Pending list:
Device Rejected List:
closes #2560
=> ui: add link in hostname to see the device details

ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/tests/components/Device/DevicePendingList.spec.ts, ui/tests/components/Device/DeviceRejectedList.spec.ts
=> ui: fix pending device appearing with useless sshid

ui/src/router/index.ts, ui/vite.config.ts
This Pull Request has changes for the `index.ts` router and `vite.config.ts` for webpack optimization at chunk building. 
This PR closes #2699
Changed Router to build certain manual chunks at needed time.
`Google DevTools` can be a great tool for testing the new response time for loading the screens.
Observe the time response for loading.
=> ui: changed webpackchunk build

agent/server/server.go, ssh/server/handler/ssh.go
- fix(agent): invalid memory nil
- fix(ssh): handle unknown exit errors in exec ssh handler function
=> Improve error handling by properly identifying known and unknown exit errors

api/routes/routes.go, api/server.go
Refactored the server initialization process to facilitate testing.
The changes were made to allow tests to access the instance of
echo to simulate HTTP requests.
=> refactor(api): refactor server initialization

ui/src/App.vue, ui/src/assets/global.css, ui/src/views/ForgotPassword.vue, ui/src/views/Login.vue, ui/src/views/SignUp.vue, ui/src/views/UpdatePassword.vue, ui/src/views/ValidationAccount.vue
The commit adds global CSS styles to the UI, improving the overall
consistency of the application and avoiding duplicated code
The changes include:
* Added global.css file to the assets folder
* Removed the .full-height class from various components
=> feat(ui): add global css style

ui/src/layouts/SimpleLayout.vue, ui/src/views/ForgotPassword.vue, ui/src/views/Login.vue, ui/src/views/SignUp.vue, ui/src/views/UpdatePassword.vue, ui/src/views/ValidationAccount.vue
By moving the common code of auth-related views to a shared layout,
we improve code reusability and maintainability across different pages
=> feat(ui): refactor auth-related pages to use a shared layout

ui/src/router/index.ts, ui/src/views/ConfirmAccount.vue, ui/src/views/Login.vue, ui/src/views/SignUp.vue
This commit adds a new feature that displays a confirmation page when
a user creates an account or tries to log in to an unconfirmed account
=> feat(ui): Add confirmation page for user accounts

ui/src/components/Snackbar/SnackbarNew.vue, ui/src/helpers/snackbar.ts, ui/src/layouts/SimpleLayout.vue, ui/src/main.ts, ui/src/plugins/snackbar.ts, ui/src/store/modules/snackbar.ts, ui/src/views/Login.vue
* Added a new component, SnackbarNew.vue, to handle snackbars
* Created a helper function, useSnackbar, to provide methods for showing messages
* Updated SimpleLayout.vue to include the SnackbarNew component
* Updated main.ts to install the SnackbarPlugin for global snackbar functionality
* Added a new plugin, snackbar.ts, to handle underlying snackbar mutations
* Updated the snackbar module in the store to store snackbar messages and types
* Updated the Login.vue component to use the snackbar helper
Other components will be refactored to use the new snackbar in the future.
Once the components no longer depend on the old snackbar,
the code related to the old snackbar will be removed.
=> feat(ui): add new snackbar component

ui/src/components/Namespace/Namespace.vue, ui/src/components/Namespace/NamespaceAdd.vue
Some improvement:
* Add label to the selected item
* Fixed the margin of Add Namespace button
* Removed duplicated code by eliminating a redundant block
=> feat(ui): improve namespace switcher menu

ui/src/views/Login.vue, ui/tests/views/Login.spec.ts, ui/tests/views/__snapshots__/Login.spec.ts.snap
* Updated the form to display alert message when credentials are incorrect
* Disabled the login button when the form is invalid
=> feat(ui): Login form improvements

ui/src/main.ts
This PR adds a global reloading to main.ts for browsers such as chromium that uses cached requests on back button.
=> fix(ui): added global reloading for caching browsers

.github/workflows/build-agent.yml
Signed-off-by: Victor Hugo Aguiar Pacce <victorhugoaguiarpacce@gmail.com>
=> actions: generate and upload vendored agent tarball

.github/workflows/build-agent.yml
adds missing compression flag to 518eecd4c3f2b3e0b694d094f324824cf6ba8d26
Signed-off-by: Victor Hugo Aguiar Pacce <victorhugoaguiarpacce@gmail.com>
=> actions: generate gzip compressed vendored agent tarball

ui/src/layouts/LoginLayout.vue, ui/src/views/ForgotPassword.vue, ui/src/views/Login.vue, ui/src/views/SignUp.vue, ui/tests/views/__snapshots__/ForgotPassword.spec.ts.snap, ui/tests/views/__snapshots__/Login.spec.ts.snap, ui/tests/views/__snapshots__/SignUp.spec.ts.snap
* Use inner icons instead of outer icons
* Highlighted form action buttons
* Fixed button alignment
=> feat(ui): minor changes in login view

.github/workflows/build-agent.yml
Signed-off-by: Victor Hugo Aguiar Pacce <victor.pacce@ossystems.com.br>
=> actions: build-agent: include agent directory instead of only contents

ui/src/components/NewConnection/NewConnection.vue, ui/src/components/NewConnection/NewConnectionList.vue, ui/src/components/Terminal/TerminalDialog.vue
This refactor addresses several issues by leveraging Vue 3's Composition API, resulting in a cleaner and more efficient codebase. It simplifies the usage of the New Connection feature, removes unused code, and optimizes the overall experience. Key improvements include enhanced code organization for the New Connection functionality.
=> refactor(ui): refactored the new connection tab with vue 3 composition api

pkg/agent/server/modes/host/pty.go, pkg/agent/server/modes/host/sessioner.go, pkg/agent/server/session.go, ssh/server/handler/ssh.go, ssh/session/session.go
=> fix ssh connection when passing -t and -tt flags

pkg/agent/server/modes/host/sessioner.go
=> fix exit status code

ssh/server/handler/ssh.go
sometimes when executing a command, SSH closes the session before writing the command's output to the client's stdout.
=> wait for goroutines to finish before exiting the client

ui/src/views/NotFound.vue
This PR is aimed to solve an router usage on NotFound.vue
which was using it by reference without existing in the component
internal instance imports.
=> fix(ui): fixed router on 404 redirect page

pkg/connman/connman.go, pkg/revdial/revdial.go
This commit replaces the previous manual locking mechanism for managing
dialers with built-in `sync.Map`. This change provides better concurrency
control and performance optimization, especially in scenarios with high
levels of concurrent connections.
* Replace the manual map and lock with `sync.Map` for managing dialers.
* Streamline dialer registration and removal.
* Ensure safer and more efficient concurrent operations on dialers.
=> feat(connman): implement sync.Map for dialers

ssh/server/handler/doc.go, ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/server/handler/util.go
=> improving log system of the handler in the ssh server

ssh/server/handler/doc.go, ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/server/handler/util.go
=> fixed: improving log system of the handler in the ssh server

ssh/server/handler/ssh.go
=> fix(ssh): avoid session record loop when session close

ui/tsconfig.json, ui/vite.config.ts
This Pull Request is aimed to fix to linting on the vite.config and typescript
configuration.
=> fix(ui): fixed linting for UI vite and typescript configuration

ui/vite.config.ts
Added a note to demonstrate explicit the delicacy of the defineModel method
=> chore(ui): added note for experimental defineModel

api/pkg/dbtest/dbserver.go, api/server.go, api/workers/cleaner.go, api/workers/heartbeat.go, api/workers/workers.go
To facilitate debugging and system analysis,
logging was implemented in error cases at the api and pkg shellhub
=> improvement(api): improvement logs to api 

ui/src/components/Setting/SettingProfile.vue, ui/tests/components/Setting/SettingProfile.spec.ts, ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
This Pull Request is aimed to refactor the profile settings to Vue 3 Composition
Api and create unitary tests for it's functions and store methods.
=> refactor(ui): refactored profile settings to vue 3 composition api

gateway/nginx.conf
Add dynamic mapping of HTTP port based on the host header
=> chore(gateway): update nginx.conf

pkg/revdial/revdial.go
Introduce a keep-alive timeout of 35 seconds in the `revdial.Dialer`
to ensure termination when there's no activity.
=> chore(revdial): add keep-alive timeout

pkg/revdial/revdial.go
Refactor `Listener` to ensure proper closure and handling of connections
by implementing a keep-alive timer upon receiving 'keep-alive' messages
from the server.
=> chore(revdial): improve listener termination

ui/src/components/Devices/DeviceList.vue, ui/tests/components/Devices/DeviceList.spec.ts, ui/tests/components/Devices/__snapshots__/DeviceList.spec.ts.snap
This Pull Request is aimed to fix a bug on the device list pagination not maintaining
the filters provided by the search bar, and sending an empty filter on
next or previous page GET request.
=> fix(ui): device list not maintaining search filters on pagination

pkg/dockerutils/utils.go, pkg/dockerutils/utils_test.go
=> fix: container id checking

ui/src/components/AuthMFA/MfaSettings.vue
This Pull Request is aimed to fix an issue where the user couldn't read the
QR Code.
=> fix(ui): added margin to qr-code generator on Multi-Factor Authentication

ui/src/router/index.ts
This Pull Request is aimed to add a guard to whenever the user enters an
URL referred to the Multi-Factor Authentication, without making it's
way through the MFA process, he gets redirected back to login.
=> fix(ui): added router guard to redirect mfa url back to login

ssh/session/session.go
=> fix(ssh): send IP to firewall when ssh wihtout session is requested

ui/src/components/NewConnection/NewConnection.vue, ui/src/components/NewConnection/NewConnectionList.vue, ui/src/store/modules/devices.ts
This Pull Request is aimed to create state on store to be only used for the
New Connection component.
This Pull Request closes #3467 by fixing the current behavior of the component.
=> fix(ui): create store meant to be used only by NewConnection list

bin/add-namespace, bin/add-user, bin/add-user-namespace, bin/cli, bin/del-namespace, bin/del-user, bin/del-user-namespace, bin/docker-compose, bin/reset-user-password, bin/utils
=> fix docker compose binary

ui/src/components/AuthMFA/RecoveryHelper.vue, ui/src/components/User/UserWarning.vue, ui/src/interfaces/INotifications.ts, ui/src/store/modules/auth.ts, ui/tests/components/AuthMFA/RecoveryHelper.spec.ts, ui/tests/components/AuthMFA/__snapshots__/RecoveryHelper.spec.ts.snap, ui/tests/store/modules/auth.spec.ts
This Pull Request is aimed to add a new feature, a new dialog to the recovery
login with multi-factor authentication to when the user logs, redirects
to the disable multi-factor.
=> feat(ui): mfa recovery login redirect to disabling dialog

api/routes/nsadm.go, pkg/api/query/paginator.go, pkg/api/query/paginator_test.go
=> normalize per_page

docker-compose.yml, gateway/Dockerfile, gateway/conf.d/shellhub.conf, ui/Dockerfile
=> Add missing healthcheck entries

.env, docker-compose.yml
Closes https://github.com/shellhub-io/shellhub/issues/3478
=> chore: define env variable to gateway bind address

api/store/mongo/device.go
=> fix device update

cli/README.md
=> correct cli documentation redirect

ui/src/components/Setting/SettingPrivateKeys.vue, ui/tests/components/PrivateKeys/SettingsPrivateKeys.spec.ts, ui/tests/components/PrivateKeys/__snapshots__/SettingsPrivateKeys.spec.ts.snap
This Pull Request adds a alert on the SettingsPrivateKeys with an v-alert
that shows the way ShellHub handles Private Keys.
=> feat(ui): alert for private keys privacy policy

ui/src/components/Terminal/TerminalDialog.vue, ui/tests/components/Devices/DeviceList.spec.ts, ui/tests/components/Terminal/TerminalDialog.spec.ts, ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap
This Pull Request is aimed to add an on Web Socket closing message to warn
the user whenever the connection is ended and refactor the actual handling itself
of the UI component.
This Pull Request closes #3504.
=> refactor(ui): terminal on close handling

ui/src/components/PrivateKeys/PrivateKeyDelete.vue, ui/src/components/PrivateKeys/PrivateKeyEdit.vue, ui/src/components/PrivateKeys/PrivateKeyList.vue, ui/src/interfaces/IPrivateKey.ts, ui/src/store/modules/private_key.ts
This Pull Request is aimed to add an ID attribute for each item on the Private
Key list, so the user will always be more free to add any field of the
individual Private Key.
=> refactor(ui): attribued an unique identifier to Private Keys listing

ui/src/components/PublicKeys/PublicKeyAdd.vue, ui/src/components/PublicKeys/PublicKeyDelete.vue, ui/src/components/PublicKeys/PublicKeyEdit.vue, ui/src/components/PublicKeys/PublicKeysList.vue, ui/src/store/modules/public_keys.ts, ui/tests/components/PublicKeys/PublicKeyAdd.spec.ts, ui/tests/components/PublicKeys/PublicKeyDelete.spec.ts, ui/tests/components/PublicKeys/PublicKeyEdit.spec.ts, ui/tests/components/PublicKeys/PublicKeyList.spec.ts, ui/tests/components/PublicKeys/__snapshots__/PublicKeyAdd.spec.ts.snap, ui/tests/components/PublicKeys/__snapshots__/PublicKeyDelete.spec.ts.snap, ui/tests/components/PublicKeys/__snapshots__/PublicKeyEdit.spec.ts.snap, ui/tests/components/PublicKeys/__snapshots__/PublicKeyList.spec.ts.snap, ui/tests/store/modules/public_keys.spec.ts
This Pull Request is aimed to add Unitary Tests to the interface of
the Public Keys Listing.
=> test(ui): added test cases for public key manager

api/store/mongo/session.go
Previously, sessions were being marked as active upon creation in the `CreateSession` function. However, this approach led to sessions being incorrectly labeled as active even if they were not authenticated. To address this issue, the responsibility for marking a session as active has been moved to ` SessionSetAuthenticated`. This ensures that only authenticated sessions are flagged as active.
=> fix set session as active

ui/tests/components/Devices/__snapshots__/DevicePendingList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DeviceRejectedList.spec.ts.snap
This Pull Request updates two snapshots related to the Device Unitary tests.
=> test(ui): generate device related snapshots

ui/scripts/entrypoint.sh
Update the entrypoint.sh script to use 'exec' for launching
nginx-debug, ensuring proper process handling.
=> chore(ui): update entrypoint.sh

ui/src/components/Setting/SettingOwnerInfo.vue, ui/src/components/Setting/SettingSecurity.vue, ui/src/components/Setting/SettingTags.vue, ui/tests/components/Setting/SettingOwnerInfo.spec.ts, ui/tests/components/Setting/SettingSecurity.spec.ts, ui/tests/components/Setting/SettingTags.spec.ts, ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingOwnerInfo.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingSecurity.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap
This Pull Request is aimed to add new unitary tests to the components related to User Settings.
Added new unitary tests to the components related to User Settings.
Added comprehensive unit tests for the new tests to cover all edge cases. Verified the functionality of the components manually in a development environment.
None.
=> tests(ui): add user settings related unitary tests

ui/src/components/NewConnection/NewConnection.vue, ui/src/components/NewConnection/NewConnectionList.vue, ui/tests/components/NewConnection/NewConnection.spec.ts, ui/tests/components/NewConnection/NewConnectionList.spec.ts, ui/tests/components/NewConnection/__snapshots__/NewConnection.spec.ts.snap, ui/tests/components/NewConnection/__snapshots__/NewConnectionList.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This Pull Request adds integration and rendering tests using vitest for the components related to the New Connection feature. 
The tests ensure that key elements such as the dialog open button and important headers are rendered correctly. 
Additionally, the keyboardMacros function, responsible for toggling the dialog, is tested to ensure it functions as expected.
- Added tests to verify the rendering of key elements in the New Connection dialog.
- Added a test to integration with our Api ensure the keyboardMacros function toggles the dialog value on Ctrl + K keydown.
=> tests(ui): add new connection related tests

ssh/pkg/tunnel/tunnel.go
In versions before 0.15, the agent's authentication may not provide the "X-Tenant-ID" header. This can cause issues with establishing sessions and tracking online devices. To solve this, we retrieve the tenant ID by querying the API.
=> fix(ssh): look for tenant in api when header is empty

api/routes/auth_test.go, pkg/validator/validator.go, pkg/validator/validator_test.go
=> fix(api): allow device with uppercase name

ui/src/components/Namespace/NamespaceAdd.vue, ui/src/components/Namespace/NamespaceInstructions.vue
This Pull Request adds a validation that will block non-cloud ou enterprise users
of adding a new namespace using the ShellHub UI.
=> feat(ui): validate the namespace add modal on community

ui/src/api/client/api.ts, ui/src/components/Namespace/NamespaceApiKeyList.vue, ui/src/components/Namespace/NamespaceDeleteApiKey.vue, ui/src/components/Namespace/NamespaceEditApiKey.vue, ui/src/components/Namespace/NamespaceGenerateApiKey.vue, ui/src/interfaces/IUserLogin.ts, ui/src/store/api/api_keys.ts, ui/src/store/api/auth.ts, ui/src/store/index.ts, ui/src/store/modules/api_keys.ts, ui/src/store/modules/auth.ts, ui/src/store/plugins/api.ts, ui/tests/components/Namespace/NamespaceApiKeyList.spec.ts, ui/tests/components/Namespace/NamespaceDeleteApiKey.spec.ts, ui/tests/components/Namespace/NamespaceEditApiKey.spec.ts, ui/tests/components/Namespace/NamespaceGenerateApiKey.spec.ts, ui/tests/components/Namespace/__snapshots__/NamespaceApiKeyList.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap, ui/tests/store/modules/api_keys.spec.ts, ui/tests/store/modules/auth.spec.ts
This Pull Request adds a role selection to the Api key generate feature, so the user can select what kind of privilege the Api Key will have on the Namespace.
None yet.
None.
=> feat(ui): add role selection to api key generate

api/pkg/gateway/context_test.go, api/pkg/gateway/gateway_test.go
=> tests(api): add tests to api gateway

ui/src/api/client/api.ts, ui/src/components/Setting/SettingProfile.vue, ui/src/interfaces/IUSer.ts, ui/src/store/api/users.ts, ui/tests/components/Setting/SettingProfile.spec.ts
This Pull Request adjusts the Profile Settings to use a new patch endpoint for the user info.
=> fix(ui): adjust new user patch endpoint

ui/src/components/Namespace/NamespaceMemberAdd.vue
This Pull Request fixes an error message which showed the old username input.
=> fix(ui): changed the username error message to a identifier one

ui/src/components/User/PaywallDialog.vue, ui/src/components/User/UserWarning.vue, ui/src/envVariables.ts, ui/src/layouts/AppLayout.vue, ui/src/router/index.ts, ui/src/store/api/users.ts, ui/src/store/modules/users.ts, ui/src/views/FirewallRules.vue, ui/tests/components/Users/PaywallDialog.ts, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This Pull Request adds a premium label to items that are supposed to
be marked as premium and a paywall dialog to block users from
accessing items their plan does not allow them to use.
=> feat(ui): add a premium paywall to ShellHub community edition

api/services/namespace.go, api/services/namespace_test.go, api/store/mongo/migrations/main.go, api/store/mongo/migrations/main_test.go, api/store/mongo/migrations/migration_74.go, api/store/mongo/migrations/migration_74_test.go, cli/services/namespaces.go, cli/services/namespaces_test.go, pkg/models/namespace.go
I am adding a default value as a migration to the announcement if no value is set on the announcement.
=> feat(namespace,api,cli): adding default value to announcement on namespace

ui/src/components/Connector/ConnectorForm.vue, ui/src/components/Connector/ConnectorList.vue, ui/src/components/User/PaywallDialog.vue, ui/src/components/firewall/FirewallRuleAdd.vue, ui/src/envVariables.ts, ui/src/views/Connectors.vue, ui/src/views/FirewallRules.vue
This pull request is aimed to block unused requests and adjust the premium paywall usage throughout the application, now it can be seen on the community tries to use the save firewall rules and add a new connector.
=> fix(ui): increase premium paywall usage through cloud and enterprise features

ui/src/components/Box/BoxMessage.vue, ui/src/components/Containers/ContainerList.vue, ui/src/components/Containers/ContainerPendingList.vue, ui/src/components/Containers/ContainerRejectedList.vue, ui/src/components/Tables/DeviceTable.vue, ui/src/layouts/AppLayout.vue, ui/src/router/index.ts, ui/src/views/Containers.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This pull request aims to adjust the Premium Paywall feature to the env variables that are responsible for the appearance of the connector, firewall rules and premium chip on tabs.
=> fix(ui): adjust paywall usage combined with env variables

ui/src/components/Containers/ContainerList.vue, ui/src/components/Containers/ContainerPendingList.vue, ui/src/components/Containers/ContainerRejectedList.vue, ui/src/components/Devices/DeviceList.vue, ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/src/views/DetailsDevice.vue, ui/tests/components/Tables/DeviceTable.spec.ts
This Pull Request adds the new committable directive that changes the
device store number counting action.
=> fix(ui): new committable directive missing on the device listing

ui/src/components/Sessions/SessionList.vue, ui/src/components/Sessions/SessionPlay.vue
This Pull Request adds the premium paywall whenever the community user tries
to use the play session button.
Solves #4033
=> feat(ui): add premium paywall feature to the session playlist

ui/src/components/Sessions/SessionList.vue, ui/src/components/Sessions/SessionPlay.vue, ui/tests/views/__snapshots__/Sessions.spec.ts.snap
This feature adds new rules to the session list and moves the play button to a better spot.
=> feat(ui): move the session play button to the new session header recorded

api/services/auth.go, api/services/auth_test.go
Users with a pending membership status will now be blocked from authenticating within the namespace. The service `AuthUser` will ignore the namespace, and the `CreateUserToken` will return an error in such cases.
=> feat(api): Block authentication for users with pending membership status

ssh/Dockerfile
This reverts commit f1091da7e745004f7bb1ac78bd208e823e4a3166.
=> Revert "docker: ssh: bump golang in /ssh"

ui/src/layouts/AppLayout.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This Pull Request aims to disable the namespace selector whenever the user
doens't have an namespace.
=> fix(ui): disable namespace select when user has no namespace

ui/src/api/interceptors.ts, ui/src/components/AppBar/AppBar.vue, ui/src/components/AppBar/Notifications/Notification.vue, ui/src/components/AuthMFA/MfaMailRecover.vue, ui/src/components/Devices/DeviceListChooser.vue, ui/src/components/Namespace/NamespaceDelete.vue, ui/src/components/Sessions/SessionList.vue, ui/src/components/Tables/DeviceTable.vue, ui/src/router/index.ts, ui/src/store/helpers/http.ts, ui/src/views/ConfirmAccount.vue, ui/src/views/Containers.vue, ui/src/views/Devices.vue, ui/src/views/ForgotPassword.vue, ui/src/views/MfaResetValidation.vue, ui/src/views/Settings.vue, ui/src/views/SignUp.vue, ui/src/views/UpdatePassword.vue, ui/src/views/ValidationAccount.vue, ui/tests/components/Containers/__snapshots__/ContainerPendingList.spec.ts.snap, ui/tests/components/Containers/__snapshots__/ContainerRejectList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DevicePendingList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DeviceRejectedList.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap, ui/tests/views/UpdatePassword.spec.ts, ui/tests/views/__snapshots__/Settings.spec.ts.snap
This Pull Request adds a new breadcrumb based on the vue-router routes.
It can be used to navigate throughout ShellHub.
=> feat(ui): new breadcrumb router navigation

ui/src/api/interceptors.ts, ui/src/components/Namespace/NamespaceInviteDialog.vue, ui/src/components/User/UserWarning.vue, ui/src/interfaces/INamespace.ts, ui/src/router/index.ts, ui/src/store/api/namespaces.ts, ui/src/store/modules/namespaces.ts, ui/tests/components/AuthMFA/MfaForceRecoveryMail.spec.ts, ui/tests/components/Namespace/NamespaceInviteDialog.spec.ts, ui/tests/components/Namespace/__snapshots__/NamespaceInviteDialog.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This Pull Request adds an interface responsible for handling the new namespace
member invitation feature, adding a new accept dialog.
=> feat(ui): invite namespace member interface

ui/src/components/Terminal/TerminalDialog.vue
Adjusted layout for improved responsiveness, using fullscreen mode for
smaller screens and max-width for larger displays.
=> feat(ui): add persistent hints and placeholders in terminal dialog fields

ui/src/layouts/AppLayout.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
* Refactored the list item structure in AppLayout to use prepend
and append slots.
* Moved the crown icon to the append slot for better alignment.
=> refactor(ui): improve sidebar item list structure

ui/src/components/User/UserWarning.vue, ui/src/views/SignUp.vue
This Pull Request fixes bugs related to the new namespace invite that prevents the recent created user to see
the namespace create instructions.
=> fix(ui): not showing namespace instructions modal

ui/src/components/Namespace/NamespaceGenerateApiKey.vue
This Pull Request changes the never expiration option text typo from expires never
to never expires.
=> fix(ui): change the never expiration api key option text

ui/src/components/Namespace/NamespaceMemberEdit.vue
This Pull Request removes the username field input that isn't used anymore on
namespace member edit.
=> fix(ui): remove username field on namespace member edit

bin/setup, ui/src/api/client/api.ts, ui/src/api/http.ts, ui/src/interfaces/IUSer.ts, ui/src/router/index.ts, ui/src/store/api/users.ts, ui/src/store/modules/users.ts, ui/src/views/Setup.vue, ui/src/views/UpdatePassword.vue, ui/tests/layouts/AppLayout.spec.ts, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap, ui/tests/views/Login.spec.ts, ui/tests/views/Setup.spec.ts, ui/tests/views/__snapshots__/Setup.spec.ts.snap, ui/tests/views/__snapshots__/UpdatePassword.spec.ts.snap
This Pull Request adds the new setup interface for community users, which is
responsible for the setup of the first account on the app.
=> feat(ui): new community setup

ui/src/components/AppBar/AppBar.vue, ui/src/components/Setting/SettingDrawer.vue, ui/src/components/Setting/SettingNamespace.vue, ui/src/components/Setting/SettingPrivateKeys.vue, ui/src/components/Setting/SettingProfile.vue, ui/src/components/Setting/SettingTags.vue, ui/src/layouts/AppLayout.vue, ui/src/views/Settings.vue, ui/tests/components/Setting/SettingDrawer.spec.ts, ui/tests/components/Setting/__snapshots__/SettingDrawer.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingsPrivateKeys.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap, ui/tests/views/Settings.spec.ts, ui/tests/views/__snapshots__/Settings.spec.ts.snap
- Added border to AppBar for improved UI separation
- Removed unnecessary margins in Setting components for cleaner
layout
- Updated AppLayout to dynamically handle navigation drawer
visibility based on screen size
- Refactored Settings view to utilize navigation drawer and
improve responsiveness
=> refactor(ui): adjust settings layout and navigation

ui/src/views/Setup.vue, ui/tests/views/__snapshots__/Setup.spec.ts.snap
This Pull Request fixes found typos in the new setup screen meant for community
new users.
=> fix(ui): typos community setup screen

ui/src/views/Connectors.vue, ui/src/views/Containers.vue, ui/src/views/Devices.vue, ui/tests/views/__snapshots__/Devices.spec.ts.snap
This pull request aims to fix a responsiveness problem in smaller devices
that makes buttons clip into the scroll bar or vanish.
=> fix(ui): responsiveness problem in smaller devices on views titles

ui/src/components/AppBar/AppBar.vue, ui/src/components/AppBar/Notifications/Notification.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
* Replaced default icons with an avatar in the AppBar, loading Gravatar
images based on hashed user email; fallback icon used if loading fails
* Adjusted notification badge and icon layout for improved alignment
and consistency
=> feat(ui): enhance AppBar with gravatar integration and layout adjustments

install.sh
- Introduced a new installation method for WSL, leveraging `systemd`
and `mirrored networking` mode.
- Validates WSL version and ensures necessary prerequisites are met
before proceeding with the installation.
- Adjusted `INSTALL_METHOD` detection to identify WSL environments
and automatically set the installation method to WSL.
- Moved installation messages for each method to the `case` statement
for centralized and consistent output.
=> feat(install): add WSL-specific installation support

ui/src/components/Team/Member/MemberInvite.vue
This PR improves the member invite functionality by introducing conditional UI rendering based on the environment and enhancing error-handling logic for better user feedback.
Conditional Rendering:
The invite instructions are now displayed only when in a cloud environment, determined by envVariables.isCloud.
Enhanced Error Handling:
Added specific error messages for 404 responses in the addMember function, indicating the user does not exist.
Reorganized error handling to ensure consistent behavior and clearer feedback for 409 and other error statuses.
Code Maintenance:
Integrated envVariables into the component to support environment-specific features.
Verify that invite instructions appear only in cloud environments.
Test the invite process and confirm that appropriate error messages are …
=> fix(ui): enhance member invite error handling and conditional UI rendering

gateway/nginx/lua/balancer.lua
* Added logging for DNS resolution results and errors to improve observability.
* Updated `resolve_dns` to handle cache set errors gracefully.
* Replaced custom `schedule` function with `ngx.timer.every` for simplicity.
* Adjusted `init_worker` to use the new timer mechanism directly.
=> refactor(gateway): enhance DNS resolution and worker initialization

ui/src/components/Devices/DeviceAdd.vue
=> feat(ui): include port in server address for install script

ui/src/components/PublicKeys/PublicKeyAdd.vue, ui/src/components/PublicKeys/PublicKeyEdit.vue, ui/src/components/Team/ApiKeys/ApiKeyGenerate.vue, ui/src/components/Team/Member/MemberEdit.vue, ui/src/components/Team/Member/MemberInvite.vue, ui/src/plugins/vuetify.ts, ui/src/views/Login.vue, ui/tests/views/__snapshots__/Login.spec.ts.snap
- **style(ui): set default variant to outlined for buttons and text fields**
=> style(ui): set default variant to outlined for buttons and text fields

ui/src/components/Tunnels/TunnelCreate.vue, ui/src/components/Tunnels/TunnelList.vue
This PR introduces enhancements to the Tunnel UI components and addresses minor issues to improve functionality and consistency.
Changes
TunnelCreate.vue:
Removed the redundant text-grey-lighten-4 CSS class from the paragraph element to simplify styling.
TunnelList.vue:
Added a @click handler for tunnel links. This triggers a refresh of the tunnel list 30 seconds after clicking a link, improving interactivity.
Fixed the date formatting string in the formatDate function by including seconds (h:mm:ss instead of h:mm:s).
New Utility Function:
Introduced handleTunnelLinkClick, which schedules a refresh using getTunnels() after a 30-second delay.
Consistency: The UI text styling has been streamlined for clarity.
Interactivity: Clicking a tunnel link now results in an automatic refresh of the …
=> feat(ui): enhance tunnel creation and list functionalities

ui/src/api/client/api.ts, ui/src/components/Setting/SettingProfile.vue, ui/src/layouts/AppLayout.vue, ui/src/store/api/users.ts, ui/src/store/modules/auth.ts, ui/src/store/modules/users.ts, ui/src/views/Login.vue, ui/tests/components/Setting/SettingProfile.spec.ts, ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap, ui/tests/views/Login.spec.ts, ui/tests/views/__snapshots__/Login.spec.ts.snap
This pull request introduces a new feature that allows users to configure SAML Single Sign-On (SSO) directly from the interface. This enhancement aims to streamline the authentication process for users and improve security by enabling federated identity management.
Features
User Interface: A user-friendly interface has been designed to guide users through the accessing process, including:
Input fields for required SAML parameters
A new button for logging via SSO.
Enhanced Security: By implementing SAML SSO, we reduce the risk of password-related security breaches.
Improved User Experience: Users can log in seamlessly using their existing credentials from the IdP, reducing the need for multiple passwords.
Scalability: This feature supports integration with various IdPs, making it adaptable …
=> feat(ui): implement SAML SSO Configuration for enterprise instance

ui/src/components/Terminal/TerminalDialog.vue
- Made the terminal dialog persistent to prevent unintended closures.
- Added a global "Escape" key listener using `onKeyStroke` from VueUse
to ensure consistent behavior when closing the dialog.
- Improved usability by ensuring users can reliably exit the terminal
without relying solely on UI elements.
=> feat(ui): enhance terminal dialog behavior and accessibility

ui/src/components/AppBar/AppBar.vue, ui/src/main.ts
This Pull Request fixes an issue where the chatwoot module would be created as
an empty instance even when it's not being currently capable of usage by
the conditional rules in main.ts.
=> fix(ui): improve conditional chatwoot usage

pkg/agent/agent.go
```
A MAC address can be empty when the network interface used to 
communicate with the external world isn't a physical one. In this case,
we should be able to define a custom value for MAC's field using the
[PREFERRED_IDENTITY] variable. If the hostname is also empty,
[PREFERRED_HOSTNAME] could be defined to provide a fallback identifier
for the device. This ensures that even if both the MAC address and
hostname is missing, we have a way to identify the device uniquely.
When it occurs, and no variable was defined, the agent should fail to
initialize.
```
=> fix(agent): don't initialize agent when hostname and identity are empty

ui/tests/components/Users/PaywallDialog.spec.ts
This PR fixes the test suite for the `PaywallDialog` component for better async handling.
1. **Stubbing `fetch` globally**: Replaced direct API call mock with a global fetch stub that resolves with the mock data.
2. **Cleanup of mock setup**: Removed unnecessary mock for `axios` and improved mock setup for the relevant APIs, specifically for namespaces and devices.
3. **Async handling improvements**: Replaced `flushPromises()` with `nextTick()` to ensure more reliable handling of Vue's async updates.
4. **Test cleanup**: Removed unused configuration and cleaned up the test logic for better readability and reliability.
- The test suite for `PaywallDialog` should now be more stable with the updated async handling.
- All relevant tests have been updated and pass successfully with the new …
=> fix(ui): stub global fetch, clean up mock setup, and improve async handling

ui/src/store/api/users.ts, ui/src/store/modules/security.ts
This PR performs a simple refactoring in the users API store. It makes two key improvements:
- Fixes parameter formatting by removing excess spaces between parameter names and their type annotations (`(username : string)` → `(username: string)`)
- Renames session recording methods to improve clarity and better reflect their purpose
=> refactor(ui): refactor UsersApi store

ui/src/components/AppBar/Notifications/Notification.vue
This PR adjusts the notification list to ensure all items are vertically aligned for a cleaner appearance. It also increases the spacing between the notifications button and other AppBar buttons, enhancing overall UI/UX.
A deeper refactor of the notifications feature will be addressed in a future PR.
=> fix(ui): fix notification list UI

ui/src/components/Devices/DeviceActionButton.vue
This PR modifies the `acceptDevice` method in `DeviceActionButton.vue` component, calling the snackbar when an error occurs and informing what happened, a behavior that was lacking in the previous implementation.
=> fix(ui): improve error handling on device accept action

ui/src/components/Team/Member/MemberInvite.vue
This PR enhances the team member invitation component by improving the role selection experience and adding conditional UI logic based on environment variables.
Refactored items array from simple strings to objects with value and description fields to provide additional context about each role.
Updated <v-select> to use item and selection slots:
Item slot: shows detailed role descriptions for better user understanding.
Selection slot: displays the selected role's value.
Modified sendEmailInvite to convert the selected role to lowercase before dispatching.
Added conditional rendering for the invitation checkbox to show it only in cloud environments.
Introduced .description-text CSS class to handle line wrapping and layout of role descriptions.
These changes improve the clarity of role …
=> feat(ui): enhance role selection with descriptions

ui/index.html
This Pull Request fixes an issue in production which the UI is built without
a way to call for environment variables.
=> chore(ui): revert calling env.js docker entrypoint

ui/src/components/Terminal/Terminal.vue, ui/src/interfaces/ITerminal.ts, ui/tests/components/Terminal/Terminal.spec.ts
This PR refactors the <Terminal /> Vue component and its associated logic for improved readability, maintainability, and correctness. Key changes include:
- Cleanly separates JSON-based vs. Blob message handling.
- Adds structured support for ErrorMessage with a new MessageKind.Error.
- Introduces a unified message handler for authentication challenges and general errors.
- Clarifies method and variable naming (e.g., getWebTermDimensions → getTerminalDimensions).
- Improves inline documentation and lifecycle organization.
- Updates unit tests for WebSocket event handling and Blob message parsing.
- Adds proper assertions for cleanup behavior (onUnmounted WebSocket close).
- Uses flushPromises to await async WebSocket message resolution.
- Removes unnecessary comments and whitespace for …
=> refactor(ui): terminal blob websocket handling

ui/admin/tests/unit/components/FirewallRules/FirewallRulesList/index.spec.ts, ui/src/components/firewall/FirewallRuleAdd.vue, ui/src/components/firewall/FirewallRuleEdit.vue, ui/src/components/firewall/FirewallRuleList.vue, ui/src/interfaces/IFilter.ts, ui/src/store/api/firewall_rules.ts, ui/tests/components/firewall/FirewallRuleAdd.spec.ts, ui/tests/components/firewall/FirewallRuleEdit.spec.ts, ui/tests/components/firewall/__snapshots__/FirewallRuleAdd.spec.ts.snap, ui/tests/components/firewall/__snapshots__/FirewallRuleList.spec.ts.snap, ui/tests/views/__snapshots__/FirewallRules.spec.ts.snap
This pull request refactors the firewall rule management system, improving type consistency, updating component logic, and enhancing test coverage. These changes improve the maintainability of the `FirewallRuleEdit` and `FirewallRuleAdd` components. 
* Simplified the `FirewallRuleEdit` and `FirewallRuleAdd` components by updating property bindings and conditional rendering logic, giving better names for the refs, and improving type safety
* Updated test cases to reflect changes in component logic and type definitions
* Updated snapshot tests to reflect changes in button labels and dialog accessibility attributes
These changes collectively improve the maintainability, consistency, and usability of the firewall rule add and edit systems.
=> refactor(ui): refactor firewall rule add and edit dialogs

ui/src/components/WebEndpoints/WebEndpointCreate.vue, ui/src/components/WebEndpoints/WebEndpointList.vue, ui/src/views/WebEndpoints.vue, ui/tests/components/WebEndpoints/WebEndpointCreate.spec.ts
This pull request addresses multiple questions in the new Web Endpoints feature:
- Changes the address field label to host in `WebEndpointCreate` 
- Ensures the list updates after creation by using async/await in the fetch request
- Show AM/PM indicator in the web endpoint's expiry date
=> fix(ui): fix Web Endpoints list and creation

ui/admin/src/layouts/AppLayout.vue, ui/admin/src/views/Dashboard.vue, ui/admin/tests/unit/views/Dashboard/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/views/Dashboard/index.spec.ts, ui/src/components/Sessions/SessionList.vue, ui/src/layouts/AppLayout.vue, ui/src/views/Devices.vue, ui/src/views/Home.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap, ui/tests/views/__snapshots__/Devices.spec.ts.snap, ui/tests/views/__snapshots__/Home.spec.ts.snap, ui/tests/views/__snapshots__/Sessions.spec.ts.snap
- **feat(ui): add device button to session list**
- **feat(ui): replace device icons with mdi-developer-board**
=> feat: update device icons

ui/src/components/Terminal/TerminalDialog.vue, ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap
This pull request fixes a rendering issue in the Terminal dialog introduced by recent `BaseDialog.vue` changes. When the base dialog was updated to include a <v-card> wrapper, it created nested card elements in the Terminal dialog (which already contained its own card). This nesting prevented the terminal interface from rendering after connection. The fix removes the redundant card wrapper from the Terminal dialog component.
=> fix(ui): fix Terminal Dialog

ui/src/components/Devices/DeviceRename.vue, ui/src/components/Team/ApiKeys/ApiKeyEdit.vue, ui/src/components/Team/ApiKeys/ApiKeyGenerate.vue, ui/src/components/Team/ApiKeys/ApiKeySuccess.vue, ui/src/interfaces/IApiKey.ts, ui/tests/components/Devices/DeviceRename.spec.ts, ui/tests/components/Team/ApiKeys/ApiKeyEdit.spec.ts, ui/tests/components/Team/ApiKeys/ApiKeyGenerate.spec.ts, ui/tests/components/Team/ApiKeys/ApiKeyList.spec.ts, ui/tests/components/Team/ApiKeys/ApiKeySuccess.spec.ts, ui/tests/views/TeamApiKeys.spec.ts, ui/tests/views/__snapshots__/TeamApiKeys.spec.ts.snap
This pull request fixes build errors caused by recent changes in the dialog system in the main UI. Some TypeScript errors were left unresolved, causing the build process to break. This PR fixes this by improving typing, exposing component internals needed in tests, and re-adding API mocks where necessary.
=> fix(ui): fix dialog-related build errors

.github/workflows/qa.yml
This pull request adds a GitHub Action that runs `npm run build` in PRs that modify the application's UI.
=> chore(ci): add Build action for UI

ui/package-lock.json, ui/package.json, ui/src/components/Team/Member/MemberDelete.vue, ui/src/components/Team/Member/MemberEdit.vue, ui/src/components/Team/Member/MemberInvite.vue, ui/src/components/Team/RoleSelect.vue, ui/tests/components/Team/Member/MemberDelete.spec.ts, ui/tests/components/Team/Member/MemberEdit.spec.ts, ui/tests/components/Team/Member/MemberInvite.spec.ts, ui/tests/components/Team/Member/__snapshots__/MemberDelete.spec.ts.snap, ui/tests/components/Team/Member/__snapshots__/MemberEdit.spec.ts.snap, ui/tests/components/Team/Member/__snapshots__/MemberInvite.spec.ts.snap, ui/tests/components/Team/RoleSelect/__snapshots__/RoleSelect.spec.ts.snap, ui/tests/views/__snapshots__/TeamMembers.spec.ts.snap
This pull request refactors the member management dialogs in the UI to use new, more specialized dialog components (`FormDialog` and `MessageDialog`) instead of the generic `BaseDialog`. The related tests have been updated for snapshot-based dialog validation. 
* Replaced `BaseDialog` with `MessageDialog` in `MemberDelete.vue`, `FormDialog` in `MemberEdit.vue` and `MemberInvite.vue`, streamlining dialog code and improving maintainability. 
* Removed the unused `@multiavatar/multiavatar` package and related avatar generation logic from `MemberInvite.vue`, as well as corresponding CSS for avatar positioning. 
* Updated `RoleSelect.vue` to hide details for a cleaner UI in role selection.
* Modified member dialog component tests (`MemberDelete.spec.ts`, `MemberEdit.spec.ts`, …
=> refactor(ui): migrate Members components to new dialog system

ui/src/components/Connector/ConnectorDelete.vue, ui/src/components/Connector/ConnectorForm.vue, ui/tests/components/Connectors/ConnectorDelete.spec.ts, ui/tests/components/Connectors/ConnectorForm.spec.ts, ui/tests/components/Connectors/__snapshots__/ConnectorDelete.spec.ts.snap, ui/tests/components/Connectors/__snapshots__/ConnectorForm.spec.ts.snap
This pull request refactors the Connector components to adapt them to the new dialogs. The tests were also updated to reflect the changes in the components.
- `ConnectorDelete` → `MessageDialog`
- `ConnectorForm` → `FormDialog`
=> refactor(ui): migrate Connectors components to new dialog system

ui/src/components/AppBar/AppBar.vue, ui/src/layouts/AppLayout.vue, ui/tests/components/AppBar/__snapshots__/AppBar.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
- Update AppBar background to use bg-v-theme-surface for consistency
- Simplify logo layout in AppLayout with proper centering
=> refactor(ui): improve AppBar and AppLayout styling

ui/src/components/QuickConnection/QuickConnection.vue, ui/src/components/QuickConnection/QuickConnectionList.vue, ui/tests/components/QuickConnection/__snapshots__/QuickConnectionList.spec.ts.snap
This pull request migrates the quick connection dialog to `WindowDialog`, also improving its UI/UX, utilizing new standard layout styles, and updating related tests.
=> refactor(ui): migrate `QuickConnection` to `WindowDialog`

ui/src/components/FormDialog.vue, ui/tests/components/Connectors/__snapshots__/ConnectorForm.spec.ts.snap, ui/tests/components/Namespace/__snapshots__/NamespaceEdit.spec.ts.snap, ui/tests/components/Team/Member/__snapshots__/MemberEdit.spec.ts.snap, ui/tests/components/Team/Member/__snapshots__/MemberInvite.spec.ts.snap, ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap, ui/tests/components/Terminal/__snapshots__/TerminalLoginForm.spec.ts.snap
This pull request adds a `v-form` to `FormDialog`'s content slot, improving the template's semantics and form-related features in the browser, like autocomplete.
=> fix(ui): add `v-form` to `FormDialog`

ui/tests/layouts/AppLayout.spec.ts
This pull request adds a stub to `AppLayout` tests to prevent intermittent errors in the test console.
=> fix(ui): stub premium content cards request in `AppLayout`
