agent/Dockerfile, agent/Dockerfile.amd64, agent/Dockerfile.arm32v6, agent/Dockerfile.arm64v8, api/Dockerfile, ssh/Dockerfile, ui/Dockerfile, ws/Dockerfile
- Use `COPY` rather than `ADD` for cache strategy(ADD never generates cache)
- Use Node.js 12(and newer than 12.15 for important CVE fix) as it is the current LTS version
=> Refactor Dockerfiles

api/main.go, gateway/nginx.conf, gateway/shellhub.conf, ssh/go.mod, ssh/main.go, ssh/session.go, ssh/ssh2ws.go
Fix ssh2ws to get client's IP behind a layer7 load balancer by moving the ssh2ws bridge to ssh service, where connections are established to localhost. It's allow us to trust in the `IP_ADDRESS` session environment variables set by our internal ssh client. This variable contains the real IP address from the client's browser which original connection came from.
=> ssh: fix ssh2ws to get client's IP behind a layer7 lb

api/pkg/store/mongo/store.go
After iterating over the mongodb cursor the variable declared outside
for loop scope point to last iteration value causing all elements to
be the same in list.
=> api: decode cursor into local scoped var instead of outside scoped

agent/Dockerfile, agent/cmd_docker.go, docker-compose.dev.yml, gateway/shellhub.conf
Init supplementary groups by wrapping around 'nsenter' using 'setpriv' utility for changing user's shell process privileges. Fixes #96
=> agent: init supplementary groups

api/pkg/services/deviceadm/service.go
Restoring getDeviceByName  function to avoid renaming a device
to an already taken name.
Fixes: d44e0c884dfb39e7209252623bbd99fb0e94c447
=> api: avoid devices with same name

api/pkg/services/deviceadm/service.go, api/pkg/services/sessionmngr/service.go, api/pkg/store/mongo/store.go, api/pkg/store/store.go
2 fixes
the aggregateCount only needs "count" field to return the number of elements.
commit  71cd3441fc526f9dca4bf543536d2adc845d8b1e fixes the query
the linter changes the GetDeviceByUid to GetDeviceByUID 
in some parts of the code. 
commit b7bb36c5178132953f70d92577f63c45a2ae2339 fixes all the calls
=> api: fix issues with counting and delete devices

ui/src/components/session/SessionList.vue
The variables that used it once were moved to inside object,
and removed global variable.
=> ui: refatory sessions on pagination

ui/src/components/device/DeviceList.vue
It's removing the unsed code and add code to list hostname.
Centralizing two itens, hostname and Operating System.
=> ui: rename name to hostname, removing unused code and blank line

ui/src/router/index.js, ui/src/views/Dashboard.vue
A treatment for not found URLs was defined
by redirecting to homepage and displaying
a warning vuetify alert.
=> ui: Redirection to dashboard with alert when non-existing route gets acessed

.github/workflows/commit.yml
We reworked cicd workflow, especially the commit message one, to allow the use of numbers, spaces, and comma for commit scope as this happens often.
Another change was as a consequence of most PR being marked as failing, while this was not really the case. To fix, we restrict the workflow to the 'push' event only.
=> Minor fixes for cicd workflow

agent/agent.go
The private key process now prints a log information when starting its
generation and when it is complete.
Refs: #184.
=> agent: Improve logging when generating the private key

ui/src/components/session/SessionClose.vue, ui/src/components/session/SessionList.vue
This remove confirm dialog, because the project used the convention to use
components in actions.
=> ui: create component to close session

ui/src/components/device/DeviceDelete.vue, ui/src/components/device/DeviceList.vue, ui/src/components/session/SessionClose.vue, ui/src/components/session/SessionList.vue, ui/src/modules/devices.js
The lists of sessions and devices are now automatically
updated through an event handler, without the need to refresh page
to see them.
This closes #189 and closes #190.
=> ui: Update lists in pagination

api/main.go, api/pkg/services/firewall/service.go, api/pkg/store/mongo/store.go, api/pkg/store/store.go, pkg/models/firewall.go, ssh/go.mod, ssh/go.sum, ssh/session.go
This commits implements a flexible firewall for filtering SSH connections.
It gives a fine-grained control over which SSH connections reach the devices.
The firewall rules can deny/allow SSH connections from specific IP address
to a specific or a group of devices using a given username.
Each firewall rule has a priority number which is evaluated in ascending order
(starting with the lowest). It's makes a lot easier to manage a large number
of firewall rules.
=> api: firewall rules

ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
The user edits the rule, but does not save changes and closes the dialog.
When you open the dialog box again, the values ​​are the same as the change and
are not this data is saved in the list. Resolves this issue.
=> ui: fix problem when user edit fields in firewallrules

api/store/mongo/store.go
Fix an incorrect call of TenantFromContext function that was resulting
in no devices and sessions correct filtering on mongo operations
=> api: fix TenantFromContext bug

ui/src/components/device/DeviceAdd.vue
Check the port on which the server is running Shellhub and set the port on the
command when the server is running on a different port 80(HTTP) and 443(HTTPS).
This closes #222.
=> ui: Add port number to device registration command

api/deviceadm/service_test.go, api/sessionmngr/service.go, api/sessionmngr/service_test.go
This has no semantic changes. All trivial lints fixes.
=> api, ssh: Fix 'revive' warnings on new code of 0.4.0

ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
Fixes the creation of a new firewall rule
to active state.
This closes #235.
=> ui: Set default state to firewall rule active

agent/selfupdater/updater_docker.go
WithAPIVersionNegotiation makes the Docker client negotiate down to a lower
version if Docker's current API version is newer than the server version.
=> agent: Use NegotiateAPIVersion for docker client

agent/main.go, agent/sshd/sshserver.go, gateway/install.sh, gateway/shellhub.conf
To set a custom keepalive interval just append `keepalive_interval` param (value in seconds) to the install script, e.g.
`http://localhost/install.sh?tenant_id=xxx-xxxx....&keepalive_interval=60`
This closes #215
=> Custom keepalive interval

.github/workflows/build-agent.yml
We need to use adjust the variant for Docker manifest proper use. This
can be seen at:
https://github.com/moby/moby/issues/34875#issuecomment-602140402
=> cicd: build-agent: Fix Docker manifest variant for ARMv6

ui/src/components/snackbar/Snackbar.vue, ui/src/components/snackbar/SnackbarError.vue, ui/src/components/snackbar/SnackbarSuccess.vue
If not send type message in props, the component has default type.
However, you can send the type message and register new message
in components.
=> ui: Add possibility to register messages specific in snackbar

ui/src/store/helpers/http.js
This resolve problem when token expired and not redirect to login in
first moment. Use the await in router, because without watch the
redundancy redirect with login.
=> ui: Fix the problem with token expiration

ui/src/components/session/SessionList.vue, ui/src/components/session/SessionPlay.vue, ui/tests/unit/components/session/SessionPlay.spec.js
This modification is better in another way, because when using the
sessionPlay component it's not necessary to put the if in the
instance.
=> ui: Move v-if hidden in the call component to internal component

agent/sshd/pty.go
`Ctty` in `SysProcAttr` should be set to a fd in a child process, but we were setting it to a fd in the parent process.
This was working by accident, but now a panic is raised by `os/exec`.
See: https://github.com/golang/go/issues/29458
=> agent: Don't set ctty fd

agent/main.go
This alsos move log entry to a location where connection is fully established.
See @sixhills comment:
https://github.com/shellhub-io/shellhub/issues/347#issuecomment-683457357
=> agent: fix 'index out of range' error in logging

docker-compose.autossl.yml, docker-compose.dev.yml
Also set a nop image for autossl service in development environment when autossl is disabled
=> docker-compose: rename nginx service to autossl

ui/src/App.vue, ui/src/components/device/Device.vue, ui/src/components/device/DeviceAdd.vue, ui/src/components/device/DeviceList.vue, ui/src/components/device/DevicePendingList.vue, ui/src/components/device/DeviceRejectedList.vue, ui/src/components/session/SessionDetails.vue, ui/src/components/session/SessionList.vue, ui/src/components/setting/SettingProfile.vue, ui/src/components/snackbar/Snackbar.vue, ui/src/components/snackbar/SnackbarCopy.vue, ui/src/components/terminal/TerminalDialog.vue, ui/src/components/welcome/Welcome.vue, ui/src/components/welcome/WelcomeSecondScreen.vue, ui/src/copy.js, ui/src/main.js, ui/src/store/modules/modals.js, ui/src/views/Settings.vue
This modification improves the use of the snackbarCopy, as it is
declared globally and use of it is done by vuex. And remove unused
variable in DeviceRejectedList component.
=> ui: Move snackbarCopy to global and refactor where it is call in code

api/store/mongo/store.go
this fix avoid GetStats from count the removed device as an online device
=> api: delete device from connected_device on removeDevice

ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
Form errors in firewall rules are now reseted when closing the dialog.
=> ui: reset validation firewall dialog

ui/src/components/device/DeviceList.vue, ui/src/components/device/DevicePendingList.vue, ui/src/components/device/DeviceRejectedList.vue, ui/src/store/modules/devices.js
Fix problem show the store's content list device not related to your
tab in the data loading interval of the other tab. Happens when the
user switches between list, pending and rejected devices.
=> ui: Add mounted in device to clear devices from list

ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/DeviceAdd.spec.js, ui/tests/unit/components/device/DeviceDelete.spec.js, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/device/DeviceRename.spec.js
Standardizes tests in the device directory, separating them into
sets. And use forEach to verify the object in device details.
This closes #414, and closes #418.
=> ui: Standardize the tests in the device directory

ui/tests/unit/components/device/DeviceDelete.spec.js
Verify the props, and default. Add another's actions use on the component.
This closes #427, and closes #428.
=> ui: Update test on the deviceDelete component, verify props and data

ui/tests/unit/components/device/DeviceRename.spec.js
Verify the variables and add another's actions use on the component.
And add a blank line to separate the wrapper from using variables.
This closes #423.
=> ui: Update unit test in deviceRenama component, verify the variables

.github/workflows/commit.yml
When checkAllCommitMessages is true, the use github access token is
required.
=> cicd: commit: Fix rework validations

ui/src/store/modules/firewall_rules.js, ui/src/store/modules/sessions.js, ui/tests/unit/store/Devices.spec.js, ui/tests/unit/store/Firewalls.spec.js, ui/tests/unit/store/Sessions.spec.js, ui/tests/unit/store/Stats.spec.js
New store tests were added verifying state changes for mutations
in devices, sessions, stats and firewalls. A few changes in store
were implemented as well.
This closes #457.
=> ui: update store tests

pkg/models/device.go
this issue was resulting in wrong uid calculations, generating duplicate devices
=> models: fix tag in DeviceAuth

api/store/mocks/store.go, api/store/mongo/store.go, api/store/mongo/store_test.go, api/store/store.go
This method will be used by our user Cloud SaaS backend to handle user registration requests. If you intend to implement your own backend service this method could be useful.
=> api: add CreateUser to store

pkg/api/client/client_public.go
This fix cover all cases (secure and insecure) servers.
http becomes ws and https becomes wss
=> pkg: fix websocket url

agent/go.mod, agent/selfupdater/updater_docker.go, agent/sshd/server.go, agent/sshd/utmp.go, gateway/kickstart.sh
This change implements recording of login activity to the utmp
and wtmp databases so that sessions are reported by standard
utilities such as "who", "last", "w" and "users".
This revised PR removes the dependency on glibc, so that the
code works when the Agent is run in an Alpine docker
environment as well as when it's run natively.
Comments and feedback on the code is very welcome as I'm
new to Go programming.
Fixes https://github.com/shellhub-io/shellhub/issues/317
=> agent: Add utmp and wtmp recording of pty sessions (Revised)

.env, bin/docker-compose, docker-compose.autossl.yml, docker-compose.httptohttps.yml, docker-compose.nossl.yml, docker-compose.yml
New options:
> The HTTPS listen port
`SHELLHUB_HTTPS_PORT`
> Redirect requests from HTTP port to HTTPS port
`SHELLHUB_REDIRECT_TO_HTTPS`
This also fixes #619
=> Rework docker-compose wrapper to support new options related to HTTPS

ui/src/components/terminal/TerminalDialog.vue
This fixes temporarily dialog close when form data is entered incorrectly.
While ws doesn't handle specific cases, the exit command can't be managed.
=> ui: remove exit case in onclose event in terminal dialog

.env, docker-compose.autossl.yml
Set the same network for autossl and gateway services to allow communication with each other
=> Set the same network for autossl and gateway services

agent/go.mod, agent/go.sum, agent/pkg/osauth/auth.go, agent/pkg/osauth/user.go, agent/sshd/cmd.go, agent/sshd/cmd_docker.go, agent/sshd/server.go
Closes #596 
CGO is really not necessary for the simple file parsing
github.com/GehirnInc/crypt can provide the needed crypto functions
Removing the CGO dependency for the agent makes cross compilation much easier, and can enable easier workflows when the agent is not running inside of docker
Currently I have left a big comment that parses additional parts of /etc/shadow
In my opinion it is unnecessary, but it would make sense to be in there for completeness or later use... So please let me know
Also my change to the User type, changing UID and GUID to ints is not strictly necessary and therefore up for discussion
I did test the new implementation on a Pi running RaspberryPiOS lite and it works fine
Let me know what you think =D
=> Remove CGO dependency in agent

Makefile
The usage of `docker-compose` wrapper for end-users will be
discontinued in favor of Makefile-based tasks to avoid confusion
with docker-compose binary in the $PATH.
Currently, following commands are supported:
```
build               Build all services
start               Start services
stop                Stop services
```
`make help` for a complete list
=> makefile: add tasks for managing a self-hosted instance

Makefile, bin/docker-compose, docker-compose.yml
With the EOL MongoDB 3.4-series we need to upgrade to 4.2-series.
This commit upgrade from 3.4-series to 4.2.12, which is the latest stable version of 4.2-series keeping existing databases without user intervention.
=> docker: upgrade mongodb version from 3.4-series to 4.2-series

pkg/api/client/client_public.go
This commit fixes #689
When changing the value of SHELLHUB_HTTP_PORT to anything else than 80
the ssh service cannot connect to reverse tunnel because the agent
try to dial to standard http port (80) instead of specified in
SERVER_ADDRESS env.
=> pkg: fix tunnelDial func to dial host:port

api/nsadm/service.go, api/store/mongo/migrations.go
This fixes #700
Also add a migration to convert existing namespace to lowercase
=> api: convert namespace to lower-case before inserting into db

api/Dockerfile, devscripts/README.md, devscripts/gen-mock
The `gen-mock` script is used to generate/update mock objects for unit testing go code.
=> devscripts: add gen-mock script

api/store/mongo/store.go
The `count` return parameter was miscalculated from total of items in
the paginated results.
This commit fixes the `count` return parameter to return the total
of users filtered (or not) by the filter query.
=> api: fix return parameter from ListUsers func

Makefile
When running 'make start' for the first time there is no mongo container running, so upgrading is not required.
=> makefile: exit when there is no mongo container

gateway/shellhub.conf
If a nonstandard port is used for HTTP, it is included in ngx.var.http_host. Thus, when ":<ssh_port>" is appended, the result is that there are two port numbers appended to the value of the ssh endpoint in the /info api.  The solution is to use ngx.var.host rather than ngx.var.http_host for this case.
=> fix /info to omit http host port from ssh host name

docker-compose.dev.yml
docker-compose.dev.yml starts an extra container in which a dev/test instance of the agent is run with
SHELLHUB_TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.  This container runs in the host network and pid
namespace, which is necessary so that it can launch SSHD child shells on behalf of the host.
However, The host network environment varies from host to host and depending on docker bridge configuration.
The docker-compose file had hardcoded the address of the gateway from the host's network as http://172.17.0.1,
with an implicit gateway port of 80.  This will not work on hosts with different bridge configuration or
when SHELLHUB_HTTP_PORT is not 80.
Since the dev agent is on the host network, localhost works to refer to a gateway running on the same host as
the dev agent.  So the …
=> agent: docker-compose.dev.yml started agent container with hard-coded SHELLHUB_SERVER_ADDRESS

agent/selfupdater/updater_docker.go, agent/sshd/utmp.go, api/authsvc/service_test.go, api/deviceadm/service_test.go, api/pkg/dbtest/dbserver.go, api/routes/session.go, api/routes/sshkeys.go, api/routes/user.go, api/sessionmngr/service_test.go, api/store/mongo/migrations.go, api/store/mongo/store.go, api/store/mongo/store_test.go
I am fixing the easy lint errors, which can be found by `golangci-lint` prior add it to CI. It'll probably be multiple PRs to clean it all as there are many issues, and I don't want to hold it for too long to avoid conflicts.
=> Fix as many lints as possible

gateway/kickstart.sh, ui/src/components/device/DeviceAdd.vue, ui/src/components/welcome/Welcome.vue, ui/tests/unit/components/device/DeviceAdd.spec.js, ui/tests/unit/components/welcome/Welcome.spec.js, ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js
The installation script, using the `sh <(curl ...)` does not work on
Busybox shell. This has been detected in newer Torizon operating system.
We are now using:
```sh
curl -sSf ... | sh
```
This is the same format used in `htts://rustup.rs` to install the Rust
compiler and has been in use for quite some time by them.
This partially revert the change in #638, however, the commit log and
issue didn't provide enough information to reproduce the original issue
so in case it breaks something we'll need to find a testing case for it.
Reported-by: Guilherme Fernandes <guilherme.fernandes@toradex.com>
=> Avoid using `sh <(curl ...)` syntax as it does not work in Busybox

agent/sshd/utmp.go, agent/sshd/utmp_timeval_time32.go, agent/sshd/utmp_timeval_time64.go
This change fixes the incorrect formatting of utmp records on some
64-bit systems.
The change writes correct utmp records on:
32-bit systems where session and time fields in utmp records are 32-bits
64-bit systems where session and time fields in utmp records are 32-bits
64-bit systems where session and time fields in utmp records are 64-bits
The only known case where a 64-bit system writes 64-bit session and time
fields is arm64/aarch64 architecture in, for example, Raspberry Pi
64-bit operating systems.
This change has been tested on:
Debian 10.8.0 32-bit
Debian 10.8.0 64-bit
Fedora 33 64-bit
Gentoo R-Pi 64-bit
OpenSUSE Leap 15.2 64-bit
R-Pi OS Latest 32-bit
R-Pi OS Latest 64-bit
Ubuntu 20.4 x86 LTS 64-bit
Ubuntu 20.10 x86 64-bit
Ubuntu 20.10 R-Pi 32-bit
Ubuntu 20.10 R-Pi 64-bit
Fixes …
=> agent: Fixes utmp/wtmp recording on 64-bit systems

gateway/shellhub.conf
Use X-Forwarded-Host header (if present) to determine which host
to use for URL generation. This may be used where a L7 reverse
proxy is in-front of ShellHub gateway service.
=> gateway: Fix /info to use X-Forwarded-Host to generate URLs

api/store/mongo/store.go
This fixes a issue when renaming an account username.
After renaming username the auth token remains with old username
which causes all subsequent requests to fail.
=> store: get user from context by id instead of username

api/authsvc/service.go, api/routes/auth.go
The store.ListNamespaces function uses the ID from context to build
the scoped query to list all namespaces. When the ID is missing all
namespaces is returned.
This commit fixes the issue when listing namespaces which not belongs
to issued token owner.
=> api: generate jwt token with user id data

bin/add-namespace
Since the binary on /bin don't need to check anymore for some
missing library, this part of the code is not necessary.
=> cli: remove unnecessary code

ui/package-lock.json, ui/package.json
This commit set the version less than 11, because the sass loader
version 11 ou higher, doesn't work with vue 2.6.12.
=> ui: Set sass loader version less than 11

api/nsadm/service.go, api/nsadm/service_test.go, api/routes/nsadm.go
This commit also removes the data return from the namespace, as it's
not necessary.
=> api: Returns conflict when inserting an existing namespace

ui/src/components/app_bar/AppBar.vue, ui/src/components/app_bar/notification/Notification.vue
The problem is that the variable hasNamespaces passed in the props,
sometimes the resquest was not finished in time. In order to solve
the problem, the status change in the store is checked directly.
=> ui: fix notifications

ui/src/components/setting/SettingProfile.vue
When the user first opened data editing and then password editing.
And the user changed the password, closed the data edit form and
not closed the password edit form.
=> ui: fix the close edit user form

.env, agent/Dockerfile, api/Dockerfile, docker-compose.dev.yml, ssh/Dockerfile, ui/Dockerfile
To enable go modules cache add following to `.env.override`:
```
SHELLHUB_GOPROXY=http://<ADDRESS>
```
Replace `<ADDRESS>` with the address proxy cache URL.
For caching go modules Athens (https://docs.gomods.io) is the recommended
proxy cache but you can use anything else.
To run Athens on `http://localhost:3333`:
```
docker run \
--name athens \
-e ATHENS_DISK_STORAGE_ROOT=/var/cache/misc \
-e ATHENS_STORAGE_TYPE=disk \
--restart always -d -p '3333:3000' gomods/athens:latest
```
To enable npm modules cache add following to `.env.override`:
```
SHELLHUB_NPM_REGISTRY=http://<ADDRESS>
```
For caching npm modules, Verdaccio (https://verdaccio.org/) is the recommended
proxy cache but you can use anything else.
To run Verdaccio on `http://localhost:4873`:
```
docker run --name verdaccio …
```
=> docker: improved container build time

ui/package.json
This reverts commit 838c216e1f10e1486793188839cc5be415040b93.
=> ui: Revert "ui: bump sass-loader from 10.2.0 to 11.1.1 in /ui"

api/authsvc/service.go, api/authsvc/service_test.go, api/deviceadm/service.go, api/routes/sshkeys.go, api/sshkeys/service.go, api/store/mongo/device_store.go, api/store/mongo/firewall_store.go, api/store/mongo/license_store.go, api/store/mongo/namespace_store.go, api/store/mongo/privatekey_store.go, api/store/mongo/publickey_store.go, api/store/mongo/session_store.go, api/store/mongo/store_test.go, api/store/mongo/user_store.go, api/store/mongo/utils.go, api/store/store.go, cli/service.go
* returns ErrNoDocuments if findOne returns nothing
* utilize Mongo-go-Driver errors definitions instead check error string
* don't ignore any error
=> api: returns errors from mongo error definitions

pkg/dockerutils/utils.go
the space is needed to match only paths started in /var
=> pkg: fix regexp to match only containerIDs in correct path

api/pkg/dbtest/dbserver.go
this fix is necessary to test migrations that use mongo 4.4 new structures like in PR #1019
=> pkg: update dbserver to mongo 4.4.4

agent/Dockerfile, api/Dockerfile
local linter in devscripts was using default configuration instead the .golangci.yaml config file
this commit copy the configuration file to each container by Dockerfile
=> docker: add linter configuration to agent and api dockerfiles

agent/go.mod, agent/main.go, agent/pkg/osauth/auth.go, agent/pkg/osauth/auth_test.go, agent/pkg/osauth/user.go, agent/sshd/cmd.go, agent/sshd/server.go
ShellHub run as single user mode.
Since in the mode, not allow to be other accounts.
We don't need root permission to switch users.
Closes: #618
```
$ SHELLHUB_SIMPLE_PASSWORD=$(openssl passwd -1) ./agent
Password: 
Verifying - Password: 
Verify failure
This application is configured via the environment. The following environment
variables can be used:
KEY                            TYPE       DEFAULT    REQUIRED    DESCRIPTION
SHELLHUB_SERVER_ADDRESS        String                true        
SHELLHUB_PRIVATE_KEY           String                true        
SHELLHUB_TENANT_ID             String                true        
SHELLHUB_KEEPALIVE_INTERVAL    Integer    30                     
SHELLHUB_PREFERRED_HOSTNAME    String                            
SHELLHUB_SIMPLE_PASSWORD       String …
```
=> agent: support non-root to run

pkg/api/client/client_public.go
As it is done by `wsconnadapter` automatically, we don't need
to defer close connection in `NewReverseListener` func.
=> pkg: removed defer that was closing connection early

.golangci.yaml, agent/agent.go, agent/tunnel.go
Also revert changes suggested by interfacer linter
=> agent: Disable deprecated interfacer linter from golangci-lint

agent/selfupdater/updater_docker.go, gateway/kickstart.sh
This commit mounts the host's `/etc/resolv.conf` file into the shellhub container via the `/gateway/kickstart.sh` file .
This is necessary to handle a situation where the host's `/etc/resolv.conf` file changes AFTER the shellhub container is started. As noted in the docker documentation (https://docs.docker.com/config/containers/container-networking/#dns-services)
> By default, a container inherits the DNS settings of the host, as defined in the /etc/resolv.conf configuration file. Containers that use the default bridge network get a copy of this file, whereas containers that use a custom network use Docker’s embedded DNS server, which forwards external DNS lookups to the DNS servers configured on the host.
The implication of "get a copy of this file" is that future changes to the host's …
=> gateway: mount /etc/resolve.conf within the container via kickstart

ui/tests/unit/components/app_bar/notification/Notification.spec.js, ui/tests/unit/components/app_bar/notification/__snapshots__/Notification.spec.js.snap
The tests are refactored to improve the visualization of the cases that
are tested.
The tests includes:
- Namespace owner with notifications;
- Doesn't own the namespace with notifications;
- Namespace owner without notifications.
=> ui: refactor UI notification tests

ui/src/components/device/Device.vue, ui/src/components/firewall_rule/FirewallRule.vue, ui/src/components/public_key/PublicKey.vue, ui/src/components/session/Session.vue, ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/__snapshots__/Device.spec.js.snap, ui/tests/unit/components/firewall_rule/FirewallRule.spec.js, ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap, ui/tests/unit/components/public_key/PublicKey.spec.js, ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap, ui/tests/unit/components/session/Session.spec.js, ui/tests/unit/components/session/__snapshots__/Session.spec.js.snap
First, the error occurs when it comes from the second or next namespace
and click in logout. This causes a request to occur on devices, session,
firewall rules and namespaces.
This closes #935.
=> ui: fix call requests on logout

api/routes/auth.go, api/services/auth.go, api/services/auth_test.go, api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_30.go, api/store/mongo/migrations/migration_30_test.go, gateway/shellhub.conf, pkg/models/device.go
When the devices request a auth the system is capable to store
the remote address who's make the request.
=> api: add a way to track the remote IP

.golangci.yaml, agent/go.sum, api/go.mod, api/go.sum, api/routes/auth.go, api/services/auth.go, api/services/utils.go, cli/go.sum, go.mod, pkg/models/device.go, pkg/models/user.go, ssh/go.sum
Since the https://github.com/dgrijalva/jwt-go is deprecated
and it may be a security breach, the commit changes to the new
version of the package.
=> api/agent/pkg/ssh/cli: update jwt

api/routes/sshkeys.go, api/server.go, api/services/mocks/services.go, api/services/sshkeys.go, pkg/api/client/client_internal.go, pkg/models/publickey.go, ssh/server.go, ssh/ssh2ws.go, ui/src/components/public_key/KeyFormDialog.vue, ui/src/components/public_key/PublicKeyList.vue, ui/src/store/api/public_keys.js, ui/tests/unit/components/public_key/KeyFormDialog.spec.js, ui/tests/unit/components/public_key/PublicKeyList.spec.js, ui/tests/unit/components/public_key/__snapshots__/PublicKeyList.spec.js.snap
First, It was just added a new field, `usernames`, that is a `regexp` expression for all allowed usernames.
```http
POST http://localhost:80/api/sshkeys/public-keys
{"name":"PublicKeyName","usernames": ".*","data":"...","hostname":".*"}
```
After that, I have checked if the `username´ who want to connect match.
=> Restrict user access using public keys

agent/Dockerfile, api/Dockerfile, cli/Dockerfile, ssh/Dockerfile
```
go get: installing executables with 'go get' in module mode is deprecated.
To adjust dependencies of the current module, use 'go get -d'.
To install using requirements of the current module, use 'go install'.
To install ignoring the current module, use 'go install' with a version,
like 'go install example.com/cmd@latest'.
See 'go help get' and 'go help install' for more information.
```
=> docker: replace `go get` with `go install`

ssh/session.go
This fixes unexpected behaviour when getting command output from `CombinedOutput()` (x/crypto/ssh.*Session.CombinedOutput) which returns an empty buffer.
=> ssh: wait remote command to exit

api/services/device.go
Previously, was possible to create a name for a tag with /@&:
this commit is to disallow these types of characters when creating
the tag name.
Signed-off-by: Juan <juan.rios@ossystems.com.br>
=> api: excludes the characters /@&: for create and update tag name

api/routes/auth.go, api/routes/device.go, api/routes/nsadm.go, api/routes/session.go, api/routes/user.go
The `echo` returns a `200` HTTP code when the routing function return a nil,
but it is not explicit for the dev, so I have guessed, for the sake of
simplicity, change it to an empty body with the `200` status.
Another point is the responses which return a JSON, but with `null` inside the
body. I believe it could be a simply `no body` too with the original
status.
=> api: change null JSON's responses to empty body

api/server.go
We have built our own log middleware to ensure proper log entries order. It also enables request tracing using X-Request-ID header.
=> api: add custom logging middleware

ui/src/components/device/Device.vue, ui/src/components/device/DeviceList.vue, ui/src/components/device/DevicePendingList.vue, ui/src/components/device/DeviceRejectedList.vue, ui/src/components/filter/object.js, ui/tests/unit/components/device/Device.spec.js, ui/tests/unit/components/device/__snapshots__/DevicePendingList.spec.js.snap, ui/tests/unit/components/device/__snapshots__/DeviceRejectedList.spec.js.snap, ui/tests/unit/components/filter/Object.spec.js
This commit removes mixins, because when a component uses it, all options in
the mixin will be "mixed" into the component's own options.
This is causing the actions in create device to be called again on the other
related components.
=> ui: remove mixins in devices components

ui/package-lock.json, ui/package.json, ui/tests/unit/components/device/DeviceDetails.spec.js, ui/tests/unit/components/filter/Date.spec.js, ui/tests/unit/components/session/SessionDetails.spec.js, ui/tests/unit/components/session/SessionList.spec.js
This commit mock the timezone so that when running the local tests there is no
error with a different timezone than the container.
=> ui: mock timezone to tests

gateway/shellhub.conf
Uses a different variable name in auth location block due to subrequests
of auth_request module that share variables with their parent requests,
which causes variable override.
=> gateway: Uses a different variable name in auth location block

ui/src/components/user/UserWarning.vue, ui/tests/unit/components/user/UserWarning.spec.js
applayout component sometimes executes before the namespace state
is available through namespacemenu get, this fixes dialog show
making use of another request in this case.
=> ui: Fix concurrent behavior in warning dialog

api/services/mocks/services.go, api/store/device_store.go, api/store/mocks/store.go, api/store/mongo/device_store.go, api/store/mongo/device_store_test.go
The previous query related to top usage of devices had some performance issues,
this commit updates the previous store function use to use a faster aggregation.
=> api: update store device toplist to a more effective query

ui/src/components/device/DeviceChooser.vue
This commit adds the functionality to interact only with dialog buttons to
perform actions.
=> ui: disable closing dialog when user clicks outside dialog

ssh/session.go
This commit improves the error message on the terminal when the user has more
than 3 devices and is not enabled for billing.
=> ssh: update message when user can't access device

ui/src/router/index.js, ui/src/views/Dashboard.vue
This avoids unnecessary usage of localStorage to store data that does not need to be persisted between page refresh/reload.
=> ui: refactor dashboard component to use props to show not found alert

api/pkg/guard/guard.go, api/pkg/guard/guard_test.go, pkg/authorizer/actions.go, pkg/authorizer/authorizer.go, pkg/authorizer/authorizer_test.go, pkg/authorizer/permissions.go
While the development API's token feature, I've noticed some issues
that could be problematic when a new member's role is added. When a
new role needs to be added, the developer should change many places
, what could lead to a probable error.
Changing from function to a map will decrease that possibility, no
more loop are needed and the code is simplified.
At this commit, the namespace's create action was also removed due
to uselessness. It is "useless" because no matter your role on a
namespace, the user might create a new one as itself as owner.
=> api, pkg: remove function to get all roles and remove unused action

api/go.mod, api/routes/auth.go
Since echo is using github.com/golang-jwt/jwt we need too to avoid type assertion error with jwt.Token type
=> api: perform correct type assertion for jwt.Token type

ui/src/store/helpers/http.js
When the request returns status code 401 is necessary to set the simple layout
type.
This closes #1587.
=> ui: fix app layout after JWT expires

ui/src/components/device/DeviceList.vue, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
This commit moves 'Tags' column to second last position, removes the 'Tags'
text from column label, converts v-chip element to non-block (inline), and
hides tooltip when there is no other tags to show.
This closes #1612.
=> ui: device list page improvements

ui/src/components/billing/BillingDialogPaymentMethod.vue, ui/src/plugins/vuetify.js
Fixes the payment form dark layout.
=> ui: add payment layout form in vuetify configs

ui/src/components/app_bar/AppBar.vue, ui/src/layouts/AppLayout.vue, ui/src/store/modules/layout.js, ui/tests/unit/layouts/AppLayout.spec.js, ui/tests/unit/layouts/__snapshots__/AppLayout.spec.js.snap, ui/tests/unit/store/Layouts.spec.js
This commit restores navigation drawer that were removed this commit #1588.
=> ui: restore navigation drawer to show on mobile

ui/src/components/namespace/NamespaceRename.vue, ui/src/components/setting/SettingNamespace.vue, ui/tests/unit/components/namespaces/NamespaceRename.spec.js, ui/tests/unit/components/namespaces/__snapshots__/NamespaceRename.spec.js.snap, ui/tests/unit/components/setting/SettingNamespace.spec.js, ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
This commit removes the part of the code responsible for renaming the
namespace to a new component responsible for just that functionality.
=> ui: move rename namespace to component

pkg/api/client/client.go, pkg/api/internalclient/client.go
Also adds error check when requesting to `/devices/auth` through client,
which was causing agent panics in case of agent service initializing
before the api.
=> pkg: set request retrials for http client

ui/src/components/device/Device.vue, ui/src/components/device/DeviceList.vue, ui/src/components/setting/tag/TagSelector.vue, ui/src/store/modules/tags.js, ui/tests/unit/components/device/DeviceList.spec.js, ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap, ui/tests/unit/components/setting/tag/TagSelector.spec.js, ui/tests/unit/components/setting/tag/__snapshots__/TagSelector.spec.js.snap, ui/tests/unit/store/Tags.spec.js
This commit uses the store to set the selected tags. This is used to work with
the tag dropdown, tagging selected tags.
=> ui: add device filter by tag when clicking tag in device list

ui/src/components/device/DeviceDelete.vue, ui/src/components/namespace/Namespace.vue, ui/src/components/tag/TagFormUpdate.vue, ui/src/components/tag/TagSelector.vue, ui/src/store/modules/tags.js, ui/tests/unit/components/tag/__snapshots__/TagSelector.spec.js.snap, ui/tests/unit/store/Tags.spec.js
It also fixes the following:
- Leaves the button disabled when tags are empty.
- Fetches namespace list when clicking menu namespace.
This Closes #1688.
=> ui: add dispatches in namespace and tags components

api/pkg/dbtest/dbserver.go, docker-compose.yml
We need to use replicaset in order to support multi-document ACID transactions.
=> Convert standalone mongodb instance to local replicaset

api/store/mongo/migrations/migration_42.go, api/store/mongo/migrations/migration_42_test.go
Indeed, the down migration 42 is not broken, but the variable inside the mongo
pipeline was not correct, what could cause some unwanted behavior.
=> api: fix down on migration 42

api/store/mongo/migrations/migration_42.go
Without this modification, when public_key is merged on pipeline end,
the field `filter` will remain.
=> api: change how public_key is merged when migration 42 is down

ui/src/components/firewall_rule/FirewallRuleFormDialogEdit.vue, ui/src/vee-validate.js, ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogEdit.spec.js
Define its default value as empty list and uses vee-validate instead
of watcher.
=> ui: fix default value of tagChoices

docker-compose.autossl.yml
We are using our own 'docker-nginx-auto-ssl' image because upstream is using the latest tag (bad practice) instead of a specific versioned tag.
=> docker: update autossl image

.env, api/go.mod, api/go.sum, api/main.go, api/server.go, api/worker.go, cli/go.sum, docker-compose.yml
The main reason for this is that ofelia does not support kubernetes, running only in docker-compose based environment.
=> api: migrate from ofelia job scheduler to asynq

gateway/shellhub.conf
On that commit, I've changed the URL to preview the OpenAPI, from
`localhost/openapi` to `localhost/openapi/preview` and added a new
one: `/localhost/mock` to enable mock test.
=> gateway: add route to hit mocked API from OpenAPI.

agent/sshd/server.go, ssh/session.go
I've also added a pipe from agent to client with stderr when `requestType` is "exec".
=> ssh,agent: progate the exit code from agent to client

agent/sshd/cmd_docker.go
Since nsenter already change root directory, we don't need
to manually specify the rootfs (/host).
=> agent: remove /host prefix from working directory

api/routes/auth.go, api/services/auth.go, api/services/mocks/services.go, api/services/namespace.go
When a user login into a namespace, it got a JWT token containing
some information about it.
Unfortunately, this approach generated some problems related to
role update, when a user has its role changed by someone else.
Caching the token when a user login and cleaning this cache when
its role is updated, it helps to invalid a token after a role
update.
=> api: invalidate token when user's role change

ssh/go.mod, ssh/go.sum
This commit fix public key authentication using rsa-sha2 keys that are not working anymore.
=> ssh: bump crypto/ssh to latest version

agent/init_docker.go
As bundle install method uses the same binary used by docker container we need to detect in runtime if we are running in docker environment or somewhere
=> agent: set agent platform during initialization

api/routes/auth.go
Just to make it easier to understand what is going on.
=> api: use const key instead of hard-coded value to get JWT from middleware

ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/session/session.go
I have fixed the missing breaking line when an error message is sent to the user, and I added the one when client cannot authenticate on device/agent.
=> ssh: fix break line and error messages sent to user

bin/cli, cli/main.go
Refactoring CLI commands to work as a "resource command parameter" pattern. All commands are, now, based on the resource it works on.
Each resource has commands related to it. A user can be created, has its password edited and remove; a namespace can be created and deleted; a member can be added or removed from a namespace.
To interact with the new commands on the CLI service, a new script called "cli" on bin/ folder was created. It just runs a `docker-compose exec` passing the parameters to CLI service and return its output to who executed the script.
The old CLI commands and scripts to interact to CLI service still are on bin/ folder, but was tagged as deprecated, what makes it does not appear on helper or usage command.
=> cli, bin: refactor CLI commands basing it on resources

ssh/server/server.go
Hello shellhub developers,
First of all, thank you for this great project, it answers a real need when you have to connect to various linux machines distributed in non mastered network environment.
A feature that I was missing to be able to use shellhub in my ecosystem is the ability to perform port forwarding.
Other people have reported this need here: https://github.com/shellhub-io/shellhub/issues/90
I took the time to examine the code and make this feature work.
With this pull request it is possible to connect with ssh to a device and specify a port forwarding like this: 
```
ssh user@<shellhub_device>@<shellhub_host> -L 0.0.0.0:42667:192.168.8.13:443
```
What do you think of it?
=> Feature/allow AllowTcpForwarding 

cli/main.go
At the deprecated command `add-namespace` the user could pass the `TENNANT_id` as a shell's variable to set the namespace's tenant instead of generate a new one. Unfortunately, the new `cli` script no more pass this variable to the cli's container, requiring the tenant to be  defined on the own create namespace's command.
```sh
./bin/cli namespace create shellhub shellhubspace 00000000-0000-4000-0000-000000000000
```
=> cli: call method to delete namespace and add tenant to usage

pkg/api/client/client.go
When the buildURL method was called with query string params
the question mark (?) char was escaped (as %3F),
which is not expected in HTTP request.
=> pkg: fix wrong url escaping in `buildURL()` method

ssh/pkg/tunnel/tunnel.go
Reuse the same HTTP client instance instead of creating a client
per tunnel. This will prevent the SSH process from keeping many
TCP connections open.
=> ssh: reuse the same HTTP client instance

ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
Update the `Session Details` snapshot, because the message of time connection on mouse hover has update.
=> ui: fix session details test

ui/src/views/ValidationAccount.vue, ui/tests/unit/views/__snapshots__/ValidationAccount.spec.js.snap
Added expired token message on `ValidationAccount` page.
=> ui: add token error on Validation Account page

ssh/pkg/tty/tty.go, ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/session/session.go
I wonder a way to info the user about what is happening during the connection, avoid a blank screen when something is not responding on the desiring time.
I have created a new package responsible to write on the SSH client connection some data. At this package, I have also coded some function to perform some basic operation on a TTY like: clean the screen, move the cursor or sing a bell.
The idea is to use this new package to creating a log like this, informing the user when something wrong happened or when something is taking longer to execute an action.
When the connection is successfully, the log is cleaned, and only the device TTY appears.
=> ssh: add TTY package as a helper to write on SSH connection

new-ui/src/App.vue, new-ui/src/components/AppBar/Notifications/Notification.vue, new-ui/src/components/Billing/BillingWarning.vue, new-ui/src/components/Devices/DeviceActionButton.vue, new-ui/src/components/Devices/DeviceRejectedList.vue, new-ui/src/components/Setting/SettingBilling.vue, new-ui/src/components/Setting/SettingNamespace.vue, new-ui/src/components/Setting/SettingProfile.vue, new-ui/src/components/firewall/FirewallRuleAdd.vue, new-ui/src/components/firewall/FirewallRuleEdit.vue, new-ui/src/store/modules/devices.ts, new-ui/src/store/modules/notifications.ts, new-ui/src/views/UpdatePassword.vue
- Don’t send request on Add/Edit firewall rule with empty tags field
- Update password, save button is disabled
- Tenant ID copy has a wrong background color
- Reset password if edit the second input first, the error “Password not match”
- Billing data in console log.
- Filtering devices accept, reject, pending. Show all in the pages.
- Billing warning not showing.
- Made dashboard request when user is not logged
- Fix devices pending on notification component
- Fix rejected devices lists page
=> new-ui: bugs found in 0.11-rc-4

new-ui/src/App.vue, new-ui/src/components/Devices/DeviceIcon.vue, new-ui/src/components/Devices/DeviceList.vue, new-ui/src/components/Devices/DevicePendingList.vue, new-ui/src/components/Devices/DeviceRejectedList.vue, new-ui/src/components/Sessions/SessionPlay.vue, new-ui/src/components/firewall/FirewallRuleAdd.vue, new-ui/tests/components/Device/DeviceIcon.spec.ts, new-ui/tests/components/Device/__snapshots__/DeviceIcon.spec.ts.snap
- Slide don’t update the session record
- Permission in add firewall rule
- Icon default when the device name not in the default list
- Update `DeviceIcon` test with new rule.
=> new-ui: bugs found in 0.11-rc-5

agent/server/server.go, ssh/pkg/metadata/constants.go, ssh/pkg/metadata/restore.go, ssh/pkg/metadata/store.go, ssh/server/channels/tcpip.go, ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/server/server.go
```
I have added handlers to deal with data coming from `direct-tpcip` and
`dynamic-tcpip` channels, consequently enabling Local Port Forward and
Dynamic Port Forward.
e.g. `ssh -L 8080:localhost:80 user@host`
e.g. `ssh -D 1080 user@host`
```
https://github.com/shellhub-io/shellhub/issues/513
=> ssh,agent: add support for local port forward and dynamic port forwarding

README.md
Fix typo on README: [ShellHub Cloud](https://shellhub.io/) seems to be correct at https://cloud.shellhub.io.
=> README: fix url

ui/src/components/AppBar/AppBar.vue
Redirect user to github issues template, while the gitter aside chat don't have support to the new version with matrix.
=> ui: remove gitter aside chat

.github/workflows/qa.yml, .golangci.yaml, agent/go.mod, agent/server/utmp/utmp.go, api/go.mod, cli/go.mod, go.mod, ssh/go.mod
This commit updates the linters configuration file to disable
all linters by default and enable only the necessary ones.
Also, the deprecated linters have been replaced.
As a result, all `go.mod` files were updated to require Go 1.18
=> cicd: refactors linters configuration

gateway/shellhub.conf
This commit updates the `proxy_pass` configuration to use a
variable for the upstram server instead of a hardcoded value.
By using a variable in the `proxy_pass` configuration, the DNS
resolution occurs dynamically rather than when nginx starts up.
This will prevent nginx from exiting with a
"host not found in upstream" error if the host is not yet
available on the network.
=> gateway: update proxy_pass config to use var for upstream server

ui/src/store/modules/private_key.ts
This error was occurred because, when the user doesn't have private keys, the old code tries to parse an empty string in an object.
closes #2554
=> ui: fix add private key

.env, docker-compose.yml, gateway/shellhub.conf
This commit adds the `SHELLHUB_PUBLIC_URL_DOMAIN` environment variable to the `.env` file, which is used to define the public URL domain for accessing devices via HTTP in a ShellHub instance.
The value of this variable is used in the `gateway/shellhub.conf` file to generate the public URL for HTTP access.
The `docker-compose.yml` file is also updated to pass this variable to the gateway container.
NOTE: If `SHELLHUB_PUBLIC_URL_DOMAIN` is not defined, the value of `SHELLHUB_DOMAIN` is used as the default value.
=> env: Add SHELLHUB_PUBLIC_URL_DOMAIN env

pkg/dockerutils/utils.go
This commit updates the regex pattern used to identify Docker container IDs.
The updated pattern is more flexible and should match a wider range of Docker setups.
=> pkg: improve regex pattern for identifying Docker container IDs

api/services/device.go
Previously, when calling the UpdateDeviceStatus method,
if the device with the given UID was not found, the method
would return a generic error from the underlying data store
causing a 500 internal error.
=> api: handle device not found error in UpdateDeviceStatus

devscripts/add-device
This pull request updates the `add-devices` use case to work in more scenarios by addressing a zsh rules conflict that was causing it to fail on some machines.
- Added additional code to the `add-devices` use case to address the zsh rules conflict.
- Improved test coverage to ensure that the updated use case is functioning as expected in a variety of scenarios.
- Ran the updated `add-devices` use case on multiple machines with different configurations to ensure that the zsh rules conflict was resolved and that the script is working as intended.
- Added additional test cases to the automated test suite to cover the newly supported scenarios.
- Fixes #2671
=> devscripts/added more coverage in add-device randomizer functionality

ui/src/layouts/AppLayout.vue
The `app-layout` previous background was unnecessary and detracted from the overall polished appearance of our application.
1. Run the `Shellhub.io`
2. Observe the request response from the `AppLayout` releasing the blinking loading screen.
The `add-devices` script shouldn't emit a blinking background at every request.
- Operating System: All
Community, Cloud
v0.11.7
=> ui: fixed white overlay changing it to transparent

ui/src/components/AppBar/Notifications/Notification.vue, ui/src/components/Devices/DeviceActionButton.vue, ui/src/components/Devices/DevicePendingList.vue
This Pull Request has changes for the `Notification.vue` component that had a duplicated button behind and was not showing the accept device modal.
This PR closes #2690 
Changed Bell Notification behavior to show up the accept device modal
Removed the duplicated button behind the accept button in Bell Notification 
Open the notification in the app top bar and accept a device.
=> ui: fixed bell notification duplicated button

ui/src/router/index.ts, ui/src/views/NotFound.vue, ui/tests/views/NotFound.spec.ts
This Pull Request has changes for the `NotFound.vue` view which was added for non route urls to show.
This PR closes #2700
Added `NotFound.vue` view
Added `NotFound` unitary test
Changed Router to show the new view when no known url is on the website
Put the URL with any not used routes.
Observe the new 404 not found page.
=> ui: added non route page 404

gateway/Dockerfile
This commit updates the gateway Dockerfile to add a Let's Encrypt volume
so that SSL certificates can be easily managed outside of the container
=> gateway: add Let's Encrypt volume to Dockerfile

.env, bin/docker-compose, docker-compose.nossl.yml
This commit removes the SHELLHUB_REDIRECT_TO_HTTPS variable from the
.env file and simplifies the docker-compose files.
The docker-compose.nossl.yml file is removed and the SSL_COMPOSE_FILE
variable in the bin/docker-compose script is updated to only include
the autossl suffix if SHELLHUB_AUTO_SSL is true.
=> docker: remove SHELLHUB_REDIRECT_TO_HTTPS and simplify docker-compose

ui/src/components/DataTable.vue
This Pull Request has changes for the `DataTable.vue`  to disable the arrow page choosers to disable when there's no pages
This PR closes #2723 
Changed the arrow keys to disable when there no other page to move in.
1. Move to the devices list.
2. Click the arrows to move to other pages.
3. Observe the behavior for changing pages to non-existent ones.
=> ui: changed device page list to disable if theres no more pages

bin/docker-compose
The commit adds code that checks the version of the docker compose plugin
or standalone binary to determine which one supports the V2 spec.
If either of them does, the corresponding command is used.
=> docker: Improve docker compose compatibility with V2 spec

ui/src/layouts/AppLayout.vue
This PR fixes the issue and closes #2754  by modifying the code responsible for pre-loading the namespaces and everything in the App Side Bar. Now, they will only be loaded when the user is logged in and on a page that requires them. This will prevent the infinite loop and allow users to update their passwords without being redirected to the login page.
Overall, this PR improves the user experience and ensures that the App Side Bar components are loaded only when needed, reducing unnecessary loading times and errors.
`Namespaces` and the `NewConnection` in the App Side Bar should only be loaded when the user is logged in and on a page that requires them.
`Namespaces` and the `NewConnection`  in the App Side Bar were being pre-loaded even when the user was on an external route page or not …
=> fix: ui new connection button pre-load rerouting to login page

ssh/go.mod, ssh/go.sum, ssh/server/handler/ssh.go
Agent version less than 0.9.3 does not support SSH exec command, what makes some request for it hang foverever. Version great than that, closes correctly and return the status code from the ran command.
=> fix(ssh): force exit when exec command is run on agent less than 0.9.3

ui/src/api/http.ts, ui/src/store/index.ts, ui/src/store/plugins/api.ts
This commit refactors the API client setup in the 'ui/src/api/http.ts' file.
The configuration now sets the base path and access token based on the current
window location and the stored token, respectively. Additionally, custom
configuration for cloud endpoints was introduced. It also sets up interceptors
for each API instances.
In the 'ui/src/store/index.ts' file, a new plugin was added to the Vuex store.
This plugin is responsible for subscribing to store mutations for handling
API-related logic and actions.
Note: The 'createNewClient' method is deprecated and no longer performs any
action. It is kept for backward compatibility but will be removed in the future.
=> refactor(ui): refactor API client setup

api/pkg/echo/handlers/binder.go
The echo's bind function does not bind header implicite, we must convert our binder to echo's default one and ask it to bind the headers.
=> fix(api): fix echo bind for headers what needs to be explicit

bin/docker-compose
This commit fixes the syntax error and ensures compatibility with
dash shell. The modification replaces the `<<<` operator with a
pipe (`|`) to redirect the output of commands into `grep`.
Closes #2914
=> fix(bin): resolve syntax error in docker-compose script

api/routes/device.go, api/routes/device_test.go, api/routes/routes.go, api/services/device.go, api/services/device_test.go, api/services/mocks/services.go, pkg/api/requests/device.go
It only renames the methods, without refactoring the logic, what will be fixed next.
=> chore(api,pkg): rename method to update device status and request model

gateway/conf.d/shellhub.conf, gateway/entrypoint.sh
* Added a new location block to handle ACME challenges for SSL certificate
generation using Certbot
* Updated Certbot command to use webroot mode instead of standalone mode
=> fix(gateway): SSL certificate generation using Certbot

ui/src/components/Billing/BillingIcon.vue
Fix following error during build step:
```
src/components/Billing/BillingIcon.vue(26,3): error TS2345:
Argument of type 'IconDefinition' is not assignable to parameter
of type 'IconDefinitionOrPack'.
```
=> fix(ui): fix build step

api/routes/device.go, api/services/device.go, api/services/device_test.go, api/services/errors.go, api/services/mocks/services.go, pkg/envs/envs.go, pkg/models/namespace.go
Improve the `UpdateDeviceStatus` service's method with a more readable and simpler logic.
From the current implementation of `UpdateDeviceStatus` logic, I drew this flow chart to summarize what the method does today, and what It should do. 
> I'm still improving my charts; Any improvement suggestion is welcome.
```mermaid
flowchart TD
A[Start] --> B{Does Namespace exist?}
B --> |Fail| X([Return error])
B --> |Success| C{Does Device exist in this namespace?}
C --> |Fail| X
C --> |Success| D{Is the new device status 'accept'?}
D --> |No| F([Update device status to the new one])
D --> |Yes| E{Is the ShellHub instance Cloud?}
E --> |No| F
E --> |Yes| G{Has namespace a subscription enabled?}
G --> |Yes| H[/Report device to billing service/]
G --> |No| I{How many devices has been removed in the …
```
=> refactor(api,pkg): improve UpdateDeviceStatus service's method

api/routes/device_test.go, api/routes/healthcheck_test.go, api/routes/nsadm_test.go, api/routes/session_test.go, api/routes/sshkeys_test.go, api/routes/stats_test.go, api/routes/tags_test.go, api/routes/user_test.go
This commit implements more test cases for the 'routes' layer.
The added test cases are the structure tag validation, 
the objective with these cases is to make sure that all the tests 
are complying with the established validation rules.
=> test(routes): implementing test cases of tag validation

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_59.go, api/store/mongo/migrations/migration_59_test.go
To maintain consistency, new users are now created with lowercase usernames. This ensures that find operations, which are also case-sensitive, function correctly. This migrate updates older users to follow this convention.
=> normalize user to lowercase

gateway/conf.d/shellhub.conf
This change updates the HTTP redirect status code from 301
to 308 in the gateway service.
The 308 status code preserves the original HTTP method and
request body during redirection, providing better
consistency and behavior for our use case.
=> feat(gateway): change redirect status code from 301 to 308

ui/src/components/DataTable.vue
This PR is aimed to solve an issue which the data-table listing
wasn't updating by the items per page button.
=> fix(ui): data-table items per page not changing

api/routes/auth_test.go, api/services/auth.go, api/services/auth_test.go
when trying to make login using 'user actions' through cloud, the token generated to login is invalid because is not save in cache, this correction is to save token in cache in the AuthGetToken function, this providing a valid token on the user actions screen
=> fix(api): caching user token

ui/src/components/Devices/DeviceRename.vue, ui/src/store/modules/devices.ts, ui/tests/components/Devices/DeviceRename.spec.ts, ui/tests/components/Devices/__snapshots__/DeviceRename.spec.ts.snap
This Pull Request is intended to address an issue where input from the Device Rename
feature was persisting with every change in the v-text-field, even if the user
didn't complete the changes. It also resolved the same bug that was causing
unsaved changes in other devices to persist.
=> fix(ui): device rename persisting the input on devices

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_60.go, api/store/mongo/migrations/migration_60_test.go, api/store/mongo/session_store.go, api/store/mongo/stats_store.go, pkg/models/session.go
This commit adds an index on `tenant_id` in the `active_sessions`
collection to improve the performance of active session counting.
It also updates code in MongoDB store to utilize this index.
Closes #3228
=> fix: optimize active session count query

api/store/mongo/device_store.go
- Removed redundant `$sort`, `$lookup`, and `$addFields` stages in the count query.
- Moved heavy operations like `$lookup` and `$addFields` after pagination stage.
=> refactor(api): optimize device listing query

api/store/mongo/device_store.go
Previously, the `device` variable was declared outside the loop,
leading to potential issues due to reusing the same object
for decoding multiple devices.
This commit fixes the issue by declaring `device` within the loop,
ensuring that each device is decoded independently.
=> fix(api): correctly decode devices in DeviceList

ssh/server/channels/tcpip.go, ssh/server/handler/sftp.go, ssh/server/handler/ssh.go, ssh/server/server.go, ssh/session/errors.go, ssh/session/session.go, ssh/session/types.go, ssh/session/utils.go
When a client connects to the SSH server using an option that sets the request type to `none`, the Local Port Forward doesn't know which device to connect because the SSH Handler wasn't called.
To allow it, we have dialed to the device through the tunnel and authenticated it. In order to avoid a lot of duplication, we also have refactored how the SSH server creates session, and added a new kind of SSH session what doesn't depend on SSH request type.
Resolves #3233
=> fix(ssh): local port forwarding with no request type

api/store/mongo/device_store.go
* DeviceSetOnline: ensures that incomplete device documents are not inserted
* DeviceUpdateStatus: avoid registering a device as online when changing
its status to accepted.
=> chore(api): refactor device store

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_62.go, api/store/mongo/migrations/migration_62_test.go
Given that 'recorded_sessions' can constitute up to 99% of the entire database, certain operations may experience prolonged blocking, disrupting the current context and leading to unexpected errors. To mitigate this issue, we are now implementing a new index on the 'tenant_id' field.
=> add index for tenant_id on recorded_sessions

api/routes/auth.go, api/routes/auth_test.go, api/services/auth.go, pkg/api/requests/auth.go
This commit addresses a bug related to variable names in the GetToken API. The goal is to change the name from 'tenant' to 'id' since the provided value is the ID, not the tenant. This adjustment ensures accuracy and consistency in the API behavior.
=> fix(api): correct variable names in GetToken API

ui/src/components/AppBar/Notifications/Notification.vue, ui/src/components/Devices/DeviceAcceptWarning.vue, ui/src/components/Devices/DeviceActionButton.vue, ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/src/components/Devices/DeviceRename.vue, ui/src/components/User/UserWarning.vue, ui/src/store/modules/devices.ts, ui/src/store/modules/users.ts, ui/tests/components/Devices/__snapshots__/DeviceAcceptWarning.spec.ts, ui/tests/components/Devices/__snapshots__/__snapshots__/DeviceAcceptWarning.spec.ts.snap
This PR is aimed to validate when the user tries to accept a device
that has the same name as an already accepted device.
=> feat(ui): add validation modal for conflicted device names

pkg/connman/connman.go, pkg/connman/syncslicemap.go
This commit refactors the `ConnectionManager` by replacing the `sync.Map`
for dialers with a `SyncSliceMap`.
The `SyncSliceMap` struct provides methods for loading, storing, and
deleting values in a synchronized map with slices.
The use of `SyncSliceMap` improves the management of reverse dialers and
handles multiple connections for the same identifier.
This change potentially addresses the SSH connection issue where multiple
agents using the same identifier prevented SSH connection, even when the
web interface showed them as online.
=> refactor(connman): restructure ConnectionManager and introduce SyncSliceMap

gateway/conf.d/shellhub.conf
Fix the issue of inadequate distribution of client connections
among worker processes by enabling the `reuseport` option.
This enhancement allows the kernel to efficiently distribute
incoming connections across multiple worker processes, resolving
the 'worker_connections are not enough' error.
=> fix(gateway): fix "worker_connections are not enough" error

.golangci.yaml, api/go.mod, api/go.sum, cli/go.mod, cli/go.sum, go.mod, pkg/uuid/uuid.go, ssh/go.mod, ssh/go.sum
`github.com/satori/go.uuid` is no longer being actively maintained (last commit was 5 years ago [^1]). So we should just use the newer `github.com/google/uuid`.
[^1]: https://github.com/satori/go.uuid/commits/master/
=> chore(deps): replace satori/go.uuid with google/uuid

pkg/wsconnadapter/wsconnadapter.go
Fix an issue in wsconnadapter where attempting to write to a nil
channel during the Close method could lead to a runtime panic.
=> fix(wsconnadapter): prevent nil channel write in Close method

.github/workflows/qa.yml
This commit is aimed to update the node version to 21.4 on QA workflow.
=> chore(qa): update node version on QA

ui/src/layouts/AppLayout.vue
This Pull Request is aimed to fix an issue where the loading progress
would be on the top-left of the screen.
=> fix(ui): added class to center loading on appLayout

pkg/agent/server/modes/host/sessioner.go
While `session.Command()` tokenizes command arguments by spaces, resulting in incorrect parsing of quoted arguments, `session.RawCommand()` preserves the command string intact, ensuring proper handling of quoted arguments.
Fixes: #3545
=> fix(agent): use raw command to fix issues with quoted arguments.

bin/docker-compose, docker-compose.agent.yml, docker-compose.dev.yml
We moved the Agent's compose service to a dedicate compose file to allow more flexibility when running the dev environment, especially for the integration tests.
The current behavior hasn't changed; when the `SHELLHUB_ENV` is set to development, the Agent still starts together with the services, but now we could separate this process using a env variable more easily in the future.
=> refactor: move dev agent service to it own compose file

ui/src/authorizer.ts
This PR is aimed to correct the notificationView authorizer name that is spelled incorrectly.
=> fix(ui): correct notification view nomenclature

bin/add-namespace, bin/add-user, bin/add-user-namespace, bin/cli, bin/del-namespace, bin/del-user, bin/del-user-namespace, bin/docker-compose, bin/reset-user-password, bin/utils, cli/Dockerfile, cli/entrypoint-dev.sh, cli/entrypoint.sh, docker-compose.dev.yml, docker-compose.yml
Changed the docker-compose commands in the CLI scripts to use 'run'
instead of 'exec', eliminating the need for the CLI service to be
continuously running.
=> feat(cli): use 'run' instead of 'exec' for docker-compose commands

gateway/conf.d/shellhub.conf, gateway/entrypoint.sh
Set the backlog value based on the kernel parameter `net.core.somaxconn`,
following the approach utilized in the NGINX Ingress controller for Kubernetes.
Referece: https://www.nginx.com/blog/tuning-nginx/
=> feat(gateway): set custom value for backlog parameter

.github/ISSUE_TEMPLATE/bug-report.yml
When opening a new bug report issue, users will now have access to a more descriptive and concise template, facilitating the process of describing issues.
For this purpose, we've included the following required fields in the template:
- **Steps to Reproduce**: This section is intended to describe the specific steps that a user should follow to reproduce an issue.
- **Expected Behavior**: This section aims to describe what a user expects to happen.
Additionally, a set of non-required fields has been added. These fields should be filled in when a user has additional information that may be useful in fixing the issue:
- **Related Logs**: Relevant log outputs that may be related to the issue.
- **Related Code**: Relevant code snippets that may be related to the issue.
- **Additional …
=> improving bug-report template

pkg/agent/pkg/yescrypt/yescript.go
Fixed a segfault issue caused by the use of the non-thread-safe crypt
function by replacing it with the thread-safe crypt_r function.
=> fix(agent): resolve segfault caused by non-thread-safe crypt function

ui/src/components/Namespace/NamespaceEditApiKey.vue, ui/src/components/Namespace/NamespaceGenerateApiKey.vue, ui/tests/components/Namespace/NamespaceEditApiKey.spec.ts, ui/tests/components/Namespace/NamespaceGenerateApiKey.spec.ts
This Pull Request adds error messages to the function responsible for generating and editing a new API key and its test cases.
Added test cases to ensure that error messages are correctly displayed when generating and editing a new API key fails.
None.
=> fix(ui): add error messages and test cases for api key generating and editing

pkg/api/requests/device.go
We have been using the `hostname_rfc1123` for validating the device name, which isn't compatible with [Docker's daemon naming convention](https://github.com/moby/moby/blob/master/daemon/names/names.go#L6), causing containers with `underscore` to be denied by the server for invalid entity format.
Closes #3291
=> fix(api): use device name custom rule for field validation

giscus.json
This change allows limiting the domains that can load Giscus
within the repository's discussions using the 'origins' key.
This is done to prevent spammers and lammers, like those in
the #3761, from creating discussions through unauthorized
Giscus forms just to show off.
For everyone reading this commit, we want to emphasize that
we are an open community welcoming broad discussion and
collaboration. Contributions are highly encouraged,
and behaviors like this will not be tolerated in our community.
=> chore: add configuration to restrict domains in Giscus

api/routes/device.go, api/routes/device_test.go, api/services/device.go, api/services/device_test.go, api/services/mocks/services.go
The service's `OfflineDevice` method was previously misspelled as `OffineDevice`. This has been corrected.
=> fix(api): correct typo in 'OfflineDevice'

docker-compose.yml
- Add stop_signal: SIGKILL for immediate container shutdown
- Set command to `/bin/sleep infinity` to keep the container running indefinitely
=> chore: update cli service in docker-compose

ui/src/components/Welcome/Welcome.vue, ui/src/components/Welcome/WelcomeFirstScreen.vue, ui/src/components/Welcome/WelcomeFourthScreen.vue, ui/src/components/Welcome/WelcomeSecondScreen.vue, ui/src/components/Welcome/WelcomeThirdScreen.vue, ui/tests/components/Welcome/Welcome.spec.ts, ui/tests/components/Welcome/WelcomeFirstScreen.spec.ts, ui/tests/components/Welcome/WelcomeFourthScreen.spec.ts, ui/tests/components/Welcome/WelcomeSecondScreen.spec.ts, ui/tests/components/Welcome/WelcomeThirdScreen.spec.ts, ui/tests/components/Welcome/__snapshots__/Welcome.spec.ts.snap, ui/tests/components/Welcome/__snapshots__/WelcomeFirstScreen.spec.ts.snap, ui/tests/components/Welcome/__snapshots__/WelcomeFourthScreen.spec.ts.snap, ui/tests/components/Welcome/__snapshots__/WelcomeSecondScreen.spec.ts.snap, ui/tests/components/Welcome/__snapshots__/WelcomeThirdScreen.spec.ts.snap
This Pull Request adds unitary tests related to the welcome screens section, testing integration with the API, navigation and the component rendering and validation.
The tests ensure that key elements such as the dialog open button and important headers are rendered correctly. 
- Added tests to verify the rendering of key elements in the Welcome Screens Components dialog.
- Added integration tests with our API.
- Added tests for the behavior functions, like copying texts and navigating.
- Modify the components script tag to `<script setup>` from Vue 3.3 Composition API
- Changed the Copy command to **VueUse** library `useClipboard`
=> test(ui): added welcome screens tests

ui/src/components/AuthMFA/MfaSettings.vue, ui/src/components/Setting/SettingProfile.vue, ui/src/store/modules/auth.ts
This Pull Request adds a new function that will update the recovery email
on the SettingsProfile when it's added by the enabling the mfa process.
=> fix(ui): update recovery email input on enabling the mfa

api/services/auth.go, api/services/auth_test.go, api/store/mocks/store.go, api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_70.go, api/store/mongo/migrations/migration_70_test.go, api/store/mongo/migrations/migration_71.go, api/store/mongo/migrations/migration_71_test.go, api/store/mongo/namespace.go, api/store/mongo/namespace_test.go, api/store/namespace.go, pkg/models/user.go
PreferredNamespace represents the namespace the user most recently authenticated with. This allows the user to authenticate using the most recently used namespace instead of the first one they were added to.
This value is updated every time the user logs in or creates a new authentication token. It is also automatically set to an empty value when the namespace is removed or the user is removed from the members list.
The preferred namespace will be stored under a new `preferences` sub-document in the user's collection. Two new migrations have been added to introduce this new document and attribute.
=> feat(api): preferred namespace

api/routes/auth.go, api/routes/auth_test.go, api/routes/routes.go, api/services/auth.go, api/services/auth_test.go, api/services/mocks/services.go, pkg/api/requests/auth.go
Currently, there are four functions to authenticate a user: `AuthUser`, `AuthGetToken`, `AuthSwapToken`, and `AuthUserInfo`. While the first method authenticates a user with credentials, the subsequent three perform similar tasks involving token retrieval and generation.
To streamline this process, we are removing these three methods and introducing a new, unified method called `CreateUserToken`, consolidating the functionality of the previous three methods into one. The new method will be used in the place of the old methods.
=> refactor(api): simplify user authentication

api/store/mocks/store.go, api/store/mongo/user.go, api/store/user.go, cli/services/users.go, cli/services/users_test.go, pkg/models/user.go
Renamed the store's method `UserDetachInfo` to `UserGetInfo`. Introduced a new type `UserInfo` to serve as the return type, replacing the previous map with "owned" and "members" attributes.
=> refactor(api): user detach info

ui/src/components/Namespace/NamespaceMemberList.vue, ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap
This pull request adds a status header to the namespace members table and a hover tooltip that contains the date in which the user was added to that namespace.
=> feat(ui): status and date on namespace members listing

gateway/nginx/conf.d/shellhub.conf
A new `location /api/user` has been added. This location functions similarly to `/api`, but redirects DELETE requests to the cloud upstream.
=> feat(gateway): redirect 'DELETE /api/user' to cloud

api/services/namespace.go, api/services/namespace_test.go, api/store/mongo/migrations/migration_74.go, api/store/mongo/migrations/migration_74_test.go
Fixing default announcements so they can only not be triggered on the enterprise and cloud edition
this PR is a change to the features added on https://github.com/shellhub-io/shellhub/pull/3984
=> fix(namespace,api,cli): fixing default announcements

ui/src/components/User/PaywallDialog.vue
This Pull Request increases the content padding on the premium paywall to be
the same as the gap between the content cards and removed the persistent
property from the dialog.
Solves #4031
=> fix(ui): increased content padding on premium paywall

gateway/nginx/conf.d/shellhub.conf
Certain MFA endpoints require authentication credentials, such as the 'X-ID' header. We've implemented a new routing rule to differentiate between endpoints that need prior authentication and those that don't.
=> fix(gateway): adjust MFA authentication redirect

agent/Dockerfile, agent/Dockerfile.amd64, agent/Dockerfile.arm64v8, agent/Dockerfile.i386, agent/Dockerfile.test, ssh/Dockerfile
- **Revert "docker: agent: bump golang in /agent"**
- **Revert "docker: agent: bump arm64v8/golang in /agent"**
- **Revert "docker: ssh: bump golang in /ssh"**
=> revert: downgrade golang from 1.23 to 1.22

api/services/auth.go, api/services/auth_test.go, api/services/setup.go, api/services/setup_test.go, api/store/mongo/fixtures/users.json, api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_32_test.go, api/store/mongo/migrations/migration_38_test.go, api/store/mongo/migrations/migration_59_test.go, api/store/mongo/migrations/migration_75.go, api/store/mongo/migrations/migration_75_test.go, api/store/mongo/user_test.go, cli/services/users.go, cli/services/users_test.go, pkg/models/user.go
The `user.confirmed` boolean attribute previously indicated whether a user’s email address was confirmed, limiting us to only two possible states. To provide greater flexibility and to represent more user statuses, this attribute has been replaced with a `user.status` field.
The new `user.status` field is a string (or a custom `UserStatus` type in Go). The constants `UserStatusConfirmed` and `UserStatusNotConfirmed` are introduced to represent the two states previously captured by the `confirmed` boolean.
Migration `75` has been added to update existing user records to align with the new schema.
=> feat(api)!: replace user.confirmed with user.status

api/services/namespace.go, api/services/namespace_test.go, pkg/api/requests/namespace.go
Membership invitations now require an email address. Other identifiers are no longer supported.
=> refactor(api)!: restrict membership invitations to email only

pkg/api/query/paginator.go, pkg/api/query/paginator_test.go
=> fix(api): use `MinPerPage` when per_page is less than or equal to zero

ui/src/components/Namespace/NamespaceMemberAdd.vue, ui/src/store/api/namespaces.ts
This Pull Request fixes the identifier input on the namespace add member,
changing it back to just an e-mail field.
=> fix(ui): rollback namespace member add identifier input to email field

ui/src/components/Namespace/NamespaceAdd.vue, ui/src/components/Namespace/NamespaceInstructions.vue
This Pull Request fixes the Namespace Instructions buttons and template rules back to
new users that didn't have a namespace.
=> fix(ui): returned namespace add template and buttons

ui/src/components/QuickConnection/QuickConnection.vue
This pull request solves a filter=null bug from the device GET request by removing the null from the filter attribute in the setFilter store method presented in the QuickConnection Component.
=> fix(ui): remove null setFilter store method from quickconnection

api/store/mongo/namespace.go, api/store/mongo/namespace_test.go
Ensures that `CreatedAt` is correctly set when a new namespace is created.
=> fix(api): set `CreatedAt` on namespace creation

ui/src/interfaces/INamespace.ts
This commit changes an typo that was found on the INamespaceInvite interface,
which is a "tenant_id" instead of "tenant".
=> fix(ui): typo on INamespaceInvite interface

api/services/namespace.go, api/services/namespace_test.go, api/store/mongo/namespace.go, pkg/models/member.go
In cloud instances, members with a `pending` status must accept their invite within 7 days before they can perform any namespace actions. To handle this, we’ve added an expiration date to the member model.
- Added `ExpiresAt` field to the member model
- Implemented expiration setting for invites
=> feat(api): add expiration to member invites

ui/src/components/PublicKeys/PublicKeyAdd.vue, ui/src/components/PublicKeys/PublicKeyEdit.vue
This Pull Request addresses a missing feature where the tags list was not fetched
when the user entered the public keys add or edit section and selected the
filter tags option. The tags are now correctly retrieved when this option
is chosen.
=> fix(ui): retrieve tags when selecting the filter tags option for public keys

ui/src/components/firewall/FirewallRuleAdd.vue, ui/src/components/firewall/FirewallRuleEdit.vue
Similar to the PR #4184
This Pull Request addresses a missing feature where the tags list was not fetched
when the user entered the firewall add or edit section and selected the
filter tags option. The tags are now correctly retrieved when this option
is chosen.
=> fix(ui): retrieve tags when selecting the filter tags option for firewall

api/services/auth.go, api/services/errors.go, api/services/namespace.go, api/services/namespace_test.go, pkg/models/user.go
create a new limit for user namespace creation, so that now, if MaxNamespaces is a negative value, the user will have no namespace creation limit, if it has a value of zero, the user will not be able to create a new namespace and if it is greater than zero, the behavior will be the same as before
=> fix: namespace creation not permitted for user

ui/src/components/Terminal/TerminalDialog.vue
This Pull Request fixes a type error in the TerminalDialog component related to the
`maxWidth` property of the Vuetify `v-dialog`. The error occurred due to an
incorrect or missing type definition for the `maxWidth` prop, causing issues
during component rendering. This fix ensures proper type handling, resolving
the error and allowing the dialog to function as expected with defined maximum width.
=> fix(ui): resolve type error for v-dialog maxWidth property in TerminalDialog

bin/cli
Before the version v2.21.0 of docker compose, the tag `--format` had
another behavior, which caused the issue attached. We are updating our
script to deal with this issue.
=>  fix(bin): run compose command without format tag

ui/src/components/Namespace/NamespaceMemberDelete.vue
This Pull Request changes the text from the namespace member remove modal, which
had the functionality recently changed to a namespace invitation, making the
never be undone text to be wrongfully placed.
=> fix(ui): change the text from the namespace member remove modal

bin/cli, bin/setup, bin/utils
- Refactored the service check logic by moving it to a reusable
function, `exit_if_not_running`, in `utils`.
- Updated `cli` and `setup` scripts to use this centralized function,
reducing redundancy and improving maintainability.
- Added `exit_if_not_running` invocation in `setup` to ensure ShellHub
is running before proceeding.
=> refactor(cli): centralize service check logic in `exit_if_not_running`

pkg/agent/server/modes/host/utils_freebsd.go
After a small simplification on the method to generate SHELL and EXEC
commands on Agent, we have forgotten to update to the FreeBSD version of
the same file. To fix it, we have added a patch file on the ports, and
created this commit afterward.
Refs: https://github.com/shellhub-io/ports/pull/8
=> fix(agent): implement method to generate CMD command to FreeBSD

ui/src/components/Namespace/NamespaceInstructions.vue
This pull request fixes an issue where the validation for open versions
is being true to cloud or enterprise, since which being true is not
open, the new rule changes the logic to an AND.
=> fix(ui): open version validation

api/services/namespace.go, api/services/namespace_test.go, cli/cmd/namespace.go, cli/pkg/inputs/namespace.go, cli/services/namespaces.go, cli/services/namespaces_test.go, gateway/utils.go, pkg/api/requests/namespace.go, pkg/models/namespace.go, pkg/models/type.go, tests/go.mod, tests/go.sum
Implement new field: APIs and CLI components (ref https://github.com/shellhub-io/cloud/issues/2025)
- Add APIs to support the new field
- Develop CLI components for field interaction
- Follow design outlined in issue https://github.com/shellhub-io/cloud/issues/2025
=> feat(cli,api): add field for namespace type

ssh/server/channels/session.go, ssh/server/channels/utils.go, ssh/server/server.go
In previous refactoring, we have removed a bunch of operations from the server, letting both the parties communicate more freely. However, the session record kept doing the same blocking operations.
The SSH server acts as an intermediary between the Agent and Client, so reducing communication overhead can significantly improve session performance and overall user experience.
In a previous refactor, we reduced several blocking operations on the server, allowing for more efficient communication between the Agent and Client. However, the session record still relied on blocking operations, which limited performance.
The core idea of this improvement was removing more operations over the communication between Agent and Client communication, and turning session record frame asynchronous using …
=> feat(ssh): simplify session, improve record, and record any PTY

ui/src/layouts/AppLayout.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
- Set `min-height` for `.v-container` to maintain viewport height
with header offset
- Updated `background-image` color to use CSS variable for theme
compatibility with dynamic primary color
=> fix(ui): improve container height and theme compatibility

ui/src/components/Containers/Container.vue, ui/src/views/Containers.vue, ui/tests/components/Containers/Container.spec.ts, ui/tests/components/Containers/__snapshots__/Container.spec.ts.snap
- Replaced `v-tabs` with `v-btn-group` for container navigation
with active state highlighting
- Modified search field to use "outlined" variant with `prepend-inner-icon`
for better alignment and spacing
- Removed redundant `v-card` wrappers for layout simplification
=> refactor(ui): update container view

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_82.go, api/store/mongo/migrations/migration_82_test.go
Implement new field on migration, for namespace
- following ideas from https://github.com/shellhub-io/issues/issues/30 and https://github.com/shellhub-io/cloud/issues/2025
- Add `type` as new field for namespace model since https://github.com/shellhub-io/shellhub/pull/4237
=> feat: migration for add field type on namespace

ui/src/components/Connector/ConnectorList.vue, ui/src/components/Namespace/NamespaceApiKeyList.vue, ui/src/components/Namespace/NamespaceMemberList.vue, ui/src/components/PrivateKeys/PrivateKeyList.vue, ui/src/components/PublicKeys/PublicKeysList.vue, ui/src/components/Sessions/SessionList.vue, ui/src/components/Tables/DeviceTable.vue, ui/src/components/Tags/TagList.vue, ui/src/components/firewall/FirewallRuleList.vue, ui/src/views/ConnectorDetails.vue, ui/src/views/Connectors.vue, ui/src/views/DetailsDevice.vue, ui/src/views/DetailsSessions.vue, ui/tests/components/Connectors/ConnectorList.spec.ts, ui/tests/components/Connectors/__snapshots__/ConnectorList.spec.ts.snap, ui/tests/components/Containers/__snapshots__/ContainerPendingList.spec.ts.snap, ui/tests/components/Containers/__snapshots__/ContainerRejectList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DevicePendingList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DeviceRejectedList.spec.ts.snap, ui/tests/components/Namespace/__snapshots__/NamespaceApiKeyList.spec.ts.snap, ui/tests/components/PrivateKeys/PrivateKeyList.spec.ts, ui/tests/components/PublicKeys/PublicKeyList.spec.ts, ui/tests/components/PublicKeys/__snapshots__/PublicKeyList.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap, ui/tests/components/firewall/FirewallRuleList.spec.ts, ui/tests/components/firewall/__snapshots__/FirewallRuleList.spec.ts.snap, ui/tests/views/__snapshots__/DetailsDevice.spec.ts.snap, ui/tests/views/__snapshots__/DetailsSessions.spec.ts.snap, ui/tests/views/__snapshots__/FirewallRules.spec.ts.snap, ui/tests/views/__snapshots__/Sessions.spec.ts.snap
Replaced v-chip with v-btn as the activator component across several list
components.
Updated button styles to align with the application's design system:
variant="plain", border, rounded, and bg-v-theme-background.
Added appropriate data-test attributes for testability.
Changed icon to mdi-format-list-bulleted for consistent visual
representation.
Renamed router navigation target from detailsConnectors to ConnectorDetails in
ConnectorList.vue.
=> feat(ui): update action triggers in lists to use v-btn for consistency

gateway/nginx/conf.d/shellhub.conf
- Redirects requests to `/api/namespaces/{tenant-id}/members/invites` to the `cloud-api`.
- Supports the new invitation links feature, enabling users to generate and manage namespace invitations.
=> feat(gateway): add support for invitation links

ui/src/components/Team/Member/MemberEdit.vue, ui/tests/components/Team/Member/__snapshots__/MemberEdit.spec.ts.snap
The `v-bind="$props"` directive was removed from the `MemberEdit.vue`
component. This binding was unnecessary and has been cleaned up
to simplify the code.
=> fix(ui): remove unused binding in MemberEdit component

ui/src/api/http.ts, ui/src/store/modules/auth.ts, ui/src/store/plugins/api.ts, ui/src/views/Login.vue
- Introduced `getConfiguration` and `setConfiguration` methods to `BaseAPI`.
- Added a `reloadConfiguration` function to reapply settings across APIs.
- Updated the auth module to integrate configuration updates on login.
- Enhanced `apiPlugin` to reload configuration after authentication success.
- Redirected users to the home page post-login in `Login.vue`.
=> feat(api): add configuration management to BaseAPI

ui/package-lock.json
This reverts commit ee2c3c7a2460d7dddb238e030ef5732d04478f49.
See: https://github.com/vuejs/language-tools/issues/5018
=> Revert "ui: bump typescript from 5.6.3 to 5.7.2 in /ui"

ui/src/components/Namespace/NamespaceEdit.vue, ui/src/components/Setting/SettingNamespace.vue, ui/src/components/Setting/SettingProfile.vue, ui/src/components/User/UserDelete.vue, ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap, ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
This Pull Request resolves an error in the build method caused by the Vuetify
variant attribute being set to an empty string. The fix introduces a
paragraph element to replace the input field when it is not in editing mode.
=> fix(ui): adjust settings inputs to use flat variant when not editing

ui/src/views/Setup.vue, ui/src/views/SignUp.vue
This pull request improves input validation, error handling, and user feedback in the account setup and sign-up flows. The changes aim to enhance the user experience by providing clearer messages and ensuring stricter input validation.
Validation Enhancements:
Updated username validation rules:
Required field.
Must be 3-32 characters.
Can only contain lowercase letters, numbers, and specific symbols (-_.@).
Added descriptive error messages for validation failures.
Improved password validation:
Required field.
Must be 5-32 characters.
Includes detailed error messages for length constraints.
Refactoring:
Simplified computed property syntax in Setup.vue (e.g., hasSign).
Adjusted hasErrors() in SignUp.vue to include the privacy policy acceptance check.
UI Updates:
Updated button states in …
=> fix(ui): enhance user input validation and error handling

ui/src/layouts/AppLayout.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This PR enhances the behavior and visibility management of menu items in the AppLayout component. The changes focus on dynamically enabling or disabling items, improving child filtering logic, and ensuring more accurate state handling.
Key Changes
Dynamic Menu Item States:
Introduced a disableItem function to disable menu items based on specific conditions (e.g., namespaces or user permissions).
Applied the :disabled attribute to relevant menu items.
Filtered Child Items:
Added a getFilteredChildren function to exclude hidden child menu items from rendering.
Namespace Handling:
Updated the namespacedInstance computed property to better control the visibility of the "Billing" submenu.
Simplified and replaced hasNamespace with namespacedInstance logic.
Reactive Items:
Converted items from a …
=> fix(ui): enhance menu behavior and item visibility

ui/src/components/Setting/SettingBilling.vue, ui/tests/components/Setting/__snapshots__/SettingBilling.spec.ts.snap
Adjusted SettingOwnerInfo to only render if the user lacks authorization
(v-if="!hasAuthorization").
Moved BillingDialog and its container to render only when the user has
authorization (v-else).
Updated related snapshot tests to reflect new conditional rendering logic.
=> fix(ui): conditional rendering for billing components

ui/src/authorizer.ts, ui/src/components/AppBar/Notifications/Notification.vue, ui/src/components/Team/ApiKeys/ApiKeyGenerate.vue
This PR introduces several improvements to the notification handling and authorization logic in the UI. These updates modernize the code structure, enhance role-based permissions, and improve the maintainability of critical components.
Key Changes:
Authorizer Update:
Added actions.notification.view to the authorizer object to enable role-based access to notification views.
Notification.vue Refactor:
Migrated to <script setup> syntax for better readability and alignment with modern Vue practices.
Simplified computed properties and watchers, consolidating logic for fetching and displaying notifications.
Improved error handling for notifications, ensuring consistency across edge cases.
ApiKeyGenerate.vue Enhancement:
Updated role logic by replacing isOwner with isAdmin to support both …
=> fix(ui): enhance notification and authorization logic in UI components

ui/src/components/AppBar/Notifications/Notification.vue
Introduced the `style` prop again in the Notification component to allow
customizable styling. The prop supports both string and object types,
with a default value of `undefined`.
=> fix(ui): re-add `style` prop to Notification component

ui/src/api/client/api.ts, ui/src/components/Tunnels/TunnelCreate.vue, ui/src/components/Tunnels/TunnelList.vue, ui/src/interfaces/ITunnel.ts, ui/src/store/api/tunnels.ts, ui/src/store/modules/tunnels.ts, ui/tests/components/Tunnels/TunnelCreate.spec.ts, ui/tests/components/Tunnels/TunnelList.spec.ts, ui/tests/components/Tunnels/__snapshots__/TunnelList.spec.ts.snap
This PR introduces Time-To-Live (TTL) support and expiration management for tunnels. It includes updates to the API, frontend components, and tests to accommodate the new TTL feature. Users can now specify a tunnel's TTL when creating it and view its expiration details in the tunnel list.
Changes
API Updates
Added ttl field:
CreateTunnelRequest and Tunnel interfaces now support ttl for tunnel creation.
Backend API methods (listTunnels, createTunnel) updated to handle TTL and pagination (page, perPage).
New expiration fields:
expires_in added to Tunnel to represent expiration details.
Frontend Updates
TunnelCreate.vue:
Added a combobox for TTL selection with predefined timeouts (e.g., 1 minute, 1 hour, 1 week).
Validates TTL input using yup.
TunnelList.vue:
Displays expiration date …
=> feat(ui): add TTL support and expiration management

ui/src/components/Tables/DeviceTable.vue, ui/tests/components/Containers/__snapshots__/ContainerList.spec.ts.snap, ui/tests/components/Containers/__snapshots__/ContainerPendingList.spec.ts.snap, ui/tests/components/Containers/__snapshots__/ContainerRejectList.spec.ts.snap
Now the device table can show dinamically:
- Operating System: For devices
- Image: For containers
=> fix(ui): show 'Image' instead 'Operating System' for containers

ui/src/components/Tunnels/TunnelCreate.vue, ui/tests/components/Tunnels/TunnelCreate.spec.ts
This PR introduces support for a custom timeout option in the tunnel creation dialog. Instead of only selecting from predefined timeout values, users can now choose a "Custom Expiration" option and manually input a timeout in seconds.
Changes
UI Updates:
Replaced v-combobox with v-select for timeout selection.
Added a v-text-field for custom timeout input, displayed when "Custom Expiration" is selected.
Logic Improvements:
Introduced selectedTimeout state to handle both predefined and custom values.
Used a computed property for the ttl value to dynamically determine the timeout.
Adjusted validation and form reset behavior to support custom timeout values.
Testing Enhancements:
Updated unit tests to check visibility and functionality of the new custom timeout input.
Added a test case to …
=> refactor(ui): add custom timeout option for tunnel creation

ui/src/components/Containers/ContainerAdd.vue, ui/src/views/Containers.vue, ui/tests/components/Containers/ContainerAdd.spec.ts, ui/tests/components/Containers/__snapshots__/ContainerAdd.spec.ts.snap
This feature is still not functional, as the script (for agent installation in containers) is not implemented yet.
=> feat(ui): add 'Add Docker Host' button and dialog

ui/src/components/Terminal/TerminalDialog.vue, ui/tests/components/Containers/__snapshots__/ContainerList.spec.ts.snap, ui/tests/components/Devices/__snapshots__/DeviceList.spec.ts.snap, ui/tests/components/QuickConnection/__snapshots__/QuickConnectionList.spec.ts.snap, ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap, ui/tests/views/__snapshots__/DetailsDevice.spec.ts.snap
- Adjust fullscreen logic to depend on `showLoginForm`
- Ensure terminal rendering is contained within a positioned div
- Remove unnecessary `v-card-item` wrapping the terminal
- Improve terminal initialization and WebSocket connection handling
- Add event listener for window resize to properly fit terminal
- Remove `variant="underlined"` from input fields for consistency
- Fix WebSocket initialization and resize handling
- Adjust styles to properly position the terminal
=> feat(ui): improve fullscreen behavior and terminal rendering

ui/src/layouts/AppLayout.vue, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Also switch icons between Containers and Connectors, as the Connectors icon seems to be more appropriate for Containers menu item.
=> feat(ui): hide 'Connectors' from App bar

ui/src/components/Sessions/SessionPlay.vue, ui/tests/views/__snapshots__/Sessions.spec.ts.snap
Refactored the session playback dialog to be fullscreen by default,
removing fixed width constraints. Merged controls into the title bar,
including play/pause, time slider, and speed selection, improving
usability and layout efficiency. Adjusted terminal styling for proper
positioning within the fullscreen container.
=> feat(ui): improve session playback UI and fullscreen support

ui/src/components/Terminal/TerminalDialog.vue, ui/src/router/index.ts
This PR enhances the terminal dialog behavior by automatically opening it when navigating to the /devices/:id/terminal route.
TerminalDialog.vue
Added useRoute from Vue Router.
Watched the route path to toggle showTerminal when the user navigates to /devices/:id/terminal.
router/index.ts
Defined a new route /devices/:id/terminal mapped to DeviceDetails to enable direct access to the terminal view.
This improves user experience by allowing direct navigation to a device's terminal without requiring manual interaction.
Navigated to /devices/:id/terminal, and the terminal opened automatically.
Verified that other routes did not trigger unintended behavior.
=> feat(ui): auto-open terminal on specific route

ui/src/components/Terminal/TerminalDialog.vue
This PR enhances the terminal dialog by allowing users to close it using the Escape key. This improves usability and accessibility, especially for keyboard users.
Added @keyup.esc="close()" to TerminalDialog.vue
Ensures the terminal dialog closes when the Escape key is pressed
Improves user experience by providing a familiar keyboard shortcut
Enhances accessibility for users who prefer keyboard navigation
Open the terminal dialog
Press the Escape key and verify that the dialog closes
Ensure existing functionality (clicking outside to close) still works as expected
=> feat(ui): close dialog on Escape key press

ui/src/components/Terminal/TerminalDialog.vue
This PR refactors the TerminalDialog.vue component to enhance the user experience when interacting with the ESC key and improves dialog behavior under specific conditions.
ESC Key Handling:
Replaced the default @keyup.esc listener with a custom handleEscKey function.
Implemented double-tap ESC functionality: pressing ESC twice within 400ms will close the terminal when the login form is hidden.
Dialog Behavior Fixes:
Fixed an issue where the login form did not reset correctly after closing the terminal.
Adjusted conditions related to showLoginForm when toggling the terminal visibility.
Code Cleanup:
Removed the onKeyStroke import as it’s no longer used.
Simplified conditional rendering for better readability.
Open the terminal dialog.
ESC Key Test:
When the login form is hidden, press ESC …
=> fix(ui): improve terminal dialog behavior and ESC key handling

ui/src/components/Terminal/TerminalDialog.vue
Ensure `max-width` is correctly determined based on `showLoginForm` and
screen size.
=> fix(ui): adjust TerminalDialog max-width logic

ui/src/components/AppBar/AppBar.vue, ui/src/components/User/PaywallChat.vue, ui/src/main.ts, ui/src/store/modules/auth.ts, ui/src/store/modules/support.ts, ui/tests/components/AppBar/AppBar.spec.ts, ui/tests/components/AppBar/__snapshots__/AppBar.spec.ts.snap, ui/tests/components/Users/PaywallChat.spec.ts, ui/tests/components/Users/__snapshots__/PaywallChat.spec.ts.snap, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This PR introduces a paywall mechanism for chat support access in the AppBar component. Users in a cloud environment with an active subscription can access Chatwoot support, while community users or non-subscribers are redirected to a paywall.
Changes
UI Updates
Added PaywallChat component to AppBar.vue.
Exposed chatSupportPaywall state for conditional rendering.
Logic & State Management
Refactored openShellhubHelp to handle different cases (Cloud, Enterprise, Community).
Introduced chatSupportPaywall state in Vuex support module.
Updated openChatwoot function for better structure and maintainability.
Modified AppBar.spec.ts to test new paywall logic.
Added mock data for billing and environment settings.
Cloud User with Active Billing
Click on "Support" → Chatwoot should open.
Cloud User …
=> feat(ui): add paywall check for chat support access

ui/src/interfaces/INamespace.ts, ui/src/store/api/namespaces.ts
This PR updates the INamespaceSettings interface by making its properties optional. This prevents potential undefined property access issues and improves flexibility when handling namespace settings.
Updated INamespaceSettings to mark connection_announcement and session_record as optional (? modifier).
Made settings in INamespaceResponse optional to allow for cases where settings might be omitted.
Modified the putNamespace function to handle optional settings safely using optional chaining (?.).
Prevents runtime errors when settings or its properties are missing.
Enhances API flexibility by allowing partial updates without requiring all settings fields.
This change ensures existing functionality remains intact while preventing crashes due to missing properties.
API calls that previously …
=> fix(ui): make namespace settings properties optional

ui/src/components/AppBar/AppBar.vue, ui/src/components/Namespace/Namespace.vue, ui/src/components/User/UserWarning.vue
The following warning was displayed:
```
► [Vue warn]: Extraneous non-props attributes (data-test) were passed to component but could not be automatically inherited because component renders fragment or text or teleport root nodes.
```
That happened because some components (specifically `Namespace.vue`, `UserWarning.vue`, and `AppBar.vue`) have more than one element as the root of the template, and Vue was trying to inherit the `data-test` attribute determined in the parent component to the children components. Since there's more than one root element, the inheritance failed and the warning was shown.
This PR adds the following snippet to the specified components:
```javascript
defineOptions({
inheritAttrs: false,
});
```
This is a [Vue's …
=> fix(ui): fix Vue's attribute inheritance warnings

ui/src/store/modules/auth.ts
This pull request fixes an issue that the chatwoot module would warn an onMounted
and onBeforeUnmounted because the chatwoot module was called before it's
usage.
=> fix(ui): declare useChatwoot on auth store only when it will be used

ui/src/components/Setting/SettingProfile.vue, ui/tests/components/Setting/SettingProfile.spec.ts, ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
This PR adds a disabled MFA switch with an explanatory tooltip for Community accounts. Previously, the MFA option on the profile settings page wasn't visible for Community. Now, it appears as a disabled switch with a tooltip stating "Only available for Cloud or Enterprise accounts!" to improve user understanding. The responsiveness of the MFA card was improved too, limiting the width of the text in smaller screens, preventing it from "hiding" the switch button. I've added a basic unit test for this switch and updated the snapshot.
=> feat(ui): improve profile settings UI

ui/src/store/api/users.ts
This PR fixes the error caused in the users API store by the `getSessionRecord`, that does not exist in the API anymore ─ it was replaced by `checkSessionRecord`, but this change wasn't made in the store. This pull request fixes this.
Closes #4605
=> fix(ui): fix `getSessionRecord` error

ui/src/components/Setting/SettingProfile.vue
This PR makes some refactorings in the `SettingProfile.vue` code.
I replaced some useless `computed`s with an object destructuring since these properties weren't reactive. I also removed some `envVariables` from the template, using the destructured values directly. An useless `eslint-disable` comment was removed too.
=> refactor(ui): profile settings component

ui/src/api/client/api.ts, ui/src/components/Team/Member/MemberInvite.vue, ui/src/interfaces/INotifications.ts, ui/src/store/api/namespaces.ts, ui/src/store/modules/namespaces.ts, ui/tests/components/Team/Member/MemberInvite.spec.ts
This PR introduces a new feature that allows users to generate an invitation link for team members instead of sending an email invitation. The implementation improves flexibility in the invitation process, enabling users to share the invite link directly.
- Updated MemberInvite.vue to include a checkbox for selecting the invite method (email or link).
- Introduced a new UI section to display the generated invite link.
- Added copy-to-clipboard functionality for easier link sharing.
- ### State Management & API Integration:
- Added Vuex state management for storing and retrieving invitation links.
- Implemented generateInvitationLink and sendEmailInvitation actions in the namespaces module.
- Created mutations to store and retrieve the generated invite link.
- Separated invite logic into …
=> feat(ui): add invite link generation for adding new namespace member

ui/admin/src/App.vue, ui/admin/src/layouts/AppLayout.vue, ui/admin/src/layouts/SimpleLayout.vue, ui/admin/src/router/index.ts, ui/admin/src/store/modules/auth.ts, ui/admin/src/store/modules/license.ts, ui/admin/tests/unit/store/modules/Auth.spec.ts
This PR refactors layout handling and authentication flow in the admin UI to be more maintainable and consistent. It shifts from component-level logic to a router-driven approach using route metadata and Vue's <script setup> syntax.
- Migrated App.vue, SimpleLayout.vue, and AppLayout.vue to <script setup> for cleaner syntax.
- Replaced onMounted logic in App.vue with centralized auth/layout handling in router.beforeEach.
- Added meta.layout and meta.requiresAuth fields to route definitions.
Updated router guard to:
```
1. Apply the correct layout via layout/setLayout.
2. Redirect unauthenticated users when required.
```
- Normalized layout naming (SimpleLayout, AppLayout) for consistency.
-Fixed isLoggedIn getter to return a boolean instead of the token itself.
Separation of concerns: …
=> refactor(ui): centralize layout handling and simplify auth check

ui/src/components/Team/Member/MemberInvite.vue, ui/src/store/modules/namespaces.ts
This PR removes `console.error` statements in the store, that caused Axios errors in the MemberInvite component tests. Additionally, it removes a misspelled "bg-whitea" Vuetify class that had no visual effect, and adds proper margin to the email input to separate its error messages from the role input, improving readability.
=> fix(ui): fix MemberInvite errors

ui/src/components/Sessions/SessionPlay.vue, ui/src/store/modules/sessions.ts
Previously, the session store used the same variable to store the session details object and the recording logs, alternating between the two, depending on the use case. This PR fixes this, creating a separate variable and methods for the logs, for more clarity. The methods' names in `SessionPlay.vue` were also updated to keep the component and the store aligned.
=> fix(ui): separate session state in store

ui/admin/src/components/Instance/SSO/ConfigureSSO.vue, ui/admin/src/components/Settings/SettingsAuthentication.vue, ui/admin/tests/unit/components/Settings/SettingsAuthentication/__snapshots__/index.spec.ts.snap
This pull request refactors how Single Sign-On (SSO) toggling is handled within the authentication settings view. It introduces improved state handling using computed properties and ensures UI elements are only rendered when relevant. It also updates associated snapshot tests to reflect these changes.
- Replaces direct dialog.value = false call with a close() utility method in ConfigureSSO.vue.
- Wraps the SSO UI block with v-if="samlEnabled" to prevent unnecessary rendering when SAML is disabled.
- Converts localEnabled and samlEnabled from ref to computed properties for better reactivity and two-way binding.
- Updates the set behavior of samlEnabled to dispatch a disabling payload when toggled off.
- Adjusts the DOM structure in SettingsAuthentication.vue to ensure layout remains …
=> refactor(ui): improve SSO toggle logic and UI rendering

ui/src/components/QuickConnection/QuickConnection.vue, ui/src/components/QuickConnection/QuickConnectionList.vue, ui/tests/components/QuickConnection/QuickConnection.spec.ts
This PR refactors the Quick Connection dialog to improve its structure,
readability, and maintainability. It also enhances the user interaction 
experience and brings consistency to both the UI and tests.
- Collapsed verbose markup into single-line elements for cleaner templates
- Updated `v-text-field` styling to use `outlined` variant and surface background
- Replaced static column headers with dynamic `headers` array for cleaner code
- Refined keyboard shortcut handling using `useMagicKeys`
- Updated test selectors to align with new dynamic header logic
- Improved empty state message for clarity ("No online device" → 
"There are currently no devices online")
These changes streamline the component code, improve testability, and lay the
groundwork for future enhancements like dynamic …
=> refactor(ui): streamline dialog structure and inputs

ui/src/components/Sessions/Player.vue, ui/tests/components/Sessions/Player.spec.ts
This PR removes the `getSessionDimensions` method, previously used to extract session dimensions as a workaround for buggy recordings. With the underlying recording issue resolved, this method is no longer needed.
The player’s `fit` option is now set to `"both"`, enabling proper resizing in both directions and preventing horizontal text overflow.
The test suite has also been cleaned up—unnecessary `flushPromises` calls were removed, and `wrapper.vm.$nextTick` calls were replaced with Vue's `nextTick`.
Depends on [cloud's #2201](https://github.com/shellhub-io/cloud/pull/2201)
=> fix(ui): fix player errors

ui/src/components/Sessions/Player.vue, ui/src/components/Setting/SettingBilling.vue
This PR replaces native `addEventListener` calls with VueUse’s `useEventListener` composable in the player and billing settings components for consistency with the rest of the codebase.
Note: the remaining `addEventListener` calls in the player component are part of the Asciinema API implementation, not native DOM listeners, and therefore cannot be replaced with useEventListener.
=> refactor(ui): replace native DOM event listeners with useEventListener

ui/src/components/Snackbar/SnackbarNew.vue, ui/src/helpers/snackbar.ts, ui/src/layouts/AppLayout.vue, ui/src/plugins/snackbar.ts, ui/src/store/modules/snackbar.ts, ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
This PR refactors the Snackbar system in the Community edition to, in the future, replace the previous setup, built around four components and a dedicated store, with a simplified, plugin-based approach using a single component.
This sets the foundation for migrating existing components and views to the new system. That migration, along with test updates, will follow in subsequent PRs after this one is approved.
=> refactor(ui): refactor new Snackbar component

ui/src/components/Sessions/Player.vue, ui/tests/components/Sessions/__snapshots__/Player.spec.ts.snap
This PR refactors the player's script by replacing manual updates to the formatted time and duration with computed properties, improving reactivity and code clarity. It also removes a duplicated and unnecessary call to `clearCurrentTimeUpdater`.
=> refactor(ui): use computed and remove duplicated method in Player

ui/src/components/Tunnels/TunnelDelete.vue
This PR disables the attribute inheritance in `TunnelDelete.vue`, since this behavior caused warnings due to the lack of a single root element in the component's template.
=> fix(ui): fix extraneous non-props warning in `TunnelDelete`

ui/src/api/http.ts, ui/src/components/AppBar/AppBar.vue
This PR removes the deprecated `createNewClient` method in `http.ts` and its last reference in `AppBar.vue`.
=> refactor(ui): remove deprecated `createNewClient` method

ui/src/components/Tags/TagSelector.vue
This PR replaces Vuetify's deprecated `active-color` attribute with the new `color` attribute in `TagSelector.vue`, preventing warnings in the console.
=> fix(ui): replace deprecated `active-color` attribute with `color`

install.sh
This PR adds podman support to install.sh
It looks for podman before docker as aliasing docker with podman with `alias docker=podman` is a common scenario and attempting to use the docker params would cause issues.
It also installs the container as `root` but further PRs are being investigated to look at rootless options
**Test Environment**
```
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (Xfce)"
$ podman --version 
podman version 5.4.2
``` 
**Tested as root and user with the following output**
```
TENANT_ID=<TENENT-ID> SERVER_ADDRESS=https://cloud.shellhub.io sh ./install.sh 
🛠️ Welcome to the ShellHub Agent Installer Script
📝 Summary of chosen options:
- Server address: https://cloud.shellhub.io
- Tenant ID: <TENENT-ID>
- Install method: podman
- Agent version: v0.18.2
🐳 …
```
=> feat: podman support

ui/src/components/Tunnels/TunnelCreate.vue
This PR adds validation to the custom timeout input when creating a tunnel, restricting values to integers between 1 and 9.223.372.036, matching the change in [Cloud's PR #2204](https://github.com/shellhub-io/cloud/pull/2204/files) and preventing errors in the back-end.
=> fix(ui): limit tunnel custom ttl and add validation to input

ui/admin/src/components/Announcement/AnnouncementList.vue, ui/admin/src/components/Device/DeviceList.vue, ui/admin/src/components/FirewallRules/FirewallRulesList.vue, ui/admin/src/components/Namespace/NamespaceList.vue, ui/admin/src/components/Sessions/SessionList.vue, ui/admin/src/components/User/UserList.vue, ui/admin/tests/unit/views/Announcements/Announcements.spec.ts, ui/src/components/Connector/ConnectorList.vue, ui/src/components/Devices/DeviceListChooser.vue, ui/src/components/PublicKeys/PublicKeysList.vue, ui/src/components/QuickConnection/QuickConnectionList.vue, ui/src/components/Sessions/SessionList.vue, ui/src/components/Tables/DeviceTable.vue, ui/src/components/Team/ApiKeys/ApiKeyList.vue, ui/src/components/firewall/FirewallRuleList.vue
This PR fixes a typo in multiple components, where "perPage" was written as "perPagae". A test mock was also added since some Axios warnings started to be thrown in the tests console.
=> refactor(ui): fix "perPagae" typo

ui/src/components/Setting/SettingTags.vue, ui/tests/components/Setting/SettingTags.spec.ts, ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap
This PR removes code related to the private keys feature of `SettingTags.vue`, since there's no relation between them in that scenario. Also, the component's `data-test` attributes were updated, along with the test suite name, plugins, and snapshot.
=> refactor(ui): update SettingTags code

ui/src/components/Setting/SettingBilling.vue, ui/src/components/Setting/SettingNamespace.vue, ui/src/components/Setting/SettingProfile.vue, ui/src/views/Settings.vue, ui/tests/views/__snapshots__/Settings.spec.ts.snap
This PR relocates the shared .v-container styles from individual Setting components (SettingBilling.vue, SettingNamespace.vue, and SettingProfile.vue) to the parent Settings.vue file. This change consolidates redundant style definitions into a single location, improving maintainability and ensuring consistent styling across all settings-related views.
Removed .v-container styles from:
- SettingBilling.vue
- SettingNamespace.vue
- SettingProfile.vue
Added .v-container styles to:
- Settings.vue
By centralizing the .v-container styles, we reduce duplication and make future adjustments simpler and less error-prone. This promotes better adherence to DRY (Don't Repeat Yourself) principles and improves code readability.
Impact
No functional changes to the application.
Improved maintainability …
=> chore(ui): relocate .v-container styles to Settings view

ui/admin/src/global-components.d.ts, ui/src/global-components.d.ts
This PR removes the `global-components.d.ts` files, which caused problems with TypeScript and the `vue` package.
=> fix(ui): delete problematic global components declarations

ui/src/components/AppBar/AppBar.vue
This PR adds an error snackbar to the support button when the environment is not supported, an edge case that didn't give any visual feedback to the user (except by a console error).
=> fix(ui): add snackbar error for support unsupported env case

ui/admin/src/components/User/UserExport.vue
This PR fixes some typos in the admin's `UserExport` component.
1. fixes the radio buttons text; both were "Namespaces with more than". Changed to "Users with more than" and "User with exactly".
2. fixes a typo in the if-else block that determines the `.csv` file name.
=> fix(ui): fix typos in UserExport

ui/src/views/FirewallRules.vue
This PR fixes the `href` attribute that redirects the user to the firewall rules section in ShellHub Docs.
=> fix(ui): fix firewall rules docs URL

ui/src/components/Tunnels/TunnelCreate.vue
This PR fixes the `useField` identifier in `TunnelCreate.vue`.
=> fix(ui): fix field name in TunnelCreate

ui/src/components/Sessions/Player.vue, ui/src/utils/playerPlayback.ts, ui/tests/components/Sessions/Player.spec.ts
This PR fixes the player's playback time formatting, making it behave properly in sessions longer than 1 day. The formatting logic was rewritten and moved to a separate util file. The tests were also updated to test the new util behavior.
=> fix(ui): fix player playback time for sessions longer than 24h

ui/src/views/Containers.vue
This PR simplifies the logic for displaying the container addition component in the Containers.vue view. Key changes include:
Replaced the conditional ConnectorAdd slot with a direct ContainerAdd component.
Removed the now-unnecessary refresh method and its 10-second delay logic.
Cleaned up unused imports: ConnectorAdd and handleError.
This refactor removes legacy connector logic, improves clarity, and reduces unused code.
The conditional rendering based on envVariables.hasConnector is no longer needed, and maintaining legacy ConnectorAdd logic created unnecessary complexity.
Only affects the UI logic related to adding containers. No backend or data-fetching logic is impacted.
=> refactor(ui): change Connector Add to Container Modal in empty Containers view

ui/src/components/Sessions/SessionList.vue, ui/src/components/Sessions/SessionPlay.vue, ui/tests/views/__snapshots__/Sessions.spec.ts.snap
This PR adds a tooltip to the SessionPlay button for cases where the session was not recorded, giving the correct visual feedback. Additionally, the tooltip-related code was moved to `SessionPlay.vue`, and the component's props were refactored.
=> feat(ui): add tooltip to SessionPlay for not recorded sessions

ui/src/views/DetailsSessions.vue
This PR updates the props passed to the `SessionPlay` component in `DetailsSession.vue`, aligning with the updates made in PR #4888, fixing the component's behavior, and preventing the UI's build from failing.
=> fix(ui): update SessionPlay props in DetailsSessions

ui/src/components/Namespace/NamespaceAdd.vue
Use computed `openVersion` to reflect `isCommunity` from env vars.
This enables conditional UI behavior based on environment config.
=> fix(ui): change namespace add panel using env flag

ui/admin/src/components/Namespace/NamespaceExport.vue, ui/admin/src/hooks/namespaceExport.ts, ui/admin/src/interfaces/IFilter.ts, ui/admin/tests/unit/views/Namespaces/__snapshots__/index.spec.ts.snap
This PR refactors `NamespaceExport.vue`, improving its typing, separating and cleaning logic, and improving the UI/UX.
=> refactor(ui): refactor admin's NamespaceExport

ui/admin/src/components/Announcement/AnnouncementDelete.vue, ui/admin/src/components/Announcement/AnnouncementEdit.vue, ui/admin/src/components/Announcement/AnnouncementList.vue, ui/admin/src/components/Settings/SettingsAuthentication.vue, ui/admin/src/components/Settings/SettingsLicense.vue, ui/admin/src/store/modules/announcement.ts, ui/admin/src/views/NewAnnouncement.vue
This pull request keeps consistent error handling across multiple components in the admin UI by removing `console.error` calls. Some unnecessary try/catch blocks were removed, and error handling is now done with the util `handleError` where needed.
=> refactor(ui): remove `console.error` calls

ui/admin/src/components/User/UserFormDialog.vue, ui/admin/src/components/User/UserList.vue, ui/admin/src/components/User/UserStatusChip.vue, ui/admin/src/interfaces/IUser.ts, ui/admin/src/store/api/users.ts, ui/admin/src/store/modules/auth.ts, ui/admin/src/views/UserDetails.vue, ui/admin/tests/unit/components/User/UserFormDialog/index.spec.ts, ui/admin/tests/unit/components/User/UserList/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/components/User/UserList/index.spec.ts, ui/admin/tests/unit/components/User/UserStatusChip/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/components/User/UserStatusChip/index.spec.ts, ui/admin/tests/unit/views/UserDetails/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/views/UserDetails/index.spec.ts
This pull request fixes some bugs in the admin's users panel, focusing on replacing the old `confirmed` boolean with a new `status` field for user confirmation states. It also includes updates to improve code clarity and consistency, such as the introduction of the `UserStatusChip` component for displaying user statuses and refactoring related logic.
* Replaced the outdated and buggy `confirmed` boolean with a `status` field. Updated all related logic and UI components to use `status` instead of `confirmed`, fixing a related bug due to changes in the API.
* Added `UserStatusChip` component to display user statuses in a standardized format across the UI. 
* Refactored the `loginToken` function to accept `userId` directly instead of a user object. Updated all references accordingly.
* …
=> fix(ui): fix admin's user list

ui/src/components/Terminal/Terminal.vue, ui/src/utils/crypto.ts, ui/src/utils/validate.ts
This PR addresses incorrect handling of base64-encoded SSH challenges during WebSocket authentication and improves terminal initialization timing.
- Base64 decoding: SSH challenges are now correctly decoded using Buffer.from(..., "base64") before signing.
- Signature output cleanup: Removed encodeURIComponent wrapping from the RSA signature function to preserve raw base64 format.
- Function typings: Refined types for inputs and outputs related to signing utilities.
- Terminal setup order: Reordered onMounted logic to register terminal event listeners before opening and focusing the terminal.
Previously, the base64 challenge string was used directly without decoding, leading to invalid signatures. Additionally, the signature was URL-encoded unnecessarily, potentially corrupting its …
=> fix(ui): correct SSH challenge signing with base64 input

ui/src/components/Containers/ContainerList.vue, ui/src/components/Containers/ContainerPendingList.vue, ui/src/components/Containers/ContainerRejectedList.vue, ui/src/components/Devices/DeviceList.vue, ui/src/components/Devices/DevicePendingList.vue, ui/src/components/Devices/DeviceRejectedList.vue, ui/src/components/Tables/DeviceTable.vue, ui/src/interfaces/IContainer.ts, ui/src/interfaces/IDevice.ts, ui/src/store/modules/container.ts, ui/src/store/modules/devices.ts, ui/src/utils/storeMethods.ts, ui/tests/components/Tables/DeviceTable.spec.ts
This pull request fixes the sorting functionality for containers and devices in the `DeviceTable` component. Now, a `setSort` store method is passed to that component, enabling updates in the sorting config inside the store and the correct sort behavior in the UI. Interfaces and tests were also updated properly.
=> fix(ui): fix device/container sorting in DeviceTable

api/store/mongo/migrations/migration_91.go
MongoDB automatically creates collections when inserting documents into non-existent collections, making the explicit CreateCollection call unnecessary. Removing this method eliminates potential errors from multiple executions.
=> fix(api): remove redundant CreateCollection method

ui/src/components/Sessions/SessionPlay.vue
This pull request adds a loading state to the "Play Session" button, informing the user when the session is loading just before being played. This is useful for larger sessions that have some delay when being fetched to be played.
=> feat(ui): add loading state to Play Session button

ui/src/components/QuickConnection/QuickConnection.vue
This pull request includes a minor change to the `QuickConnection.vue` file. The change removes the `min-height` property from the `<v-card>` element, leaving only the `max-height` property. This change improves the element's responsiveness, since the `min-height` set to 700px was leading to problems in screens with less than 700px of height available.
=> fix(ui): fix quick connection card min-height

ui/src/components/Terminal/Terminal.vue
This PR fixes a bug where the terminal would not resize correctly if the signature process had not completed. Previously, the resize event listener was registered unconditionally on mount, which caused issues when the terminal was not fully initialized.
`handleJsonMessage()` after the signature process completes.
`handleWebSocketMessage()` when a text blob is received (password-based logins).
Ensured the resize handler only attaches when the terminal is ready.
Removed the unconditional resize registration in `onMounted()`.
1. Start the signature process but do not complete it.
2. Resize the browser window.
3. The terminal does not resize properly.
1. Verify the terminal resizes correctly during and after the signature process.
2. Test both signature-based and password-based logins.
3. …
=> fix(ui): restore resize handling during incomplete signature

api/services/device.go, api/services/device_test.go
When two devices with same hostname or identity are registered, device's lookup API method called be SSH service could return the wrong device when SSH connection is requested. Since only “accepted” devices should be reachable, we now constrain the lookup to devices in the accepted state. This ensures SSH connections always target the correct, approved device.
=> fix(ssh,api): return from device's lookup only accepted ones

ui/src/components/Terminal/Terminal.vue, ui/tests/components/Terminal/Terminal.spec.ts
This pull request removes a redundant `isReady` ref in `Terminal.vue`. Since the WebSocket already has a `readyState` variable used to keep track of the state, that ref is unnecessary.
=> refactor(ui): remove redundant `isReady` ref in Terminal component

ui/src/components/Terminal/Terminal.vue
This pull request fixes a bug in the web terminal where it always initialized with the default 80x24 dimensions, independently of the available space. This PR fixes this by ensuring the `fitAddon` is called before the WebSocket initialization, sending the correct dimension values from the start.
=> fix(ui): fit terminal before opening WebSocket connection

ui/src/components/Terminal/TerminalHelper.vue
This PR updates the v-text-field inside the TerminalHelper.vue component to:    
- Replace append-icon with append-inner-icon
- Update @click:append to @click:append-inner
These changes ensure the copy icon correctly appears inside the input field and functions when clicked.
=> fix(ui): correct copy icon behavior in command field

ui/admin/src/components/Namespace/NamespaceEdit.vue
This pull request fixes a bug in the admin's NamespaceEdit component, where trying to edit the namespace's `max_devices` property returned `422 Unprocessable Entity`. This bug was happening because the component was sending the `max_devices` new value as a string, not as a number, in the `PUT` request. This PR fixes this and improves the ref name inside the component.
=> fix(ui): fix NamespaceEdit error when changing max devices number

ui/admin/src/components/Instance/SSO/ConfigureSSO.vue, ui/admin/tests/unit/components/Instance/SSO/index.spec.ts, ui/src/utils/crypto.ts, ui/src/utils/validate.ts
This PR fixes and enhances the SAML SSO configuration flow by introducing validation for the X.509 certificate field. It ensures that users provide a valid certificate in PEM format before submitting the configuration form.
- Added validateX509Certificate utility to verify X.509 certificates using sshpk.
- Display inline error messages for invalid or empty certificate fields.
- Improved the hasError computed logic to account for certificate validity.
- Refactored how SAML mapping data is constructed and validated.
- Ensured only non-empty mappings are submitted.
- Prevents invalid X.509 certificates from being submitted.
- Improves user feedback with clear validation errors.
- Reduces chances of SAML misconfiguration due to bad input.
- Attempted to submit form with empty and malformed …
=> fix(ui): validation for X.509 certificate in SAML config

ui/src/components/Team/Member/MemberInvite.vue
This pull request fixes the invitation with link functionality in the `MemberInvite.vue` component. The payload was being sent with the `role` in uppercase, causing problems with authorization. Now it sends the correct role in lowercase. A method to generate the payload was also added, reducing code duplication, since both link and email invitations use the same payload structure.
=> fix(ui): fix member's role case when inviting with link

ssh/web/session.go, ssh/web/utils.go, ssh/web/websocket.go, ssh/web/websocket_test.go
The previous implementation of the web terminal used `uint8` for the
column and row dimensions. This limited the maximum values to 255, which
could lead to display issues when users attempted to set larger terminal
sizes. Such limitations could hinder user experience, especially in
scenarios where larger terminal dimensions are required for better
visibility and usability.
To address this issue, we have updated the implementation to use
`uint32` for parsing terminal dimensions, in accordance with RFC 4254
specifications. This change allows the web terminal to support a much
larger range of dimensions, up to 4,294,967,295, thus preventing errors
and display issues when users specify larger sizes.
=> fix(ssh): resolve terminal dimension limitations by aligning with RFC 4254

ui/src/components/Team/ApiKeys/ApiKeyEdit.vue, ui/src/components/Team/ApiKeys/ApiKeyGenerate.vue, ui/src/components/Team/ApiKeys/ApiKeyList.vue, ui/src/components/Team/Member/MemberEdit.vue, ui/src/components/Team/Member/MemberInvite.vue, ui/src/components/Team/Member/MemberList.vue, ui/src/components/Team/RoleSelect.vue, ui/src/interfaces/INamespace.ts, ui/tests/components/Team/ApiKeys/ApiKeyGenerate.spec.ts, ui/tests/components/Team/ApiKeys/__snapshots__/ApiKeyList.spec.ts.snap, ui/tests/components/Team/Member/MemberEdit.spec.ts, ui/tests/components/Team/RoleSelect/RoleSelect.spec.ts, ui/tests/components/Team/RoleSelect/__snapshots__/RoleSelect.spec.ts.snap, ui/tests/views/__snapshots__/TeamApiKeys.spec.ts.snap, ui/tests/views/__snapshots__/TeamMembers.spec.ts.snap
This pull request refactors role selection across multiple components by introducing a reusable `RoleSelect` component and simplifying role-related logic. Additionally, it removes redundant code and ensures consistent capitalization for role display. 
Affected components:
- `MemberInvite.vue`
- `MemberEdit.vue`
- `ApiKeyGenerate.vue`
- `ApiKeyEdit.vue`
Tests and snapshots were also added/updated.
=> refactor(ui): add reusable `RoleSelect` component

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_107.go, api/store/mongo/migrations/migration_107_test.go, pkg/models/system.go, ui/admin/src/api/client/api.ts, ui/admin/src/components/Instance/SSO/ConfigureSSO.vue, ui/admin/src/components/Settings/SettingsAuthentication.vue, ui/admin/src/interfaces/IInstance.ts, ui/admin/src/store/api/instance.ts, ui/admin/src/store/modules/instance.ts, ui/admin/tests/unit/components/Instance/SSO/index.spec.ts, ui/admin/tests/unit/components/Settings/SettingsAuthentication/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/components/Settings/SettingsAuthentication/index.spec.ts, ui/admin/tests/unit/store/modules/instance.spec.ts
This pull request updates the admin's UI to support both POST and Redirect URLs for SAML configuration instead of a single signon URL.
=> feat(ui): update SAML configuration to support POST and Redirect URLs

api/store/mongo/migrations/main.go, api/store/mongo/migrations/migration_107.go, api/store/mongo/migrations/migration_107_test.go, pkg/models/system.go
- Add migration 107 to transform signon_url into bidingf object
- Update SystemIdpSAML model to use binding with post/redirect fields
- Maintain backward compatibility through migration down function
- Add comprehensive tests migrations
BREAKING CHANGE: SAML configuration now uses binding object instead of signon_url string
=> feat(api): restructure SAML signon_url to support multiple URL types

ui/src/components/PrivateKeys/PrivateKeyAdd.vue, ui/src/components/PrivateKeys/PrivateKeyEdit.vue, ui/src/components/PrivateKeys/PrivateKeyList.vue, ui/src/components/Terminal/Terminal.vue, ui/src/components/Terminal/TerminalDialog.vue, ui/src/components/Terminal/TerminalLoginForm.vue, ui/src/interfaces/IPrivateKey.ts, ui/src/interfaces/ITerminal.ts, ui/src/main.ts, ui/src/nodespecific.ts, ui/src/utils/crypto.ts, ui/src/utils/validate.ts, ui/tests/components/PrivateKeys/PrivateKeyAdd.spec.ts, ui/tests/components/PrivateKeys/PrivateKeyEdit.spec.ts, ui/tests/components/Terminal/TerminalLoginForm.spec.ts, ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap, ui/tests/components/Terminal/__snapshots__/TerminalLoginForm.spec.ts.snap
This pull request fixes a bug in the `PrivateKeyEdit` component that, when the private key list changed (some key being added or deleted), the values of the edit dialog didn't change, resulting in a mismatch between the item in the list and the data in the dialog.
Depends on #5109
=> fix(ui): fix `PrivateKeyEdit` reactivity

ui/src/layouts/AppLayout.vue, ui/tests/layouts/AppLayout.spec.ts
This PR introduces a visual "BETA" label to navigation items that are both marked as beta and only available in cloud environments. This helps users identify experimental or in-development features more clearly when using the cloud version of the application.
Added a v-chip with the label "BETA" to applicable nav items in AppLayout.vue
The chip is conditionally rendered when:
- item.isBeta is true
- envVariables.isCloud is true
- Updated snapshot tests to reflect the new UI rendering logic
Providing a clear visual indicator for beta features improves transparency and sets appropriate expectations for users. Limiting this to cloud deployments ensures that only relevant users see the label.
- Manually verified that the BETA chip appears only for items meeting the conditions
- Snapshot tests …
=> fix(ui): show beta chip for cloud-only beta nav items

ui/src/components/firewall/FirewallRuleAdd.vue
This pull request fixes the Active and Action selects in `FirewallRuleAdd`. The component was refactored, and erroneously these selects have been left with `:model-value` instead of `v-model`, breaking its reactivity and sending the wrong data to the back-end. That PR fixes that and, additionally, ensures that those selects are reset when the dialog is closed.
=> fix(ui): fix active and action selects in `FirewallRuleAdd`

gateway/certbot.go, gateway/certbot_test.go, gateway/main.go
Introduces a step to verify required parameters, and create necessary directories before attempting certificate generation or renewal, improving reliability and error handling.
Also, we Renamed TunnelsCertificate to WebEndpointsCertificate for more descriptive semantics and updates related constructors and tests accordingly.
=> feat(gateway): add pre-generation validation and clarify certificate type naming

ui/src/store/modules/auth.ts
This PR fixes a bug where the name value was not initialized before making MFA-related API calls. As a result, recoverMfa and requestResetMfa could fail due to missing or incorrect identifiers.
The name value is required for MFA recovery and reset operations. Without explicitly initializing it from localStorage, these functions could behave unexpectedly or fail entirely if name.value is empty or undefined.
Load name from localStorage in:
- recoverMfa
- requestMfaReset
1. Simulate an MFA recovery or reset flow without prior setting of name.
2. Confirm that the name is correctly loaded from localStorage.
3. Ensure the API calls succeed with the expected parameters.
=> fix(ui): ensure name is loaded before MFA recovery and reset

ui/src/components/Sessions/SessionPlay.vue, ui/src/store/api/sessions.ts, ui/tests/store/modules/sessions.spec.ts
This pull request corrects the API call for deleting session logs and the behavior of the components when dealing with deleted logs.
* Fixed the `deleteSessionLogs` function in `sessions.ts` to use the correct `deleteSessionRecord` API endpoint instead of the incorrect `clsoeSession` method.
* Improved error handling in the `displayDialog` method in `SessionPlay.vue` to show an error message if session logs are missing or deleted, instead of opening the dialog with no logs.
=> fix(ui): fix session log deletion

Makefile, api/entrypoint-dev.sh, devscripts/add-device, ssh/entrypoint-dev.sh
Replace old openssl genrsa command with openssl genpkey to generate RSA private keys in PKCS#8 format by default. This modernizes key generation across all services and scripts.
Closes #5219
=> fix(api,ssh): update script that generate private keys in pkcs8 format

ui/admin/tests/unit/views/Device/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/views/Device/index.spec.ts, ui/admin/tests/unit/views/FirewallRules/__snapshots__/index.spec.ts.snap, ui/admin/tests/unit/views/FirewallRules/index.spec.ts
This PR updates the admin UI unit tests and snapshots for Device and FirewallRules to align with the updated backend model where tags are now represented as objects instead of simple strings.
It also refreshes mock data to reflect the new schema and updates related snapshots accordingly.
Converted tags from strings to objects ({ tenant_id, name, created_at, updated_at }).
Updated snapshots to display test-tag instead of old string values (tag1, xxxx, yyyy).
- Renamed mockDevices → devices.
- Added a second mock device with corresponding snapshot row.
- remote_addr → remoteAddr
- OS info changed from Ubuntu → Linux Mint
- Updated timestamps (last_seen, created_at) and namespaces.
- Adjusted status icons (success → error for offline, etc.).
- Renamed mockFirewallRules → firewallRules.
- …
=> fix(ui): align Device & FirewallRules tests with tag objects

ui/src/store/modules/tags.ts, ui/tests/components/Containers/ContainerList.spec.ts, ui/tests/components/Devices/DeviceList.spec.ts, ui/tests/components/PublicKeys/PublicKeyList.spec.ts, ui/tests/components/Tags/TagCreate.spec.ts, ui/tests/components/Tags/TagEdit.spec.ts, ui/tests/components/Tags/TagFormUpdate.spec.ts, ui/tests/components/Tags/TagList.spec.ts, ui/tests/components/Tags/TagRemove.spec.ts, ui/tests/components/Tags/TagSelector.spec.ts, ui/tests/components/Tags/__snapshots__/TagList.spec.ts.snap, ui/tests/views/DetailsDevice.spec.ts, ui/tests/views/PublicKeys.spec.ts
This pull request cleans up tests related to the new tags' refactor and fixes warnings and errors caused by missing mocks to the new API routes. It also removes unnecessary `console.error` calls in the Tags store.
=> fix(ui): fix warnings and errors in tag-related tests

ui/admin/src/components/Device/DeviceList.vue, ui/admin/src/components/Namespace/NamespaceList.vue, ui/admin/src/components/User/UserList.vue, ui/admin/src/store/modules/devices.ts, ui/admin/src/store/modules/namespaces.ts, ui/admin/src/store/modules/users.ts, ui/admin/src/views/Device.vue, ui/admin/src/views/Namespaces.vue, ui/admin/src/views/Users.vue
This PR introduces improvements to how filters and sorting are managed for the Devices, Users and Namespace sections in the admin UI. Specifically:
Moved filter, sortField, and sortOrder state into their respective stores (devices, users and namespace) using reactive variables.
Updated fetchDeviceList, fetchNamespaces and fetchUsersList to default to the store's current filter/sort values if none are explicitly passed.
- Moved loading.value = false into finally blocks to prevent spinner hangs.
- Simplified filter formatting code in Device.vue, Users.vue and Namespaces.vue.
- Verified filters persist across search calls.
- Ensured fallback to stored values when parameters are not explicitly passed.
- Checked that loading indicators behave correctly on success/failure.
=> fix(ui): persist filters and sorting in several admin stores

ui/src/App.vue, ui/src/store/modules/layout.ts, ui/tests/store/modules/layout.spec.ts
This pull request changes the Layout store in the main UI to initialize the `layout` state as an empty value. This prevents a bug where the initial value `AppLayout` was used before the layout was properly set by the router's `beforeEach` guard, causing problems like unnecessary API calls related to the AppLayout in places that didn't use it (e.g. Login page).
=> fix(ui): start layout state in store as an empty value

ui/src/components/PrivateKeys/PrivateKeyAdd.vue, ui/src/components/PrivateKeys/PrivateKeyDelete.vue, ui/src/components/PrivateKeys/PrivateKeyEdit.vue, ui/src/components/PublicKeys/PublicKeyAdd.vue, ui/src/components/PublicKeys/PublicKeyDelete.vue, ui/src/components/PublicKeys/PublicKeyEdit.vue, ui/src/components/firewall/FirewallRuleAdd.vue, ui/src/components/firewall/FirewallRuleDelete.vue, ui/src/components/firewall/FirewallRuleEdit.vue, ui/tests/components/PrivateKeys/PrivateKeyAdd.spec.ts, ui/tests/components/PrivateKeys/PrivateKeyDelete.spec.ts, ui/tests/components/PrivateKeys/__snapshots__/PrivateKeyEdit.spec.ts.snap, ui/tests/components/PublicKeys/PublicKeyAdd.spec.ts, ui/tests/components/PublicKeys/PublicKeyDelete.spec.ts, ui/tests/components/PublicKeys/PublicKeyEdit.spec.ts, ui/tests/components/PublicKeys/__snapshots__/PublicKeyEdit.spec.ts.snap, ui/tests/components/firewall/FirewallRuleAdd.spec.ts, ui/tests/components/firewall/FirewallRuleDelete.spec.ts, ui/tests/components/firewall/FirewallRuleEdit.spec.ts
This PR refactors the UI codebase to standardize and streamline all modal dialog usage by replacing BaseDialog with the new shared components: FormDialog and MessageDialog.
- Replaced BaseDialog with FormDialog in PrivateKeyAdd.vue and PrivateKeyEdit.vue
- Replaced BaseDialog with MessageDialog in PrivateKeyDelete.vue
- Replaced BaseDialog with FormDialog in PublicKeyAdd.vue and PublicKeyEdit.vue
- Replaced BaseDialog with MessageDialog in PublicKeyDelete.vue
- Replaced BaseDialog with FormDialog in FirewallRuleAdd.vue and FirewallRuleEdit.vue
- Replaced BaseDialog with MessageDialog in FirewallRuleDelete.vue
Modified all component tests to target FormDialog and MessageDialog
Improved assertions to validate props such as title, icon, confirmText, etc.
Removed legacy test selectors tied to …
=> refactor(ui): unify dialogs using new shared dialog components

ui/src/components/PublicKeys/PublicKeyAdd.vue, ui/src/components/PublicKeys/PublicKeyEdit.vue, ui/src/components/firewall/FirewallRuleAdd.vue, ui/tests/components/PublicKeys/PublicKeyAdd.spec.ts, ui/tests/components/PublicKeys/PublicKeyDelete.spec.ts, ui/tests/components/PublicKeys/PublicKeyEdit.spec.ts
This PR addresses several issues introduced in the recent dialog refactor:
- Build errors caused by missing or incorrect TypeScript typings.
- Incorrect usage of ref<{}> now corrected to use Record<string, unknown>.
- Improved typing in normalizeStoreItems for safer tag parsing.
- Fixed default filter types with explicit union types (SelectDeviceFilter, SelectNameFilter).
- Cleaned up filterList and usernameList with clearly typed SelectOption<T>.
- defineExpose now properly exposes usernameError and hostnameError for validation support in PublicKeyAdd.vue.
- Minor cleanup in FirewallRuleAdd.vue: removed unused variant="underlined" prop.
- Test update in PublicKeyDelete.spec.ts:
- Uses a named VueWrapper type alias for clarity and IDE support.
1. Ensure the UI builds without errors (pnpm …
=> fix(ui): correct types and expose errors in dialog refactor

ui/src/components/Namespace/NamespaceAdd.vue, ui/src/components/Namespace/NamespaceDelete.vue, ui/src/components/Namespace/NamespaceEdit.vue, ui/src/components/Namespace/NamespaceInstructions.vue, ui/src/components/Namespace/NamespaceLeave.vue, ui/tests/components/Namespace/NamespaceEdit.spec.ts, ui/tests/components/Namespace/NamespaceLeave.spec.ts, ui/tests/components/Namespace/__snapshots__/NamespaceEdit.spec.ts.snap, ui/tests/components/Namespace/__snapshots__/NamespaceLeave.spec.ts.snap
This pull request refactors the namespace-related dialogs in the UI to use new, more specialized dialog components, improving consistency, maintainability, and user experience. It also updates related tests to match the new dialog implementations.
- `NamespaceAdd`, `NamespaceEdit` → `FormDialog`
- `NamespaceDelete`, `NamespaceLeave` → `MessageDialog`
- `NamespaceInstructions` → `WindowDialog`
=> refactor(ui): migrate Namespaces components to new dialog system

ui/src/components/Tags/TagCreate.vue, ui/src/components/Tags/TagEdit.vue, ui/src/components/Tags/TagFormUpdate.vue, ui/src/components/Tags/TagRemove.vue, ui/tests/components/Tags/TagCreate.spec.ts, ui/tests/components/Tags/TagFormUpdate.spec.ts, ui/tests/components/Tags/TagRemove.spec.ts
This PR refactors all tag-related components to replace the use of the legacy BaseDialog component with the newer, more flexible FormDialog and MessageDialog components.
**TagCreate.vue**
Replaced BaseDialog with FormDialog, added confirmDisabled logic, and updated structure/styling.
**TagEdit.vue**
Switched to FormDialog, improved validation handling, and aligned logic with TagCreate.
**TagFormUpdate.vue**
Integrated FormDialog for improved UX and consistent layout. Dialog is now confirm-disabled with inline tag creation.
**TagRemove.vue**
Migrated from BaseDialog to MessageDialog, streamlined dialog confirmation flow, and removed unused methods.
- TagCreate.spec.ts
- TagFormUpdate.spec.ts
- TagRemove.spec.ts
All tests now validate dialog rendering, event emissions, and UI changes …
=> refactor(ui): replace BaseDialog with FormDialog/MessageDialog in tags

ui/src/components/WebEndpoints/WebEndpointCreate.vue, ui/src/components/WebEndpoints/WebEndpointDelete.vue, ui/tests/components/WebEndpoints/WebEndpointCreate.spec.ts, ui/tests/components/WebEndpoints/WebEndpointDelete.spec.ts
This PR modernizes the dialogs in the Web Endpoints feature by replacing the legacy BaseDialog component with the shared FormDialog and MessageDialog components. This brings consistency to the UI and simplifies dialog logic.
- Migrated to FormDialog
- Hooked up confirm, cancel, and close actions
- Disabled confirm when validation errors are present
- Initialized alertText as an empty string and reset on close
- Reset fields (including device selection) when closing
- Simplified validation rules and error handling
- Improved axios error path and snackbar usage
- Migrated to MessageDialog
- Added confirm/cancel/close bindings
- Moved permission check (canDeleteWebEndpoint) alongside dialog usage
- Simplified update flow after deletion
- Updated selectors to match FormDialog and …
=> refactor(ui): migrate web endpoints to new generic dialog

ui/src/components/Devices/DeviceAdd.vue, ui/src/components/Team/ApiKeys/ApiKeySuccess.vue, ui/tests/components/Team/ApiKeys/ApiKeySuccess.spec.ts
This pull request refactors `ApiKeySuccess` and `DeviceAdd` to use CopyWarning in their fields, ensuring a more secure use by blocking copying in non-secure contexts.
* Replaces direct clipboard API usage and snackbar calls in `DeviceAdd.vue` and `ApiKeySuccess.vue` with the `CopyWarning` component, which now manages copying and user feedback. 
* Refactors tests in `ApiKeySuccess.spec.ts` to mock the `@vueuse/core` clipboard composable instead of the native clipboard API, ensuring tests align with the new implementation. Updates assertions to expect info-level snackbar messages and to check for the presence of the warning dialog on error.
=> refactor(ui): use `CopyWarning` in new copy components

agent/server/modes/host/command/command_docker.go, agent/server/modes/host/command/command_native.go
Add support for populating the SSH_CLIENT environment variable on incoming SSH connections. This allows shells and scripts running on the server to detect the client IP, source port, and server port for the session, improving compatibility with remote shell behaviors (e.g., Bash reading ~/.bashrc for non-interactive sessions).
This change aligns with standard SSH behavior and helps scripts and monitoring tools identify remote clients reliably.
=> feat(ssh): set SSH_CLIENT environment variable for remote sessions

agent/server/modes/host/utils_freebsd.go
To reproduce the error you can run `go mod tidy`:
```shell
λ go mod tidy
go: finding module for package github.com/shellhub-io/shellhub/agent/pkg/server/modes/host/command
go: github.com/shellhub-io/shellhub/agent/server/modes/host imports
github.com/shellhub-io/shellhub/agent/pkg/server/modes/host/command: module github.com/shellhub-io/shellhub@latest found (v0.20.1, replaced by ../), but does not contain package github.com/shellhub-io/shellhub/agent/pkg/server/modes/host/command
```
=> fix(agent): fix import path
